- main.py
Forgot the TV Shows, please replicate to line 220:
`seen_date = (episode.lastViewedAt if episode.lastViewedAt else datetime.now())
eps.instance.mark_as_seen(seen_date)`
> Sync last viewed date from Plex to Trakt

- README.md
Extracted out of https://github.com/Taxel/PlexTraktSync/pull/25
Maybe this gets merged sooner
> Wordwrap readme for readability on console

- Pipfile
- Pipfile.lock
- README.md
I ran into conflicts with globally installed pip packages that I could not resolve anymore.
Altho I'm not daily Python programmer, I used my existing work to setup pipenv:
- https://github.com/tracboat/tracboat/pull/57
The sync script works again!
> Add pipenv based setup

- main.py
> log in script folder

- get_env_data.py
- main.py
Allows to sync [Plex managed users](https://support.plex.tv/articles/203948776-managed-users/) (local users without Plex account) 
closes #42
> Add Plex managed users support

- clear_trakt_collections.py
Loads trakt user credentials in the same way as in main.py.
Using the pytrakt store.
> update trakt user loading

- README.md
See https://github.com/Taxel/PlexTraktSync/pull/101#discussion_r559511480
> Add 2fa link in readme

- main.py
Changed I added so far to this PR :
1. respect POST requests interval to avoid rate-limit errors (instead of going full speed and get many 429 errors)
2. when 429 error (rate limit exceeded) is raised, read and apply the Retry-After value from trakt header 
3. if 429 error is raised too much time for the same request, it aborts this request to avoid infinite loop
4.  correction of logging error message
Important : the Retry-After value can be read from response only when [this PR](https://github.com/moogar0880/PyTrakt/pull/138) of PyTrakt will be merged. So we should **wait before merging this**.
Nota: TVshow episodes are synced one by one because of the PyTrakt module structure, which is not great (read [here](https://github.com/moogar0880/PyTrakt/issues/132)) therefore trakt rate limit …
> Respect trakt POST rate limit

- .gitignore
Extracted from https://github.com/Taxel/PlexTraktSync/pull/116
> Update .gitignore with absolute paths and add .idea

- clear_trakt_collections.py
- config.py
- get_env_data.py
- main.py
- plex_trakt_sync/path.py
Extracted from https://github.com/Taxel/PlexTraktSync/pull/127
@twolaw please approve!
> Add path module for path related variables

- plex_trakt_sync/main.py
See commit messages for details.
> Various bugfixes and logic error fixes

- plex_trakt_sync/config.py
- plex_trakt_sync/get_env_data.py
It shouldn't be `get_env_data` concern how to save config to disk.
> Refactor: Add save() method to Config class

- README.md
I wanted to document the Python versions we support and ended up doing some other cosmetics as well.
Version | Released | Security Support | Release
-- | -- | -- | --
3.9 | 5 months ago(05 Oct 2020) | Ends in 4 years and 6 months(05 Oct 2025) | 3.9.2
3.8 | 1 year and 5 months ago(14 Oct 2019) | Ends in 3 years and 7 months(14 Oct 2024) | 3.8.8
3.7 | 2 years and 8 months ago(27 Jun 2018) | Ends in 2 years and 3 months(27 Jun 2023) | 3.7.10
3.6 | 4 years ago(23 Dec 2016) | Ends in 9 months(23 Dec 2021) | 3.6.13
3.5 | 5 years ago(30 Sep 2015) | Ended 6 months ago(13 Sep 2020) | NA
3.4 | 7 years ago(16 Mar 2014) | Ended 2 years ago(18 Mar 2019) | NA
3.3 | 8 years ago(29 Sep 2012) | Ended 3 years and 5 months ago(29 Sep 2017) | NA
2.7 | 10 years ago(03 Jul 2010) | Ended 1 year and 2 months …
> Documentation: Improve wording and formatting in readme

- plex_trakt_sync/config.py
This is needed for to reload .env again.
Fixes https://github.com/Taxel/PlexTraktSync/issues/153, https://github.com/Taxel/PlexTraktSync/issues/154
> Fix config initialization recursive loop on first run

- Pipfile
- Pipfile.lock
- requirements.txt
Nothing useful here yet, but upgrading allows to implement multiple watchings in the future:
- https://github.com/Taxel/PlexTraktSync/discussions/146#discussioncomment-507622
refs:
- https://github.com/pkkid/python-plexapi/pull/704
> Update plexapi to 4.5.0

- Pipfile
- Pipfile.lock
- main.py
- plex_trakt_sync/cli.py
- requirements.txt
This adds click framework support, allowing to control options from the command-line.
Adding actual commandline arguments will be submitted as future PRs.
NOTE:
> Feature: Use click package for command line parsing

- plex_trakt_sync/logging.py
- plex_trakt_sync/main.py
This makes log entries INFO and above also appear on the console. Thus simplifying code not requiring to do duplicate print and logging.
> Update logging configuration to add stdout logger

- .dockerignore
- Dockerfile
This does nothing else, only recipe to build docker image.
This is a minimal version, a building block to fine-tune some other nuances later.
> Add dockerfile to build the app

- plex_trakt_sync/main.py
- plex_trakt_sync/requests_cache.py
Extracted from https://github.com/Taxel/PlexTraktSync/pull/122 making it smaller.
> Refactor: Add requests_cache module wrapper

- plex_trakt_sync/main.py
https://github.com/pkkid/python-plexapi/issues/706
> Identify as PlexTraktSync for X-Plex-Platform header

- plex_trakt_sync/commands/sync.py
- plex_trakt_sync/plex_api.py
This simplifies sync code to process sections of wanted types only and exposing implementation detail (ShowSection/MovieSection classes).
> Add movies and shows accessors to PlexApi

- plex_trakt_sync/main.py
- plex_trakt_sync/plex_api.py
- Add PlexLibrarySection class
- Add PlexMovieItem class
- Handle old imdb id guid
- Update to use filtering based on new classes
> Refactor Movies processing

- LICENSE.md
refs:
- https://github.com/Taxel/PlexTraktSync/issues/157
> Add/update copyright notices 

- plex_trakt_sync/commands/sync.py
- plex_trakt_sync/main.py
- plex_trakt_sync/trakt_api.py
Since search is `GET` method, the rate limits are handled by https://github.com/Taxel/PlexTraktSync/pull/176
> Add find_movie trakt api method

- plex_trakt_sync/commands/sync.py
- plex_trakt_sync/main.py
- plex_trakt_sync/plex_api.py
- plex_trakt_sync/trakt_api.py
Movie ratings are synced now with PlexApi and TraktApi classes.
> Refactor: Sync ratings using Plex/Trakt API classes

- plex_trakt_sync/commands/sync.py
- plex_trakt_sync/main.py
- plex_trakt_sync/plex_server.py
This removes its dependency from the main module and prevents a circular dependency loop.
> Move plex_server logic to separate module

- plex_trakt_sync.sh
- Pass arguments to main.py
- Allow calling plex_trakt_sync.sh from any directory
- Do not reset PATH
> Fix portabilty of plex_trakt_sync.sh

- plex_trakt_sync/commands/watch.py
- plex_trakt_sync/trakt_api.py
The first try was rather crude proof of concept:
- https://github.com/Taxel/PlexTraktSync/pull/192
> Refactor Scrobbing to use more cleaner APIs

- plex_trakt_sync/plex_api.py
The same fix for 0.6 as https://github.com/Taxel/PlexTraktSync/pull/172
> Add replace of thetvdb to tvdb

- plex_trakt_sync/commands/sync.py
```
$ ./plex_trakt_sync.sh
INFO: Syncing with Plex xxx and Trakt xxx
INFO: Syncing TV=True, Movies=True
INFO: Loaded Trakt lists in 3.9 seconds
INFO: Server version 1.20.3.3437-f1f08d65b updated at: 2021-03-21 09:32:35
INFO: Recently added: 
Processing Movies   [#######################-------------]   65%  00:00:11
...
```
> Show progressbar when processing section

- plex_trakt_sync/commands/sync.py
Reported in https://github.com/Taxel/PlexTraktSync/issues/220#issuecomment-817191186
> Fix trakt username display on startup

- plex_trakt_sync/commands/sync.py
- plex_trakt_sync/plex_api.py
Remove memoize and results collection in section items.
This should make user progress reporting more interactive.
requires: https://github.com/Taxel/PlexTraktSync/pull/212
> Update progressbar to be more responsive

- plex_trakt_sync/commands/sync.py
- plex_trakt_sync/plex_api.py
This is internal refactor to make code more readable.
> Simplify code by using Plex episode object

- plex_trakt_sync/decorators/rate_limit.py
Requested by @twolaw: https://github.com/Taxel/PlexTraktSync/issues/220#issuecomment-817575080
> Move sleeping messages to debug log level

- plex_trakt_sync/cli.py
- plex_trakt_sync/commands/inspect.py
This is useful to getting info about Plex library item:
- https://github.com/Taxel/PlexTraktSync/discussions/208#discussioncomment-611321
- https://github.com/Taxel/PlexTraktSync/issues/117
```
Usage: main.py inspect [OPTIONS] INPUT
Inspect details of an object
Options:
--help  Show this message and exit.
```
example:
```
./plex_trakt_sync.sh inspect 1234
```
> Add inspect command

- plex_trakt_sync/commands/inspect.py
- plex_trakt_sync/commands/sync.py
- plex_trakt_sync/commands/watch.py
- plex_trakt_sync/plex_api.py
- plex_trakt_sync/trakt_api.py
- tests/test_new_agent.py
- tests/test_tv_lookup.py
Fix consistency of media_type/type names, other minor cleanups.
> Swap media_type/type names

- plex_trakt_sync/plex_api.py
- tests/test_plex_search.py
This adds plex.search to find items by name.
> Add search API to Plex

- Pipfile
- Pipfile.lock
- plex_trakt_sync/trakt_api.py
- requirements.txt
- tests/test_tv_lookup.py
Includes [#141: Add MethodNotAllowedException exception for 405 status code](https://github.com/moogar0880/PyTrakt/pull/141)
refs;
- https://github.com/moogar0880/PyTrakt/pull/144
> Update Pytrakt 3.1.0

- plex_trakt_sync/cli.py
- plex_trakt_sync/commands/trakt_login.py
```
Usage: main.py trakt-login [OPTIONS]
Log in to Trakt Account to obtain Access Token.
Options:
--help  Show this message and exit.
```
Similarly to https://github.com/Taxel/PlexTraktSync/pull/230
> Add trakt login command

- plex_trakt_sync/commands/inspect.py
- plex_trakt_sync/commands/sync.py
- plex_trakt_sync/trakt_api.py
_Refactoring extracted from https://github.com/Taxel/PlexTraktSync/pull/240_
> Add trakt.find_episode method find Trakt episode from Plex episode

- .github/ISSUE_TEMPLATE/bug.md
- .github/ISSUE_TEMPLATE/feature.md
Inspired by https://github.com/reclosedev/requests-cache/commit/e2abb1a3143aeb5b1305f51c573c23c44356302f#commitcomment-49418487
> Add GitHub issue templates for bug and feature

- README.md
People may end up installing `master` branch, which is not what we want.
> Add instructions to install with git

- .gitattributes
- CONTRIBUTING.md
- tests/requirements.txt
refs:
- https://github.com/Taxel/PlexTraktSync/issues/150
> Add running tests doc and requirements file

- plex_trakt_sync/commands/inspect.py
refs:
- https://github.com/Taxel/PlexTraktSync/pull/261
> Inspect: Print git version

- plex_trakt_sync/commands/sync.py
- plex_trakt_sync/plex_api.py
The library must not be excluded from "exclude-libraries" from the config.
Fixes #265
> Add --library option to sync command

- plex_trakt_sync/commands/sync.py
- plex_trakt_sync/media.py
Purpose of this class is to create unified Media object that has Plex and Trakt media items.
This will simplify code where having to pass around plex/trakt pairs, and likely avoid copy-paste errors.
> Refactor: Add Media container

- plex_trakt_sync/media.py
refs:
- https://github.com/Taxel/PlexTraktSync/issues/270
> Skip items on trakt Exceptions

- plex_trakt_sync/commands/sync.py
- plex_trakt_sync/media.py
Add and use methods to Media class consolidating pm/tm/pe/te variables.
Follow up to https://github.com/Taxel/PlexTraktSync/pull/254
> Refactor: Use media object methods

- plex_trakt_sync/media.py
Fixes https://github.com/Taxel/PlexTraktSync/issues/268
> Log as debug for none/local provider items

- plex_trakt_sync/decorators/rate_limit.py
- plex_trakt_sync/media.py
Closes https://github.com/Taxel/PlexTraktSync/issues/279
> Use incremental backoff for other exceptions than RateLimitException

- plex_trakt_sync/config.py
The trace now includes a bit that config could not be parsed:
```
File "/Users/glen/scm/plex/Plugins/PlexTraktSync/plex_trakt_sync/config.py", line 75, in load_json
raise RuntimeError(f"Unable to parse {path}: {e}")
RuntimeError: Unable to parse /Users/glen/scm/plex/Plugins/PlexTraktSync/config.json: Expecting property name enclosed in double quotes: line 16 column 5 (char 327)
```
> Catch json errors from loading config

- plex_trakt_sync/commands/sync.py
Thanks to @twolaw for pointing this out:
- https://github.com/Taxel/PlexTraktSync/issues/228#issuecomment-826142277
The line was lost in refactoring:
- https://github.com/Taxel/PlexTraktSync/pull/194
> Restore adding movies to lists

- tests/conftest.py
- tests/test_batch.py
- tests/test_new_agent.py
- tests/test_plex_search.py
- tests/test_tv_lookup.py
_Extracted test helpers from https://github.com/Taxel/PlexTraktSync/pull/282_
refs:
- https://github.com/Taxel/PlexTraktSync/issues/150
> Tests: Add helpers to create api objects

- plex_trakt_sync/commands/cache.py
The command is intended for debuging.
> Print urls in cache with cache command

- plex_trakt_sync/commands/sync.py
Fulfills https://github.com/Taxel/PlexTraktSync/issues/260 request
> Add --movie option to sync

- Pipfile
- Pipfile.lock
- plex_trakt_sync/version.py
- requirements.txt
Update to fix https://github.com/spapas/python-git-info/issues/9
> Update python-git-info to 0.7.1

- plex_trakt_sync/plex_api.py
Take guid in this order:
- tmdb, tvdb, then imdb
See https://github.com/Taxel/PlexTraktSync/issues/313#issuecomment-838447631
Fixes #313
> Take guid in pre-defined order

- plex_trakt_sync/commands/trakt_login.py
- plex_trakt_sync/trakt_api.py
This ensures trakt related methods/hacks are in trakt_api class.
This avoids regressions like this:
- https://github.com/Taxel/PlexTraktSync/pull/325#issuecomment-855202257
> Add device_auth method to trakt_api

- plex_trakt_sync/commands/webhook.py
- plex_trakt_sync/media.py
- plex_trakt_sync/plex_api.py
- plex_trakt_sync/trakt_api.py
- plex_trakt_sync/walker.py
**IMPORTANT**: This changeset bumps Python minimum version to 3.7:
- https://github.com/Taxel/PlexTraktSync/pull/336
NOTE: searching multiple guids requires to use of the new agent.
Future todo: 
- cleanup old unused methods
- cleanup proxy methods to guid on PlexMediaItem
refs:
- https://github.com/Taxel/PlexTraktSync/issues/318
> Search all guids for a match

- Pipfile
- Pipfile.lock
- README.md
- requirements.txt
Fixes https://github.com/Taxel/PlexTraktSync/issues/334
> Add requests and urllib3 to versioned dependencies

- .envrc
- .gitignore
> Setup .envrc for direnv

- README.md
- plex_trakt_sync/cli.py
- plex_trakt_sync/commands/unmatched.py
- plex_trakt_sync/plex_api.py
- plex_trakt_sync/walker.py
requires https://github.com/Taxel/PlexTraktSync/pull/339 to be merged first
> Add command to display details of unmatched media items

- plex_trakt_sync/commands/sync.py
- plex_trakt_sync/plex_api.py
- plex_trakt_sync/trakt_list_util.py
This gives us better overview and control of HTTP requests caching.
> Update PlexApi to avoid other code calling request_cache directly

- .envrc
- plex_trakt_sync/plex_api.py
- plex_trakt_sync/trakt_api.py
Requires https://github.com/Taxel/PlexTraktSync/pull/347 to be merged first.
> Deprecate .guid wrapper access

- plex_trakt_sync/commands/inspect.py
- plex_trakt_sync/plex_api.py
- plex_trakt_sync/trakt_api.py
- tests/test_new_agent.py
- tests/test_plex_search.py
Resolves deprecations from https://github.com/Taxel/PlexTraktSync/pull/348
> Resolve guid wrapper deprecation

- plex_trakt_sync/plex_api.py
Fixes:
- https://github.com/Taxel/PlexTraktSync/pull/358
> Fix is_legacy_agent being a propery

- plex_trakt_sync/plex_api.py
- tests/test_collection_metadata.py
Refs:
- https://github.com/Taxel/PlexTraktSync/issues/117
Pre-requisite for:
- https://github.com/Taxel/PlexTraktSync/pull/366
> Add collection metadata when adding media to collections

- .gitignore
- plex_trakt_sync/commands/plex_login.py
- plex_trakt_sync/commands/sync.py
- plex_trakt_sync/commands/trakt_login.py
- plex_trakt_sync/config.py
- plex_trakt_sync/factory.py
- plex_trakt_sync/logging.py
- plex_trakt_sync/plex_api.py
- plex_trakt_sync/plex_server.py
- plex_trakt_sync/trakt_api.py
- tests/conftest.py
- tests/test_config.py
This is to cleanup the config api and simplify rest of the code.
> Refactor: Convert "None" and "-" values to empty

- plex_trakt_sync/commands/sync.py
- plex_trakt_sync/logging.py
- plex_trakt_sync/plex_api.py
- plex_trakt_sync/plex_server.py
requires:
- https://github.com/Taxel/PlexTraktSync/pull/351
refs:
- https://github.com/reclosedev/requests-cache/issues/260
> Add caching to Plex requests

- plex_trakt_sync/plex_api.py
- plex_trakt_sync/walker.py
Like with movies, try all providers, not just first.
> Use resolve_any for episodes

- CONTRIBUTING.md
https://github.com/Taxel/PlexTraktSync/issues/117#issuecomment-817119708
> Add description how to share xml from plex

- plex_trakt_sync/commands/trakt_login.py
Clearer instructions for setting up client ID / secret
> Clearer instructions

- plex_trakt_sync/commands/plex_login.py
Explains how to login when 2FA is enabled.
> 2FA prompt

- plex_trakt_sync/decorators/rate_limit.py
- plex_trakt_sync/plex_api.py
> Add retry behavior when resolving guids from plex object

- .github/dependabot.yml
https://github.com/Taxel/PlexTraktSync/network/updates
> add dependabot for github-actions, pip and docker

- plex_trakt_sync/commands/cache.py
- plex_trakt_sync/commands/inspect.py
- plex_trakt_sync/commands/plex_login.py
- plex_trakt_sync/commands/webhook.py
- plex_trakt_sync/decorators/deprecated.py
- plex_trakt_sync/decorators/rate_limit.py
- plex_trakt_sync/logging.py
- plex_trakt_sync/media.py
- plex_trakt_sync/pytrakt_extensions.py
```
$ flake8 . --count --exit-zero --max-complexity=10 --max-line-length=225 --statistics --exclude .direnv/
```
> Cleanup: Apply some flake8 fixes

- plex_trakt_sync/media.py
- plex_trakt_sync/plex_api.py
Fixes https://github.com/Taxel/PlexTraktSync/issues/402
> Skip Plex entries whose guid can not be resolved

- plex_trakt_sync/commands/inspect.py
refs:
- https://github.com/pkkid/python-plexapi/issues/807
> Skip accessing .guids for legacy agent

- plex_trakt_sync/commands/cache.py
```
./plex_trakt_sync.sh cache https://192-168-0-17.d24635b366f04f4c9cfa76d808bd2acb.plex.direct:32400/library/metadata/8057
```
> Add url option to cache to dump cache content

- plex_trakt_sync/commands/sync.py
- plex_trakt_sync/sync.py
This allows to see what changes would be made without actually making these changes.
> Add --dry-run option to sync command

- .github/workflows/docker-image.yml
- Dockerfile
[Create and publish a Docker image to GHCR](https://docs.github.com/en/actions/guides/publishing-docker-images#publishing-images-to-github-packages
) 
on push to main branch and tags
`$ docker pull ghcr.io/taxel/plextraktsync:latest` pulls latest build on main branch
`$ docker pull ghcr.io/taxel/plextraktsync:$tag` pulls $tag
Fixes #411
> Create and publish a Docker image

- plex_trakt_sync/commands/sync.py
- plex_trakt_sync/commands/unmatched.py
- plex_trakt_sync/factory.py
Moves progressbar instantiation to factory.
> Add progressbar factory

- plex_trakt_sync/commands/inspect.py
- plex_trakt_sync/media.py
Fix inspect on episode id giving fatal error.
reported:
- https://github.com/Taxel/PlexTraktSync/issues/452#issuecomment-906918565
- https://github.com/Taxel/PlexTraktSync/pull/453#issuecomment-907449941
> Fix inspect on episode

- config.default.json
- plex_trakt_sync/config.py
- plex_trakt_sync/path.py
This is to simplify docker based deployments putting all files that are updated to a single directory.
> Add env variables to override path for logs/configs/cache

- .gitignore
- docker-compose.yml
Usage:
```
docker-compose run --rm plex-trakt-sync
```
Requires https://github.com/Taxel/PlexTraktSync/pull/457 to be merged first
refs:
- https://github.com/Taxel/PlexTraktSync/issues/411
> Add docker compose config

- Dockerfile
- docker-compose.yml
This simplifies `docker-compose.yml` needed to run the application.
> Move env setup to Dockerfile

- plex_trakt_sync/commands/watch.py
- plex_trakt_sync/listener.py
- tests/test_events.py
Simplifies code, so that progress=100 match can be done with EventDispatcher.
> Refactor: Extract EventDispatcher to own class

- README.md
Replaces https://github.com/Taxel/PlexTraktSync/pull/471
Instructions from https://github.com/Taxel/PlexTraktSync/pull/458
Closes #411
> Add Docker Compose instructions

- plex_trakt_sync/commands/watch.py
- plex_trakt_sync/events.py
- plex_trakt_sync/listener.py
This allows WatchStateUpdater to reset internal cache on server restarts.
> Feature: Add Error event listener to WatchStateUpdater

- .github/workflows/pypi.yml
Based on:
- https://github.com/pkkid/python-plexapi/raw/4.7.1/.github/workflows/pypi.yml
Docs:
- https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries
Needs to setup token:
- https://pypi.org/help/#apitoken
Requires:
- https://github.com/Taxel/PlexTraktSync/pull/263
- https://github.com/Taxel/PlexTraktSync/pull/511
Closes:
- https://github.com/Taxel/PlexTraktSync/issues/414
> Add pypi publish workflow

- plex_trakt_sync/commands/plex_login.py
Unowned server count was listing owned server count.
> Fixed unowned server count

- .github/workflows/pypi.yml
refs:
- https://github.com/Taxel/PlexTraktSync/issues/414
> Run pypi workflow on tags push

- .dockerignore
- .github/workflows/docker-image.yml
Fixes https://github.com/Taxel/PlexTraktSync/issues/517
> Docker: Fix for moved location of config.default.json in .dockerignore

- .github/workflows/docker-image.yml
> Fix multi arch support 

- plex_trakt_sync/media.py
- plex_trakt_sync/sync.py
- plex_trakt_sync/trakt_api.py
This PR adds episodes to ratings sync.
Previously, only movies ratings were sync.
```
2021-10-25 16:17:43,795 INFO[PlexTraktSync]:Rating <tvdb:253463/2/1:<Episode:183:Black-Mirror-s02e01>> with 6 on Plex
2021-10-25 16:18:02,832 INFO[PlexTraktSync]:Rating <tmdb:749670:<Episode:4349:Détective-Conan-s01e01>> with 8 on Trakt
```
closes #485
> Sync episodes ratings

- plex_trakt_sync/commands/sync.py
- plex_trakt_sync/walker.py
The option does nothing, code to add logic behind it is in a future merge request.
> Feature: Add --id option to sync

- plextraktsync/commands/inspect.py
- plextraktsync/trakt_api.py
Inspired from exception trace from https://github.com/Taxel/PlexTraktSync/issues/579
> Add --watched-shows option to inspect

- plextraktsync/commands/sync.py
- plextraktsync/commands/version.py
- plextraktsync/version.py
Add `version()` method that always returns best available version info.
> Feature: Add unified method to get version info

- plextraktsync/commands/inspect.py
Fixes regression from https://github.com/Taxel/PlexTraktSync/pull/582
> Fix inspect supporting multiple ids

- plextraktsync/walker.py
- tests/test_walker.py
Add tests to new logic:
- https://github.com/Taxel/PlexTraktSync/pull/574
> Tests: walk planner using mock objects

- plextraktsync/version.py
- tests/test_version.py
> Cleanup:  Remove deprecations of version module

- plextraktsync/decorators/rate_limit.py
This should help debugging errors like in:
- https://github.com/Taxel/PlexTraktSync/issues/591
> Feature: Add details of last call on error

- plextraktsync/commands/watch.py
- plextraktsync/config.default.json
- plextraktsync/trakt_api.py
adds logic to do pause if watch progress is below threshold:
```py
def stop(self, progress: float):
if progress >= self.threshold:
self.scrobbler.stop()
else:
self.scrobbler.pause()
```
Closes https://github.com/Taxel/PlexTraktSync/issues/603
Needs to be merged first:
- https://github.com/Taxel/PlexTraktSync/pull/604
> Add config to configure trakt auto watch threshold

- Dockerfile
This avoids compilation step every time container is launched
> Docker: Compile sources into docker image

- .gitattributes
See https://github.com/Taxel/PlexTraktSync/discussions/649#discussioncomment-1840586
> Fix: Force LF for .sh files

- plextraktsync/decorators/flatten.py
- plextraktsync/plex_api.py
_Extracted from https://github.com/Taxel/PlexTraktSync/pull/652_
> Feature: Add video_streams property

- plextraktsync/commands/inspect.py
- plextraktsync/console.py
Recommended by documentation:
- https://rich.readthedocs.io/en/latest/console.html#console-api
> Feature: Add single console instance

- plextraktsync/trakt_list_util.py
Use media item `__str__`, so can find media item id, rather just title and year.
> Feature: Use media item str to print item details

- plextraktsync/commands/inspect.py
- plextraktsync/plex_api.py
This prints filenames of media in inspect command
> Feature: Print filenames from media parts

- plextraktsync/commands/inspect.py
Resolves `None` being printed as play date.
> Fix: Use proper field for play history display date

- plextraktsync/decorators/flatten.py
- plextraktsync/plex_api.py
Makes code more readable with yield instead of pushing to results.
> Refactor: Use flatten decorators

- tests/mock_data/673-config.json
- tests/test_config.py
Add config tests for https://github.com/Taxel/PlexTraktSync/issues/673
> Tests: Test config merge logic

- CONTRIBUTING.md
- README.md
> Move GitHub installation method to CONTRIBUTING.md

- Pipfile
- Pipfile.lock
- plextraktsync/decorators/rate_limit.py
- requirements.txt
requires:
- https://github.com/moogar0880/PyTrakt/pull/163
Add better handling of 423 error code:
- https://github.com/Taxel/PlexTraktSync/issues/579#issuecomment-962427562
See also:
- https://github.com/trakt/api-help/issues/228
> Add handling of LockedUserAccountException

- plextraktsync/logging.py
Fixes https://github.com/Taxel/PlexTraktSync/issues/713 a regression from https://github.com/Taxel/PlexTraktSync/pull/664
> Fix log_file not respecting log_dir

- plextraktsync/commands/watch.py
- plextraktsync/config.default.json
Config to enable:
```json
{
"watch": {
"add_collection": true
```
> Feature: Add logic to watch to add items to collection if enabled

- plextraktsync/plex_api.py
- plextraktsync/walker.py
_Extracted from https://github.com/Taxel/PlexTraktSync/pull/720_
The performance gain is explained here:
- https://github.com/Taxel/PlexTraktSync/pull/668
> Performance: Pass plex to PlexLibraryItem for better userRatings fetching

- plextraktsync/media.py
_Extracted from https://github.com/Taxel/PlexTraktSync/pull/720_
> Feature: Add media_type to Media for repeated access

- plextraktsync/media.py
- plextraktsync/trakt_api.py
_Extracted from https://github.com/Taxel/PlexTraktSync/pull/720_
> Feature: support show ratings

- .dockerignore
- Dockerfile
- plextraktsync.sh
To make things symmetric to to pipx and to match readme documentation.
See:
- https://github.com/Taxel/PlexTraktSync/discussions/734#discussioncomment-2007176
> Feature: Add plextraktsync to PATH in docker image

- plextraktsync/trakt_api.py
Deprecated from https://github.com/Taxel/PlexTraktSync/pull/725
> Chore: Cleanup deprecated ratings methods

- plextraktsync/events.py
This is just for completeness.
> Chore: Add TranscodeSession event class

- plextraktsync/commands/watch.py
- plextraktsync/media.py
- plextraktsync/sync.py
- plextraktsync/trakt_api.py
This simplifies usage of the api methods.
> Refactor: Add batch as lazy loaded property

- plextraktsync/commands/watch.py
This helps better understand the messages.
> Feature: Prefix watch messages with method they come from

- plextraktsync/sync.py
- plextraktsync/walker.py
Fixes #707 
Requires:
- https://github.com/Taxel/PlexTraktSync/pull/725
> Feature: Add Show rating sync

- plextraktsync/commands/unmatched.py
- plextraktsync/decorators/memoize.py
- plextraktsync/factory.py
- plextraktsync/media.py
- plextraktsync/plex_api.py
- plextraktsync/pytrakt_extensions.py
- plextraktsync/trakt_list_util.py
- plextraktsync/walker.py
- setup.cfg
Refs:
- https://github.com/Taxel/PlexTraktSync/issues/781
- https://flake8.pycqa.org/en/latest/user/configuration.html
> Cleanup, fix flake8 warnings and errors

- .github/workflows/lint.yml
Refs:
- https://github.com/marketplace/actions/python-flake8-lint
- https://github.com/Taxel/PlexTraktSync/issues/781
> Chore: Setup CI flake8 lint

- plextraktsync/walker.py
Fixes https://github.com/Taxel/PlexTraktSync/issues/781
> Fix: Restore Python 3.8 compatibility

- README.md
Altered Unraid section by adding additional details on utilizing the Community Apps plugin for installation, as well as scheduling a task utilizing the User Scripts plugin (essentially front end cron) to start the container
> Update README with Unraid section

- plextraktsync/config.py
Extracted from https://github.com/Taxel/PlexTraktSync/pull/852
> Refactor: Add ConfigLoader class

- plextraktsync/plex_api.py
Fixes https://github.com/Taxel/PlexTraktSync/issues/882
> Add @rate_limit to fetch_items to commence retrying

- plextraktsync/commands/inspect.py
- plextraktsync/plex_api.py
```
Subtitles:
Subtitle 1: (English) None (format: srt, selected: True, transient: None)
Subtitle 2: (English) None (format: None, selected: False, transient: None)
Subtitle 3: (English) None (format: srt, selected: True, transient: None)
Subtitle 4: (Español) None (format: srt, selected: False, transient: None)
Subtitle 5: (eesti) None (format: srt, selected: False, transient: None)
```
> Feature: Print subtitles information with inspect command

- plextraktsync/cli.py
- plextraktsync/commands/inspect.py
- plextraktsync/commands/subdl.py
- plextraktsync/plex_api.py
- plextraktsync/util/expand_id.py
Currently tested subtitle stream only.
Requires:
- https://github.com/Taxel/PlexTraktSync/pull/885
> Feature: Add command to download subtitles

- setup.cfg
Fixes https://github.com/Taxel/PlexTraktSync/issues/933
> Fix: Add util package to setup.cfg

- .dockerignore
https://github.com/Taxel/PlexTraktSync/issues/949#issuecomment-1162039357
> Fix util packaging for docker

- plextraktsync/decorators/rate_limit.py
- plextraktsync/decorators/retry.py
- plextraktsync/plex_api.py
- plextraktsync/trakt_api.py
Use more logical decorator name than rate_limit than just retry some api
calls from plex or trakt.
> Refactor: Add retry decorator

- plextraktsync/config.default.yml
- plextraktsync/plex_server.py
Allow configuring plex timeout from this app config. for example:
- https://github.com/Taxel/PlexTraktSync/issues/956#issuecomment-1175871380
> Feature: Add plex.timeout configuration

- .github/ISSUE_TEMPLATE/bug.yml
- plextraktsync/cli.py
- plextraktsync/commands/bug_report.py
- plextraktsync/commands/self_update.py
- plextraktsync/util/execx.py
- plextraktsync/util/openurl.py
- plextraktsync/util/versions.py
```
$ ./plextraktsync.sh bug-report
Click this link to create a GitHub issue populated with your configuration:
https://github.com/Taxel/PlexTraktSync/issues/new?template=bug.yml&os=macOS-12.4&python=3.10.5&version=0.20.x
```
inspired by [`starship bug-report`](https://starship.rs/faq/#starship-is-doing-something-unexpected-how-can-i-debug-it)
> Feature: Add bug-report command

- plextraktsync/commands/watch.py
This reverts commit ecfc7e784b113941457c7273ececf77c2c0c9cd9.
fixes #865
> Revert "Marking as watched in Trakt"

- README.md
Add usefull infos in readme for troubleshooting
> Good practice & QA

- plextraktsync/config.default.yml
- plextraktsync/config.py
- plextraktsync/factory.py
This allows to print timestamps. Useful pronbably when using watch command.
> Feature: Add log_console_time config option

- plextraktsync/commands/plex_login.py
Handle BadRequest instead of crashing
see #1028
> Handle plex login BadRequest

- CONTRIBUTING.md
Taken from https://github.com/Taxel/PlexTraktSync/issues/966#issuecomment-1236524825
> Docker instructions for PR install

- .github/workflows/test.yml
- requirements.pipenv.txt
This adds test to ensure Pipfile.lock is up to date:
- https://github.com/Taxel/PlexTraktSync/actions/runs/3088604566
refs:
- 6916b47b
> CI: Test dependencies install with pipenv as well

- plextraktsync/commands/inspect.py
See this url for `{edition-edition  title}` file naming:
- https://support.plex.tv/articles/naming-and-organizing-your-movie-media-files/
> Feature: Print title and edition title in inspect

- plextraktsync/commands/watch.py
- plextraktsync/listener.py
Fixes: https://github.com/Taxel/PlexTraktSync/issues/1079
> Fix: Skip sessions tracking in watch if not available

- plextraktsync/commands/inspect.py
- plextraktsync/plex_api.py
_Extracted from https://github.com/Taxel/PlexTraktSync/pull/1084_
> Feature: Print media duration in inspect command

- plextraktsync/factory.py
- plextraktsync/plex_server.py
A preparation of storing multiple server urls in a separate servers.yml config.
> Refactor PlexServerConnection to support any number of server urls

- plextraktsync/cli.py
- plextraktsync/commands/imdb_import.py
- plextraktsync/media.py
- plextraktsync/trakt_api.py
1. export your imdb user ratings as csv:
- https://help.imdb.com/article/imdb/track-movies-tv/ratings-faq/G67Y87TFYYP6TWAV#
2. run the import, passing csv as commandline argument:
```
➔ plextraktsync imdb-import ratings.csv
Importing movie tt0308476: Kukushka (2002), rated at 2021-02-19
Rating: <Movie>: The Cuckoo with 10 (was None)
Importing movie tt0978764: Sucker Punch (2011), rated at 2016-09-20
Rating: <Movie>: Sucker Punch with 10 (was 10)
Importing show tt2861424: Rick and Morty (2013), rated at 2018-10-20
Rating <TVShow> Rick and Morty with 10 (was None)
```
> Feature: Add imdb-import command

- plextraktsync/commands/plex_login.py
- plextraktsync/util/local_url.py
_Extracted from https://github.com/Taxel/PlexTraktSync/pull/1087_
> Refactor: Extract local_url to own function

- plextraktsync/trakt_api.py
Fixes https://github.com/Taxel/PlexTraktSync/issues/1106
> Fix: Add episodes to valid rating type

- plextraktsync/commands/inspect.py
- plextraktsync/media.py
- plextraktsync/plex_api.py
- plextraktsync/trakt_api.py
Fixes https://github.com/Taxel/PlexTraktSync/issues/1117
> Fix: Support inspect of Show

- plextraktsync/commands/self_update.py
- plextraktsync/util/execp.py
Useful for debugging and understanding what is being executed.
> Feature: print executed commands in self-update

- Dockerfile
- https://alpinelinux.org/posts/Alpine-3.16.0-released.html
> Feature: Build docker image with alpine 3.16

- Pipfile
- Pipfile.lock
- requirements.txt
Update trakt to 3.4.1, Fixes #975:
- https://github.com/glensc/python-trakt/commit/827550a0edab5988a713bfe609bb21bd7d504219
- https://github.com/moogar0880/PyTrakt/pull/181
- https://github.com/moogar0880/PyTrakt/issues/146
> Fix: Catch JSONDecodeError from trakt

- Pipfile
- Pipfile.lock
- requirements.txt
Fixes https://github.com/Taxel/PlexTraktSync/issues/941
> Update trakt to 3.4.2

- plextraktsync/decorators/retry.py
Fixes https://github.com/Taxel/PlexTraktSync/pull/728
> Import BadResponseException from proper package

- Pipfile
- Pipfile.lock
- plextraktsync/pytrakt_extensions.py
- plextraktsync/trakt_api.py
- requirements.txt
requires:
- https://github.com/moogar0880/PyTrakt/pull/169
> Refactor: Use User.get_liked_lists() from pytrakt package

- Pipfile
- Pipfile.lock
- plextraktsync/decorators/retry.py
- requirements.txt
Update to use package from PyPI:
- https://pypi.org/project/pytrakt/
Because the source version still ended up with an error:
- https://github.com/s0undt3ch/setuptools-declarative-requirements/issues/8#issuecomment-1288145464
> Update to pytrakt 3.4.5

- README.md
- setup.cfg
- https://docs.python.org/3.11/whatsnew/3.11.html
**Release**: 3.11.0
**Date**: October 25, 2022
> Feature: Add Python 3.11 as supported version

- plextraktsync/commands/watch.py
- plextraktsync/media.py
- plextraktsync/walker.py
Bring back `media.show` property mistakenly removed in 1eaf574
Needed for shows ratings sync
fixes #1151
> Bring back media.show property mistakenly removed in 1eaf574

- .github/ISSUE_TEMPLATE/bug.yml
- plextraktsync/commands/info.py
This should help users sharing their config.
> Feature: Add config field to bug report form

- plextraktsync/media.py
- plextraktsync/plex_api.py
- plextraktsync/sync.py
- plextraktsync/trakt_api.py
- plextraktsync/util/local_url.py
Extract random unrelated changes from https://github.com/Taxel/PlexTraktSync/pull/1163
> Small refactorings

- plextraktsync/cli.py
- plextraktsync/commands/inspect.py
- plextraktsync/commands/watched_shows.py
Doesn't really belong with inspect command, and makes the command more visible (from --help)
> Refactor: Move watched_shows logic to own command

- plextraktsync/media.py
- plextraktsync/trakt_api.py
- tests/test_trakt_progress.py
Unused after 7dea3ae84fe758daeeb39f96d38b8f560786e7c1 commit.
Refs:
- https://github.com/Taxel/PlexTraktSync/pull/939
> Cleanup Media.collected property

- plextraktsync/plex_api.py
- plextraktsync/sync.py
- plextraktsync/trakt_list_util.py
Improve https://github.com/Taxel/PlexTraktSync/pull/1183
1. skip updating playlist if it's already the same
2. print if playlist was updated/not updated
> Feature: Optimize updating playlists

- plextraktsync/plex_api.py
- plextraktsync/sync.py
- plextraktsync/trakt_list_util.py
Now Playlists created in Plex will have same description as in Trakt
> Feature: Add support for description for update_playlist

- plextraktsync/trakt_api.py
- https://docs.python.org/3/library/collections.html#collections.defaultdict
Just a shorter code given that there's a class that does what is needed.
> Refactor: Use defaultdict(list) in TraktBatch items

- plextraktsync/commands/plex_login.py
Extracted from https://github.com/Taxel/PlexTraktSync/pull/1087 to make it's diff less complex
> Refactor: Add variables for plex_owner_token, plex_owner_token

- plextraktsync/plex_api.py
Forgotten out of https://github.com/Taxel/PlexTraktSync/pull/1195
> Fix: Account for playlist description update as list was updated

- plextraktsync/commands/cache.py
Suggestion from the requests-cache author:
- https://github.com/requests-cache/requests-cache/issues/711#issuecomment-1292628245
> Use session.cache.responses.values method in cache command

- plextraktsync/sync.py
- plextraktsync/walker.py
Fixes: https://github.com/Taxel/PlexTraktSync/issues/298
> Feature: Disable lists/watchlist sync for partial walk

- plextraktsync/commands/plex_login.py
- plextraktsync/factory.py
Fix https://github.com/Taxel/PlexTraktSync/discussions/1241#discussioncomment-4283101
> Fix has_plex_token check

- README.md
- docker-compose.yml
> docker-compose version 2

- plextraktsync/trakt_api.py
- bypass ep search if show is unknown
- warn about seasons ordering only if episode is found by id
> Fix trakt episode searching

- .dockerignore
- plextraktsync/commands/plex_login.py
- plextraktsync/config/Config.py
- plextraktsync/factory.py
- plextraktsync/mixin/ChangeNotifier.py
- setup.cfg
Fixes problem that on initial login "default" is attempted to connect rather user chosen server:
- https://github.com/Taxel/PlexTraktSync/pull/1248#issuecomment-1333743366
> Fix wrong server on initial login

- plextraktsync/cli.py
- plextraktsync/commands/self_update.py
- plextraktsync/factory.py
This removes dependency of loading self-update command on each run.
> Refactor: Use enable_self_update from factory

- plextraktsync/factory.py
- plextraktsync/trakt_api.py
- tests/test_batch.py
_Extracted from https://github.com/Taxel/PlexTraktSync/pull/1269_
> Use shared Timer for all TraktBatch timers

- plextraktsync/__main__.py
- plextraktsync/cli.py
- plextraktsync/factory.py
- plextraktsync/sync.py
- plextraktsync/trakt_api.py
- plextraktsync/util/Cleanup.py
- setup.cfg
Adds handler system to invoke callbacks on program exit. abort (ctrl+c) and normal shutdown.
> Add cleanup handler

- plextraktsync/factory.py
The fix upstream is taking too long to merge:
- https://github.com/tqdm/tqdm/pull/1395
Fixes https://github.com/Taxel/PlexTraktSync/issues/1208
> Monkey patch tqdm to fix closing progressbar

- plextraktsync/config/Config.py
- plextraktsync/config/HttpCacheConfig.py
Fixing https://github.com/Taxel/PlexTraktSync/pull/1221
> Fix missing http_cache from config

- CONTRIBUTING.md
Doc for remote url building:
- https://stackoverflow.com/a/46637257
- https://docs.docker.com/engine/reference/commandline/build/#extended-description
> Docs: Add docker build instructions

- plextraktsync/commands/inspect.py
- plextraktsync/commands/watch.py
- plextraktsync/plex/PlexLibraryItem.py
Fixes https://github.com/Taxel/PlexTraktSync/issues/877
> Fix: Skip items from excluded libraries in watch

- entrypoint.sh
Fixes https://github.com/Taxel/PlexTraktSync/issues/1291
> Docker: Allow duplicate uid/gid

- Pipfile
- Pipfile.lock
- plextraktsync/decorators/cached_property.py
- requirements.txt
See https://github.com/pkkid/python-plexapi/pull/1065#issuecomment-1357156762
> Use backports.cached-property dependency

- plextraktsync/plex/PlexApi.py
- plextraktsync/pytrakt_extensions.py
_Extracted from https://github.com/Taxel/PlexTraktSync/pull/1279_
> Add typing to PlexApi.reset_show

- plextraktsync/commands/cache.py
Extracted from https://github.com/Taxel/PlexTraktSync/pull/1279
> Inspect: Pretty print xml

- plextraktsync/trakt_list_util.py
Possible fix for https://github.com/Taxel/PlexTraktSync/issues/1314
> Remove LazyUserList to fix namedtuple creation

- plextraktsync/cli.py
> Don't call factory.config property

- plextraktsync/cli.py
- plextraktsync/commands/config.py
- plextraktsync/config/Config.py
- plextraktsync/config/HttpCacheConfig.py
Extracted bits from https://github.com/Taxel/PlexTraktSync/pull/1312
> Separate --urls-expire-after in config command

- plextraktsync/commands/inspect.py
- plextraktsync/commands/plex_login.py
- plextraktsync/commands/self_update.py
- plextraktsync/commands/subdl.py
- plextraktsync/commands/sync.py
- plextraktsync/commands/trakt_login.py
- plextraktsync/commands/watch.py
- plextraktsync/config/PlexServerConfig.py
- plextraktsync/config/RunConfig.py
- plextraktsync/factory.py
- plextraktsync/logger/filter.py
- plextraktsync/media.py
- plextraktsync/plex/PlexServerConnection.py
- plextraktsync/sync.py
- plextraktsync/trakt/TraktApi.py
- plextraktsync/trakt_list_util.py
- plextraktsync/util/execx.py
- plextraktsync/walker.py
Distinguish code import and types imports.
> Add TYPE_CHECKING to modules

- plextraktsync/sync.py
- plextraktsync/walker.py
Extracted from https://github.com/Taxel/PlexTraktSync/pull/1324, https://github.com/Taxel/PlexTraktSync/pull/1333
Tries to make code more readable. Add comments to code.
When reviewing, please see diff with ignore whitespace:
- https://github.com/Taxel/PlexTraktSync/pull/1334/files?w=1
> Refactor: Simplify watchlist sync code base

- .dockerignore
- plextraktsync/factory.py
- plextraktsync/queue/BackgroundTask.py
- plextraktsync/queue/Queue.py
- plextraktsync/queue/TraktBatchWorker.py
- plextraktsync/trakt/TraktApi.py
- setup.cfg
- tests/test_threading.py
This is to handle submitting batches in background regardless what main Thread is doing.
Refs:
- https://github.com/Taxel/PlexTraktSync/issues/1323
- https://github.com/Taxel/PlexTraktSync/pull/1326
Future todo?
- https://docs.python.org/3/library/logging.handlers.html#logging.handlers.QueueListener
> Feature: Add Queue class Client/Server

- plextraktsync/config/Config.py
Refs:
- https://github.com/Taxel/PlexTraktSync/discussions/1257
In the future could just stop writing the deprecated keys, for now include comment that they are deprecated.
> Write deprecation message to deprecated .env keys

- plextraktsync/plex/PlexLibraryItem.py
_Extracted from https://github.com/Taxel/PlexTraktSync/pull/1338_
Before:
```
<tmdb:620725:Movie:nan:Jexi>
```
After:
```
<tmdb:620725:Movie:5d7770b4fb0d55001f5f70f2:Jexi>
```
> Fix: Update PlexLibraryItem __repr__ to understand online ids

- plextraktsync/commands/inspect.py
- plextraktsync/media.py
- plextraktsync/plex/PlexApi.py
- plextraktsync/plex/PlexLibraryItem.py
- plextraktsync/util/expand_id.py
Try to inspect plex discover items, i.e watchlist:
```
plextraktsync inspect 'https://app.plex.tv/desktop/#!/provider/tv.plex.provider.discover/details?key=%2Flibrary%2Fmetadata%2F61001cede257c1002db883f4'
```
No Plex API support yet:
- https://github.com/pkkid/python-plexapi/issues/1091
> Inspect Plex Discover items

- plextraktsync/commands/cache.py
_Extracted from https://github.com/Taxel/PlexTraktSync/pull/1360_
> Print headers in cache dump command

- plextraktsync/trakt/TraktApi.py
- remove debug for detecting wrong media type
- add debug when more than one match
> TraktApi.search_by_id: remove old debug, add new debug

- plextraktsync/commands/inspect.py
- plextraktsync/media.py
- plextraktsync/plex/PlexApi.py
- plextraktsync/plex/PlexLibraryItem.py
Supports Movies, Shows, Seasons, Episodes of Plex Agent (not Legacy Agent)
> Feature: Print Discover URL in inspect output

- plextraktsync/cli.py
- plextraktsync/commands/download.py
- plextraktsync/commands/subdl.py
- plextraktsync/plex/PlexApi.py
This allows to download whole media for the movie/episode.
```
$ plextraktsync download "plex_web_url"
$ plextraktsync download "media_key"
```
> Rename subdl command to download

- plextraktsync/commands/plex_login.py
Some experiments with InquirerPy and rich. Looks nice.
> Use multline server name selection in plex login

- plextraktsync/cli.py
- plextraktsync/commands/clear_collections.py
Resolves https://github.com/Taxel/PlexTraktSync/issues/930
> Feature: Add collection option to clear_collections

- plextraktsync/util/expand_id.py
```
plextraktsync inspect plex://movie/5d776842e6d55c002040f1cd
```
This will treat as Plex Discover url.
> Feature: Add support for inspecting plex:// guids

- plextraktsync/sync.py
- plextraktsync/trakt/TraktApi.py
https://github.com/Taxel/PlexTraktSync/pull/1363 for episodes
Requires:
- https://github.com/Taxel/PlexTraktSync/pull/1381
Fixes https://github.com/Taxel/PlexTraktSync/issues/374
> Feature: Add sync.plex_to_trakt.clear_collected config (for Episodes)

- plextraktsync/commands/info.py
- plextraktsync/commands/login.py
- plextraktsync/commands/plex_login.py
Continue https://github.com/Taxel/PlexTraktSync/pull/1382 (merged without some unpushed changes).
> Cleanup: Use has_plex_token from factory

- plextraktsync/queue/TraktBatchWorker.py
- plextraktsync/util/remove_empty_values.py
Extracted from https://github.com/Taxel/PlexTraktSync/pull/1384
> Refactor: Extract remove_empty_values from TraktBatchWorker

- plextraktsync/queue/Queue.py
- plextraktsync/queue/TraktMarkWatchedWorker.py
- plextraktsync/trakt/PartialTraktMedia.py
- plextraktsync/trakt/TraktApi.py
- plextraktsync/util/Factory.py
> Refactor: Add queue for mark watched trakt api call

- Pipfile
- Pipfile.lock
- plextraktsync/config.default.yml
- plextraktsync/config/HttpCacheConfig.py
- requirements.txt
1.0 cache headers behavior as more features, so its time to update:
- https://github.com/requests-cache/requests-cache/blob/09df7d15f6d403b0e8412cc914bea226a3abe9ed/docs/user_guide/headers.md#supported-headers
- https://github.com/requests-cache/requests-cache/blob/v0.9.8/docs/user_guide/headers.md#supported-headers
Cache constant `0` meaning change:
- https://github.com/requests-cache/requests-cache/pull/568
Add constant translation:
- https://github.com/requests-cache/requests-cache/commit/7578f704dc6a96226ec392e5ebb2a08ea56ae6c8#commitcomment-97479992
Refs:
- https://github.com/requests-cache/requests-cache/issues/769
- https://github.com/requests-cache/requests-cache/issues/770
> Feature: Update requests-cache to 1.0.0b1

- plextraktsync/queue/TraktMarkWatchedWorker.py
- plextraktsync/trakt/PartialTraktMedia.py
- plextraktsync/trakt/TraktApi.py
Add batching for https://github.com/Taxel/PlexTraktSync/pull/1384
Requires:
- https://github.com/Taxel/PlexTraktSync/pull/1391
- https://github.com/glensc/python-pytrakt/pull/25
Refs:
- https://github.com/Taxel/PlexTraktSync/issues/1323
> Feature: Batch mark as watched requests

- plextraktsync/commands/inspect.py
- https://www.plex.tv/blog/let-the-next-episode-roll/
- https://support.plex.tv/articles/credits-detection/
> Feature: Display markers in inspect

- README.md
- plextraktsync/config.default.yml
- plextraktsync/sync.py
> Fix rating sync logic

- plextraktsync/cli.py
- plextraktsync/commands/download.py
- plextraktsync/commands/inspect.py
- plextraktsync/commands/plex_login.py
- plextraktsync/commands/self_update.py
- plextraktsync/commands/sync.py
- plextraktsync/config/ConfigLoader.py
- plextraktsync/config/PlexServerConfig.py
- plextraktsync/config/RunConfig.py
- plextraktsync/logger/filter.py
- plextraktsync/media.py
- plextraktsync/plex/PlexApi.py
- plextraktsync/plex/PlexGuid.py
- plextraktsync/plex/PlexLibraryItem.py
- plextraktsync/plex/PlexLibrarySection.py
- plextraktsync/plex/PlexServerConnection.py
- plextraktsync/plex/PlexWatchList.py
- plextraktsync/queue/TraktMarkWatchedWorker.py
- plextraktsync/sync.py
- plextraktsync/trakt/ScrobblerCollection.py
- plextraktsync/trakt/TraktApi.py
- plextraktsync/trakt/TraktLookup.py
- plextraktsync/trakt/TraktWatchlist.py
- plextraktsync/trakt/trakt_set.py
- plextraktsync/trakt_list_util.py
- plextraktsync/util/Factory.py
- plextraktsync/util/execx.py
- plextraktsync/walker.py
Apply https://github.com/asottile/pyupgrade, cleanup imports with https://pypi.org/project/autoflake/ and manual `pass` removal. Tested with running python 3.7 full sync.
> Run pyupgrade --py37-plus

- plextraktsync/plex/PlexLibraryItem.py
> PlexLibraryItem: Use api methods from plexapi 4.13.4

- plextraktsync/cli.py
- plextraktsync/util/Factory.py
- https://rich.readthedocs.io/en/latest/logging.html#handle-exceptions
> Enable rich tracebacks in rich logger

- plextraktsync/decorators/measure_time.py
- plextraktsync/plex/PlexApi.py
- plextraktsync/plex/PlexLibrarySection.py
- plextraktsync/walker.py
See https://github.com/Taxel/PlexTraktSync/pull/1447#issuecomment-1487223403
> Feature: Use rich links in print_plan

- plextraktsync/plex/PlexServerConnection.py
Could be a fix for :
- #1426
- #1455
> Add timeout to Plex server connection

- plextraktsync/logging.py
- tests/test_logger.py
Fixes:
- https://github.com/Taxel/PlexTraktSync/pull/1482#issuecomment-1604481336
> Fix logger notices with non-string log messages

- Dockerfile
- https://alpinelinux.org/posts/Alpine-3.18.0-released.html
> Feature: Build docker image with alpine 3.18

- plextraktsync/cli.py
- plextraktsync/trakt/TraktApi.py
Exception in Exception in Exception is too noisy
No Trakt connection -> stop the script with CRITICAL error
> reorganize ClickException in Trakt AuthException

- plextraktsync/mixin/SetWindowTitle.py
- plextraktsync/walker.py
https://rich.readthedocs.io/en/stable/reference/console.html#rich.console.Console.set_window_title
> Feature: Update window title with current section

- plextraktsync/commands/download.py
- plextraktsync/commands/plex_login.py
- plextraktsync/config/PlexServerConfig.py
- plextraktsync/config/ServerConfig.py
- plextraktsync/plex/PlexApi.py
- plextraktsync/plex/PlexId.py
- plextraktsync/plex/PlexIdFactory.py
- plextraktsync/util/Factory.py
- plextraktsync/util/expand_id.py
- tests/test_plex_id.py
This allows downloading by using urls from https://app.plex.tv/desktop/
```
plextraktsync download "https://app.plex.tv/desktop/#!/server/2ac365831928c7ad926484eae3c65e3a88112c54/details?key=/library/metadata/1"
```
> Update download to detect server automatically

- plextraktsync/commands/plex_login.py
- plextraktsync/config/ServerConfigFactory.py
- plextraktsync/util/Factory.py
> Refactor: Rename ServerConfig -> ServerConfigFactory (cleanup)

- .dockerignore
- plextraktsync/config/ServerConfigFactory.py
- plextraktsync/path.py
- plextraktsync/servers.default.yml
- plextraktsync/util/Path.py
- setup.cfg
It has no value in it. contents always overwritten
> Cleanup: Skip loading default servers file

- requirements.pipenv.txt
See:
- https://github.com/dependabot/dependabot-core/issues/7909#issuecomment-1731177868
Refs:
- https://github.com/dependabot/dependabot-core/commit/340683db5cbc55829b23678ea2d3b7abf57204fa
- https://github.com/dependabot/dependabot-core/pull/7922
> Update pipenv==2023.8.28 in requirements.pipenv.txt to match github

- .github/workflows/docker-image.yml
See:
- https://github.com/Taxel/PlexTraktSync/pull/1602#issuecomment-1752634633
> Build docker images for all platforms in PR

- plextraktsync/commands/download.py
- plextraktsync/plex/PlexLibraryItem.py
Update download command to also accept season as argument
> Feature: Allow downloading whole seasons

- plextraktsync/commands/inspect.py
- plextraktsync/commands/plex_login.py
- plextraktsync/config/ServerConfigFactory.py
- plextraktsync/plex/PlexId.py
Makes inspect swtich servers if url is from other server from servers.yml
> Feature: Update inspect to understand server url

- plextraktsync/plex/PlexLibraryItem.py
this will fix download when trying to download specific season only
> Fix _get_episodes to return only episodes for current season

- trakt-api.sh
Accepts `TRAKT_API_KEY`, `TRAKT_AUTHORIZATION` env variables, Reads tokens form `.pytrakt.json`, if needed with `jq`.
> Feature: Add helper script to make trakt api requets

- plextraktsync/commands/inspect.py
Otherwise if trakt match is not found, some plex info is not displayed
> Inspect: Print plex data before trakt data

- requirements.pipenv.txt
- https://github.com/dependabot/dependabot-core/commit/8ab281402be6679aa3c9914d5feecdfd314a7fd3
> Update pipenv==2023.11.15 to match GitHub

- plextraktsync/sync.py
`Rating Aladdin (1992) with 9 on Trakt (was None)`
just like in `imdb_import.py`
> Add 'was' before old rating

- plextraktsync/plex/PlexApi.py
Refs :
- https://github.com/pkkid/python-plexapi/pull/1284
closes #1664
> Use playlist editSummary() instead of deprecated edit()

- plextraktsync/media.py
- plextraktsync/plex/PlexGuid.py
- plextraktsync/plex/PlexLibraryItem.py
> Improve Skipping {guid}: not found on Trakt messages

- plextraktsync/media.py
> Display title of unmatched guid in log

- plextraktsync/config/HttpCacheConfig.py
these seem to be left out from provided config. found them in my local config.
> Add cache entries for trakt search

- plextraktsync/plex/PlexApi.py
- plextraktsync/plex/PlexPlaylist.py
_Extracted from https://github.com/Taxel/PlexTraktSync/pull/1475 to make it's changes smaller_
> Refactor: Extract PlexPlaylist class

- plextraktsync/plex/PlexApi.py
- plextraktsync/watch/WatchStateUpdater.py
his allows more control of what is cached than in PlexApi
> Refactor: Move caching to WatchStateUpdater

- plextraktsync/plex/PlexLibraryItem.py
- plextraktsync/watch/WatchStateUpdater.py
- plextraktsync/watch/events.py
Improve usability for https://github.com/Taxel/PlexTraktSync/issues/942
> Fix: Allow only episodes and movies in watch

- plextraktsync/plex/PlexApi.py
- plextraktsync/util/Factory.py
Allow using server "config" in PlexApi.
> Feature: Add PlexServerConfig support to PlexApi

- plextraktsync/commands/inspect.py
- plextraktsync/plex/PlexLibraryItem.py
Avoid logic in inspect command
> Refactor: Add web_url, discover_url properties to PlexLibraryItem

- .dockerignore
- setup.cfg
Package new modules:
- rich: https://github.com/Taxel/PlexTraktSync/pull/1694
- plan: https://github.com/Taxel/PlexTraktSync/pull/1688
> Fix: Package rich and plan modules

- README.md
- setup.cfg
Improve https://github.com/Taxel/PlexTraktSync/pull/1602
> Fix: Add Python 3.12 as supported

- plextraktsync/plan/Walker.py
- plextraktsync/trakt/TraktItem.py
_Extracted from https://github.com/Taxel/PlexTraktSync/pull/1578_
> Cleanup: Remove un-needed trakt from TraktItem

- plextraktsync/plex/PlexPlaylist.py
Extracted from https://github.com/Taxel/PlexTraktSync/pull/1475
> Fix: Detect and report duplicate playlists

- plextraktsync/decorators/rate_limit.py
- plextraktsync/trakt/ScrobblerProxy.py
> Fix: Add rate_limit to ScrobblerProxy calls

- Dockerfile
Release notes:
- https://alpinelinux.org/posts/Alpine-3.19.0-released.html 2023-12-07
Previous update:
- https://github.com/Taxel/PlexTraktSync/pull/1515
> Feature: Update docker image to alpine3.19

- plextraktsync/media.py
- plextraktsync/plex/PlexPlaylist.py
- plextraktsync/plex/PlexPlaylistCollection.py
- plextraktsync/sync.py
- plextraktsync/trakt/TraktApi.py
- plextraktsync/trakt/TraktUserList.py
- plextraktsync/trakt/TraktUserListCollection.py
- plextraktsync/trakt/types.py
- plextraktsync/util/Factory.py
The intention is to print "Added to list" message only if it's really missing from the list
> Refactor: Playlists refactoring

- plextraktsync/plex/PlexGuid.py
- plextraktsync/plex/PlexLibraryItem.py
- plextraktsync/trakt/TraktUserList.py
- plextraktsync/trakt/TraktUserListCollection.py
reports duplicates with guid matches:
```
WARNING  Duplicate Gone with the Wind (1939) (14257) with Gone with the Wind (1940) 15133                                                     
WARNING  Duplicate Total Recall (1990) (619) with Total Recall (Mind Bending Edition) (1990) 21672                                            
```
Requires:
- https://github.com/Taxel/PlexTraktSync/pull/1475
> Feature: Report duplicate movies when adding items to plex lists

- plextraktsync/media.py
improve messages when inspecting youtube agent item.
- https://github.com/ZeroQI/YouTube-Agent.bundle
> Fix: Fix fatal errors with youtube provider

- plextraktsync/sync.py
- plextraktsync/trakt_list_util.py
To be merged after:
- https://github.com/Taxel/PlexTraktSync/pull/1475
> Cleanup: Remove unused TraktListUtil, TraktList classes

- .dockerignore
- setup.cfg
Fixes https://github.com/Taxel/PlexTraktSync/issues/1755
Fixes https://github.com/Taxel/PlexTraktSync/issues/1756
Refs:
- https://github.com/Taxel/PlexTraktSync/pull/1749
> Fix: Package media module

- plextraktsync/cli.py
Fixes https://github.com/Taxel/PlexTraktSync/issues/1770, https://github.com/Taxel/PlexTraktSync/issues/1752
> Fix: Report missing terminal error more nicely

- README.md
systemd --user is way to run script without root
> Add systemd user instructions for watch

- README.md
- plextraktsync/cli.py
Refs:
- https://stackoverflow.com/questions/61134206/remove-text-from-click-python-module-help-menu/61134439#61134439
> Use metavar=NAME for --server option

- plextraktsync/plex/PlexLibraryItem.py
- plextraktsync/trakt/TraktApi.py
Refs:
- https://github.com/Taxel/PlexTraktSync/issues/1805
> Fix: Add typings for some parameters

- plextraktsync/commands/imdb_import.py
Refs:
- https://github.com/Taxel/PlexTraktSync/issues/1805
> Fix: Skip rating over imdb_import items with same value

- plextraktsync/media/Media.py
- plextraktsync/plex/PlexApi.py
- plextraktsync/plex/PlexLibraryItem.py
Requires:
- https://github.com/Taxel/PlexTraktSync/pull/1817 (rebase)
Extracted from:
- https://github.com/Taxel/PlexTraktSync/pull/1821
Refs:
- https://github.com/Taxel/PlexTraktSync/issues/1805
> Add types and some optimizations

- plextraktsync/plex/PlexApi.py
Usage removed in 1a1975a7566ee4477dfbcc8b46c38a4492f1bd03
> Cleanup: Remove unused update_playlist from PlexApi

- plextraktsync/util/Rating.py
Fixes https://github.com/Taxel/PlexTraktSync/issues/1852
> Allow rated_at be null when formatting

- plextraktsync/plex/PlexIdFactory.py
- plextraktsync/sync/Sync.py
> Update provider/tv.plex.provider.vod to match PlexId.METADATA

- plextraktsync/sync/LikedListsPlugin.py
- plextraktsync/sync/Sync.py
Plugin may have dangerous outcome if purpose is filled incorrectly.
> Fix: Remove dry_run being mixed in is_partial

- Dockerfile
> Build missing wheels only if needed (0.26.x)

- plextraktsync/rich/RichProgressBar.py
> Feature: Add async iterator support to RichProgressBar

- plextraktsync/sync/TraktListsPlugin.py
- plextraktsync/trakt/TraktUserListCollection.py
Makes more sense to have action in Plugin rather Collection class
> Refactor: Move sync method from TraktUserListCollection to TraktListsPlugin

- plextraktsync/sync/TraktListsPlugin.py
Remove warning:
- https://github.com/Taxel/PlexTraktSync/issues/1932
> Fix: Update TraktListsPlugin run conditions

- plextraktsync/watch/WatchStateUpdater.py
Maybe help https://github.com/Taxel/PlexTraktSync/issues/1934
> Add watch debug of username filter

- plextraktsync/sync/WatchListPlugin.py
Fixes https://github.com/Taxel/PlexTraktSync/issues/1940
> Add missing hookimpl for PlexWatchListPlugin

- plextraktsync/sync/LikedListsPlugin.py
- plextraktsync/sync/WatchListPlugin.py
More like cosmetics to make readable and move logic to appropriate plugin.
> Refactor: Minor logic changes in LikedListsPlugin, WatchListPlugin

- plextraktsync/sync/Sync.py
- tests/test_plugin.py
Add dumb test so that breaking change from https://github.com/Taxel/PlexTraktSync/pull/1939 would be detected
> Test: Add test_sync test

- plextraktsync/plan/Walker.py
- plextraktsync/sync/WatchListPlugin.py
Fixes after https://github.com/Taxel/PlexTraktSync/pull/563
> Fix walker methods being async in WatchListPlugin

- .pre-commit-config.yaml
Refs:
- https://astral.sh/
- https://github.com/astral-sh/ruff-pre-commit
- https://github.com/astral-sh/ruff
- https://github.com/astral-sh/ruff/issues/11380
Other
- https://github.com/pypa/pip/blob/36a61d0e3b7e99cbac83d527c670f348db218859/.pre-commit-config.yaml#L24
- https://github.com/pypa/pip/blob/36a61d0e3b7e99cbac83d527c670f348db218859/pyproject.toml#L153
> Setup ruff (from astral-sh) pre-commit hook

- plextraktsync/commands/unmatched.py
Fixes: https://github.com/Taxel/PlexTraktSync/issues/1949
> Fix: unmatched command async code calls

- plextraktsync/plan/Walker.py
Fixes https://github.com/Taxel/PlexTraktSync/issues/1949
> Fix: No progressbar launches sync code

- plextraktsync/config/SyncConfig.py
Fixes https://github.com/Taxel/PlexTraktSync/issues/1986
> Add liked_list default value for missing config

- README.md
Fixed the Unraid script instructions to start the sync.
> Update README.md - Fixed Unraid script command

- plextraktsync/plex/PlexGuid.py
- plextraktsync/trakt/TraktApi.py
- plextraktsync/trakt/TraktItem.py
when movie is not matched, a search with same id for show is attempted. also test that the title matches when this warning is printed.
> Fix: Improve movie as show search correctness

- plextraktsync/commands/inspect.py
- plextraktsync/plex/PlexLibraryItem.py
Required change now:
- https://github.com/pkkid/python-plexapi/pull/1451
Refs:
- https://github.com/Taxel/PlexTraktSync/pull/2024
> Fix: Reload files before inspect files

- .pre-commit-config.yaml
Integrate:
- https://pypi.org/project/validate-pyproject/
NOTE: there's bug in upstream doc:
- https://github.com/abravalheri/validate-pyproject/pull/195#issuecomment-2323272867
> Build: Setup validate-pyproject pre commit hook

- .github/workflows/automerge.yml
- .github/workflows/ci.yml
- .github/workflows/docker-image.yml
- .github/workflows/test.yml
Taken from eventum repo:
- https://github.com/eventum/eventum/blob/62dd272fe61cb9d2cdc2a6fb3c597d86418b0580/.github/workflows/ci.yml
Docs:
- https://github.com/fastify/github-action-merge-dependabot
> Build: Add automerge job workflow

- README.md
Added exit to the container already running user script.
> Update unraid user script

- plextraktsync/util/Rating.py
```
INFO     Rating Hevimpi reissu (2024) with Rating(rating=7, rated_at='2024-12-28T19:15:25.000Z', title=Good) on Trakt (was None)
```
> Feature: Show rating titles from trakt

- plextraktsync/plex/PlexGuidProvider.py
- plextraktsync/plex/PlexGuidProviderYoutube.py
```
Inspecting <PlexId:*redacted*:*redacted*>: <youtube:youtube|fPk1R1cTkzM|YouTube:Movie:*redacted*:Cheburashka-e-Kosyak>
--- Plex
Plex Web URL: https://app.plex.tv/desktop/#!/server/*redacted*/details?key=/library/metadata/*redacted*
Title: Cheburashka e Kosyak
Media.Duration: 00:02:36
Media.Type: 'movie'
Media.Guid: 'com.plexapp.agents.youtube://youtube|fPk1R1cTkzM|YouTube?lang=xn'
Audio: 'stereo', 'Unknown (AAC Stereo)'
Video: 'vp9'
Subtitles:
Parts:
Part 1 (exists: True): /*redacted*/Cheburashka e Kosyak [fPk1R1cTkzM].mp4 5.4 MiB
Markers:
Guids:
Guid: youtube:movie:fPk1R1cTkzM, Id: youtube|fPk1R1cTkzM|YouTube, Provider: 'youtube'
Metadata: {'collected_at': '2024-12-30T18:17:01.000Z', 'media_type': 'digital', 'resolution': 'sd_480p', 'audio': 'aac', 'audio_channels': 
'2.0'}
Played on …
```
> Feature: Add PlexGuidProviderYoutube provider

- plextraktsync/plex/guid/provider/Abstract.py
- plextraktsync/plex/guid/provider/IMDB.py
- plextraktsync/plex/guid/provider/Local.py
- plextraktsync/plex/guid/provider/Mbid.py
- plextraktsync/plex/guid/provider/TMDB.py
- plextraktsync/plex/guid/provider/TVDB.py
- plextraktsync/plex/guid/provider/Youtube.py
Refs
- https://github.com/Taxel/PlexTraktSync/pull/2121
> Refactor: Move common provider to abstract class

- plextraktsync/plex/guid/provider/TMDB.py
Refactor https://github.com/Taxel/PlexTraktSync/pull/2134
> Refactor tmdb provider similar code

- plextraktsync/plex/PlexLibraryItem.py
Some refactoring when browsing old code.
> Refactor: Reuse code in PlexLibraryItem

- plextraktsync/commands/plex_login.py
- plextraktsync/config/HttpCacheConfig.py
Requires:
- https://github.com/Taxel/PlexTraktSync/pull/1870
> Feature: Cache MyPlexAccount responses

- Dockerfile
Release notes:
- https://alpinelinux.org/posts/Alpine-3.20.0-released.html 2024-05-22
Previous update:
- https://github.com/Taxel/PlexTraktSync/pull/1712
> Chore: Update base image to alpine 3.20
