Taxel/PlexTraktSync

get_env_data.py, main.py
Setup could be more user-friendly, here is what I did :
- .pytrakt.json is moved from home folder to project folder (with .env and config.json) so that all config files are together. Easier for maintenance or migration.
- if main.py runs for the first time, get_env_data.py is called.
- get_env_data.py writes PLEX_TOKEN and TRAKT_USERNAME in .env file, no need to manually copy/paste.
Also, why do you have `trakt.APPLICATION_ID = '65370'` line ?
It is only needed for pin auth method but you choose oauth method.
By the way, PIN authentication would be easier for such a basic script. Note that it is default pytrakt method.
=> improve configuration

main.py
#11 pull-request was sync movie last view date correction.
Here is the same for tv episode.
Fixes #19 issue.
=> Sync episode last viewed date from Plex to Trakt & timezone fix

main.py, pytrakt_extensions.py
Some movies or tv episodes had a new watched status added over and over at each sync.
This bug was linked to 3 problems solved here :
- using trakt id instead of slug for watched sync (slug title is not reliable to identify a content)
- fetching specials episodes status
- fetching watched episodes even if no air date
closes #10
closes #29
=> Fix multiple watched bug

config.py
If user runs script from outside its folder, full path is needed to open file.
closes #16 
Maybe needed for last_update.log too #17
=> full path for file opening

get_env_data.py
[Device authentication](https://trakt.docs.apiary.io/#reference/authentication-devices) is easier to setup for users with command line scripts.
Users don't have to copy/paste a long url but only a code.
Moreover, the pytrakt function of device_auth stores the `oauth_refresh` token which can be used to automatically refresh the `oauth_token` every 3 months.
=> Switch to device auth

main.py
PR to bypass utc timezone conversion for python version <3.6 because of :
`ValueError: astimezone() cannot be applied to a naive datetime`
From python version 3.6 this is not an issue anymore :
> in version 3.6: The astimezone() method can now be called on naive instances that are presumed to represent system local time
closes #34
=> no utc tz for python < 3.6

README.md, config.json, main.py
User can customize the "excluded-libraries" list in `config.json` to set Plex section names that will not be sync.
closes #22
=> Add excluded libraries

README.md, config.json, get_env_data.py, main.py
Plex base url is now found at first run and automatically stored in `.env` file.
The user doesn't need to edit it in config file anymore.
It also allows the use of a Plex shared librarie (remote Plex librarie shared by a friend).
closes #27
=> Store Plex base url automatically in the .env file on first run

main.py, trakt_list_util.py
This makes the script respect the Trakt playlists order (items rank is preserved) when syncing them to Plex.
fixes #54
=> keep trakt rank when sync playlists to plex

main.py
This allows to bypass a movie or a show when Trakt gives a bad response or no response, instead of crashing the whole sync.
fixes #66
=> Catch trakt bad response

main.py, pytrakt_extensions.py
Some Trakt API response have changed recently :
There is a new keyword `title` for TV show seasons. Trakt now returns the title for each season.
This PR adds keyword `title` to `SeasonProgress()` and therefore fixes the `bad response from trakt` error for entire TV Library that showed up recently.
And use of trakt id instead of slug just like in PR #31
closes #71
=> Add new keyword 'title' for TV show seasons

main.py, trakt_list_util.py
Before that, when syncing a list from Trakt to Plex playlist, only movies were read.
With this PR, TV episodes are sync too.
Shows and seasons remain not synced because Plex accepts only episodes and movies in its playlists.
fixes #28 
fixes #74
=> Add tv episodes to playlist sync trakt->plex

.gitignore, Pipfile, Pipfile.lock, main.py, requirements.txt
Hey guys,
after finally getting to installing this script in my home, I was immediately annoyed by the fact that the new plex movie agent does not work so far.
So I went ahead and included the tar.gz of the [pull request in python-plexapi that fixes the issue](https://github.com/pkkid/python-plexapi/pull/562) and some minor modifications that use the new `movie.guids` property if the new Plex movie agent is used.
It works fine on my machine, if someone who still has a library with the old movie agent can confirm I didn't break anything there, we can merge this.
This fixes #56 and makes #83 unnecessary because it turns out the newer plexapi actually gives back the imdb and/or tvdb links in the new property, no more "search by name and year and hope it's the right match" necessary.
Once the …
=> Plexmovieagent fixed

.gitignore
Extracted out of https://github.com/Taxel/PlexTraktSync/pull/87 so the change could be merged sooner.
cc @Taxel
=> Ignore .pytrakt.json to avoid accidentially commiting credentials

trakt_list_util.py
Bypass a liked list which has become unavailable due to owner's profile becoming private. This situation raises OAuthException.
Description by user :
> Some time ago I "liked" a playlist but now the owner's profile is private and I can't see it anymore until I follow him.
fixes #92
=> except OAuthException for unavailable liked list

get_env_data.py, main.py
This PR makes connection attempts to Plex more resilient.
It makes the script try different url for connections attempts to Plex until success :
1. if SSL certificate mismatch, it tries the expected url and if success it updates the url in .env file (*)
2. if SSL error, it tries the unsecured way (without SSL)
3. if connection still fails, it tries to basically connect to localhost (url added in .env as "fallbackurl" and customisable)
(*) : Plex server sometime updates its ID. Therefore the connection url change too (the `server_id_hash` part here) :
`https://dashed_ip_address.server_id_hash.plex.direct:port`
The SSL certificate provided by Plex server is for *.server_id_hash.plex.direct and must match the connection url. 
If someone finds a better way to implement the 3 try/except I …
=> Improve connection to Plex server

clear_trakt_collections.py
The config_path to .pytrakt.json for trakt credentials needs to be set before the `import trakt.users` command.
closes #103
=> Set trakt config_path before import trakt.users

Pipfile, Pipfile.lock, requirements.txt
The project has no changelog for migration:
- https://github.com/pkkid/python-plexapi/issues/521
So it would be trial and error to resolve what's broken.
Whole diff:
- https://github.com/pkkid/python-plexapi/compare/3.2.0...4.3.1
Release notes by versions in the range:
- https://github.com/pkkid/python-plexapi/releases/tag/3.4.0 (no notes)
- https://github.com/pkkid/python-plexapi/releases/tag/3.5.0 (no notes)
- https://github.com/pkkid/python-plexapi/releases/tag/3.5.1 (no notes)
- https://github.com/pkkid/python-plexapi/releases/tag/3.6.0 (no notes)
- https://github.com/pkkid/python-plexapi/releases/tag/4.0.0 (no notes)
- https://github.com/pkkid/python-plexapi/releases/tag/4.1.0 (no notes)
- https://github.com/pkkid/python-plexapi/releases/tag/4.1.1 (no notes)
- …
=> Update PlexAPI from 3.2.0 to 4.3.1

main.py
Hey guys,
after finally getting to installing this script in my home, I was immediately annoyed by the fact that the new plex movie agent does not work so far.
So I went ahead and included the tar.gz of the [pull request in python-plexapi that fixes the issue](https://github.com/pkkid/python-plexapi/pull/562) and some minor modifications that use the new `movie.guids` property if the new Plex movie agent is used.
It works fine on my machine, if someone who still has a library with the old movie agent can confirm I didn't break anything there, we can merge this.
This fixes #56 and makes #83 unnecessary because it turns out the newer plexapi actually gives back the imdb and/or tvdb links in the new property, no more "search by name and year and hope it's the right match" necessary.
Once the …
=> Update to use guids from python-plexapi to fix Plexmovieagent breakage

plex_trakt_sync/config.py, plex_trakt_sync/main.py
This consolidates access to "config" type items to one `CONFIG` symbol. Makes it possible to add new config keys without much duplication. Also, the initialization is delayed so "first install" dialogs are invoked when config is accessed, not when module is loaded. In the future could add data key specific validation or defaults. And overloading config keys from environment.
NOTE:
=> Update config module to lazy initialize and include environment variables

plex_trakt_sync/decorators.py, plex_trakt_sync/main.py, plex_trakt_sync/memoize.py, plex_trakt_sync/nocache.py, plex_trakt_sync/plex_api.py
_Extracted from https://github.com/Taxel/PlexTraktSync/pull/122_
The purpose of the API class is to make API access fluent, without having to dea with cache_disabled wrapping or thinking if method calls should be cached.
This class makes heavy use of decorators to simplify the code itself.
=> Feature: Add PlexApi class for dealing with Plex Api fetching and caching

clear_trakt_collections.py, plex_trakt_sync/cli.py
To run the clear collections, you now have to pass `--confirm` option:
```
➔ ./main.py clear-collections
You need to pass --confirm option to proceed
```
=> Add clear_trakt_collections as subcommand

plex_trakt_sync/decorators.py
Inspired from https://stackoverflow.com/a/62956469/2314626
```py
with measure_time("Completed full sync"):
sync()
```
=> Add measure_time helper to log block timing

plex_trakt_sync/main.py
Should not directly write to .env file.
Followup to https://github.com/Taxel/PlexTraktSync/pull/139
=> Update to use config save() method in get_plex_server

plex_trakt_sync/cli.py, plex_trakt_sync/commands/sync.py, plex_trakt_sync/main.py, plex_trakt_sync/plex_api.py, plex_trakt_sync/trakt_api.py
This also makes the main sync loop look cleaner as specific logic is extracted to API class.
=> Add TraktApi class dealing with caching/fetching trakt api methods

plex_trakt_sync/decorators/__init__.py, plex_trakt_sync/decorators/rate_limit.py, plex_trakt_sync/trakt_api.py
Methods with such decorators are retried if `RateLimitException` exception is thrown.
```python
@rate_limit()
def watched_shows(self):
return pytrakt_extensions.allwatched()
```
The whole method is retried, so don't put there anything you don't want to be retried.
there's also side effect, if method calls another method getting the exception. like:
```python
@rate_limit()
def movie_ratings(self):
return self.me.get_ratings(media_type='movies')
```
the decorator will retry `me` 5 times, and then for each `movie_ratings` 5 retries another 5 times of `me`.
```
/usr/local/bin/python3 /Users/glen/scm/plex/Plugins/PlexTraktSync/test_pytest_trakt_search.py
WARNING: RateLimitException for <function TraktApi.me at 0x10b0dfe50>, retrying after 1 seconds (try: 1/5)
WARNING: RateLimitException for …
```
=> Add rate_limit decorator

plex_trakt_sync/decorators/rate_limit.py, plex_trakt_sync/trakt_api.py
To rate limit requests without hitting rate limit error, decorate the method like:
```python
@rate_limit(delay=1.2)
def me(self):
try:
return trakt.users.User('me')
```
All methods share the same pool for rate limits.
Currently, all methods in TraktApi all `GET` method based, so for test only `.me` method is rate limited
refs:
- https://trakt.docs.apiary.io/#introduction/rate-limiting
- https://github.com/Taxel/PlexTraktSync/pull/119
=> Add rate limit delay support

plex_trakt_sync/decorators/__init__.py, plex_trakt_sync/decorators/nocache.py
Extracted from https://github.com/Taxel/PlexTraktSync/pull/180
otherwise methods being decorated with `@nocache` got their arguments shifted around.
```python
@nocache
def rate(self, m, rating):
m.rate(rating)
```
this was called with two arguments only: `m, rating`.
=> Rewrite nocache as function to support decorators on class method arguments

plex_trakt_sync/cli.py, plex_trakt_sync/commands/watch.py, plex_trakt_sync/listener.py
This adds `watch` subcommand to print play events from PMS:
```
➔ ./plex_trakt_sync.sh watch
Listening for events!
INFO: Starting AlertListener: ws://localhost:32400/:/websockets/notifications?X-Plex-Token=<hidden>
{'type': 'playing', 'size': 1, 'PlaySessionStateNotification': [{'sessionKey': '19', 'guid': '', 'ratingKey': '9723', 'url': '', 'key': '/library/metadata/9723', 'viewOffset': 39000, 'playQueueItemID': 17659, 'state': 'playing', 'transcodeSession': '9dd9jn2ci6cx3fynei05gs6p'}]}
{'type': 'playing', 'size': 1, 'PlaySessionStateNotification': [{'sessionKey': '19', 'guid': '', 'ratingKey': '9723', 'url': '', 'key': '/library/metadata/9723', 'viewOffset': 41000, 'playQueueItemID': 17659, 'state': 'stopped', 'transcodeSession': '9dd9jn2ci6cx3fynei05gs6p'}]}
```
nothing intermediately …
=> Add watch subcommand to print play events from PMS

README.md, plex_trakt_sync/commands/sync.py
The sync subcommand supports `--sync=tv` and `--sync=movies` options,
so you can sync only specific library types.
```
Usage: main.py sync [OPTIONS]
Perform sync between Plex and Trakt
Options:
--sync [all|movies|tv]  Specify what to sync  [default: all]
--help                  Show this message and exit.
```
refs:
- https://github.com/Taxel/PlexTraktSync/discussions/190
=> Add --sync={all|tv|movies} option

plex_trakt_sync/commands/watch.py, plex_trakt_sync/listener.py, plex_trakt_sync/plex_api.py, plex_trakt_sync/trakt_api.py
Builds on top of https://github.com/Taxel/PlexTraktSync/pull/148
This is mostly proof of concept (but it works!), therefore no readme update.
There's plenty of to optimize:
- skip events, in case laptop suspend/resume there's tons of messages from websocket that should be skipped
- code refactoring, isolate logic to own classes/methods/functions
- optimize on cpu, needs investigating what first
- the code is synchronous, maybe need to rewrite asynchronous
- the sleep(1) maybe is putting too much pressure on cpu
- scrobblng probably needs to emitted only on start/pause/stop, as trakt can itself continue counting play time
- optimize for reducing requests to trakt
- ... that's already a bunch!
NOTE: The Trakt app may need `scrobble` permission:
- …
=> Add scrobbling support to watch command

plex_trakt_sync/commands/clear_collections.py, plex_trakt_sync/commands/sync.py, plex_trakt_sync/decorators/measure_time.py, plex_trakt_sync/decorators/rate_limit.py, plex_trakt_sync/logging.py, plex_trakt_sync/main.py, plex_trakt_sync/plex_server.py, plex_trakt_sync/trakt_api.py, plex_trakt_sync/trakt_list_util.py
```
2021-04-06 20:27:10,368 DEBUG[trakt.core]:method, url :: get, https://api-v2launch.trakt.tv/shows/1/seasons?extended=episodes
2021-04-06 20:27:10,371 DEBUG[urllib3.connectionpool]:Starting new HTTPS connection (1): api-v2launch.trakt.tv:443
2021-04-06 20:27:10,497 DEBUG[urllib3.connectionpool]:https://api-v2launch.trakt.tv:443 "GET /shows/1/seasons?extended=episodes HTTP/1.1" 200 None
2021-04-06 20:27:10,506 DEBUG[trakt.core]:RESPONSE [get] (https://api-v2launch.trakt.tv/shows/1/seasons?extended=episodes): <Response [200]>
2021-04-06 20:27:11,392 INFO[PlexTraktSync]:Completed full sync in 53.3 seconds
```
This affects only file logger, stdout logger is not affected
=> Include logger name to log messages

plex_trakt_sync/decorators/memoize.py
Revert "Use lru_cache directly for py<3.8"
This reverts commit 86d3923e81b029b7380ed2ac5307ba75f56a466d.
=> Fix py 3.7 compatibility

plex_trakt_sync/decorators/rate_limit.py
The `last_time` was not updated, therefore the evasive `sleep()` calls to avoid the rate limit being hit, did not work.
=> Update last_time when rate limiting POST requests

plex_trakt_sync/commands/sync.py, plex_trakt_sync/plex_api.py, plex_trakt_sync/trakt_api.py
When started to look at https://github.com/Taxel/PlexTraktSync/issues/117, I noticed the `collected_at` was not filled at all. This uses `addedAt` value from Plex when adding items to "Collection" in Trakt.
This adds `collected_at` to movies only (not tv episodes)
refs:
- https://trakt.docs.apiary.io/#reference/sync/add-to-collection/add-items-to-collection
=> Fill collected_at for from Plex library

plex_trakt_sync/listener.py
```
$ ./plex_trakt_sync.sh watch
Listening for events!
INFO: Starting AlertListener: ws://localhost:32400/:/websockets/notifications?X-Plex-Token=<hidden>
ERROR: AlertListener Error: Connection is already closed.
INFO: Starting AlertListener: ws://localhost:32400/:/websockets/notifications?X-Plex-Token=<hidden>
ERROR: AlertListener Error: Connection is already closed.
INFO: Starting AlertListener: ws://localhost:32400/:/websockets/notifications?X-Plex-Token=<hidden>
ERROR: AlertListener Error: Connection is already closed.
INFO: Starting AlertListener: ws://localhost:32400/:/websockets/notifications?X-Plex-Token=<hidden>
ERROR: AlertListener Error: Connection is already closed.
INFO: Starting AlertListener: ws://localhost:32400/:/websockets/notifications?X-Plex-Token=<hidden>
ERROR: …
```
=> Restart websocket if connection was closed

plex_trakt_sync/plex_api.py
This allows better mocking of the item not relying on specific class
_Extracted from https://github.com/Taxel/PlexTraktSync/pull/215_
=> Use property type to check media type

plex_trakt_sync/plex_api.py, plex_trakt_sync/trakt_api.py, tests/__init__.py, tests/test_new_agent.py
Fixes error reported here:
- https://github.com/Taxel/PlexTraktSync/issues/220#issuecomment-817190974
```
File "/Users/bink/scripts/PlexTraktSyncTV/plex_trakt_sync/decorators/rate_limit.py", line 43, in wrapper
return fn(*args, **kwargs)
File "/Users/bink/scripts/PlexTraktSyncTV/plex_trakt_sync/trakt_api.py", line 195, in find_movie
raise ValueError(f"Invalid id_type: {media.provider}") from e
ValueError: Invalid id_type: plex
```
=> Fix tv episodes matching for new tv agent

plex_trakt_sync/commands/sync.py, plex_trakt_sync/plex_api.py
Catch an error from `NotFound` item from Plex:
- https://github.com/Taxel/PlexTraktSync/issues/220#issue-855138799
=> Add error catching of NotFound plex items

tests/test_tv_lookup.py
This tests that `Mapleworth Murders (2020) S01E02` can be retrieved.
To run the test:
```
pytest tests/test_tv_lookup.py
```
refs:
- https://github.com/Taxel/PlexTraktSync/discussions/208#discussioncomment-594277
=> Add test for episode lookup

plex_trakt_sync/trakt_api.py
This uses plex date (rather current date) when adding episodes to trakt collection.
Similar change for movies: #211
=> Use Plex collected_at for Episodes

plex_trakt_sync/commands/sync.py, plex_trakt_sync/trakt_api.py
This reduces API calls made to Trakt API to add items to collection to 1 (or 0).
This also reports summary of changes made:
```
INFO: Updated Trakt collection: {'added': {'episodes': 15}}
INFO: Completed full sync in 45.0 seconds
```
this saved 14 POST calls to Trakt, possibly reducing run time of 13 seconds.
=> Group API calls to add items to Trakt collection

plex_trakt_sync/style.py
This allows to use styles like "error", "success" so they be colored identically, and in the future can change style by changing style, not code:
```py
import plex_trakt_sync.style
PROMPT_TRAKT_CLIENT_SECRET = style.prompt("Please enter your client secret")
TRAKT_LOGIN_SUCCESS = style.success(
"You are now logged into Trakt. "
"Your Trakt credentials have been added in .env and .pytrakt.json files."
)
```
=> Add semantic styles helpers

plex_trakt_sync/commands/sync.py
```
Usage:
./plex_trakt_sync.sh sync --show='The Addams Family (1964)'
```
requires:
=> Add --show option to sync, to sync only specific show

plex_trakt_sync/cli.py, plex_trakt_sync/commands/plex_login.py, plex_trakt_sync/style.py
```
➔ ./plex_trakt_sync.sh plex-login --help
Usage: main.py plex-login [OPTIONS]
Log in to Plex Account
Options:
--username TEXT  Plex login
--password TEXT  Plex password
--help           Show this message and exit.
```
the command line options are optional, they are asked interactively.
Similarly to https://github.com/Taxel/PlexTraktSync/pull/243
=> Add command to log in to Plex

plex_trakt_sync/plex_api.py, plex_trakt_sync/trakt_api.py, tests/test_tv_lookup.py
This allows watch command to scrobble tv episodes by legacy agent, i.e `com.plexapp.agents.thetvdb://77137/1/1?lang=en` guid.
=> Update find_by_media to support legacy episode format

config.default.json, plex_trakt_sync/config.py, plex_trakt_sync/logging.py
This solves a problem that different runs overwrite logs that user is having.
```json
"logging": {
"append": true
},
```
Fixes https://github.com/Taxel/PlexTraktSync/issues/231
=> Add support to disable log truncation on each run

plex_trakt_sync/commands/sync.py, plex_trakt_sync/trakt_api.py, tests/conftest.py, tests/mock_data/trakt_sync_collection_request.json, tests/mock_data/trakt_sync_collection_response.json, tests/test_batch.py
```
Usage: main.py sync [OPTIONS]
Perform sync between Plex and Trakt
Options:
--show TEXT             Sync specific show only
--sync [all|movies|tv]  Specify what to sync  [default: all]
--batch-size INTEGER    Batch size for collection submit queue  [default: 1]
--help                  Show this message and exit.
```
refs:
- https://github.com/Taxel/PlexTraktSync/pull/232#issuecomment-821866092
- https://github.com/Taxel/PlexTraktSync/issues/256#issuecomment-821851004
=> Add --batch-size option for TraktBatch

plex_trakt_sync/decorators/rate_limit.py
This is quick fix for https://github.com/Taxel/PlexTraktSync/issues/257
Similarly to #248, just add another exception to the catch.
refs:
- https://github.com/Taxel/PlexTraktSync/issues/260
=> Catch TraktException in rate limit to retry after 1s

Pipfile, Pipfile.lock, plex_trakt_sync/commands/sync.py, plex_trakt_sync/version.py, requirements.txt, tests/test_version.py
Prints version info from git, if available:
```
INFO: PlexTraktSync [2ad99c15: Add primitive version test @2021-04-18 09:27:16]
```
This adds new module, but it's import error is ignored if user have not updated dependencies.
=> Print git version info if available

plex_trakt_sync/commands/sync.py, plex_trakt_sync/trakt_api.py, tests/test_tv_lookup.py
Replaces https://github.com/Taxel/PlexTraktSync/pull/240, which proven to be too slow to fetch from trakt for each episode.
So this PR uses fetch for episode only if previous bulk fetch failed.
Problem solution to the discussions at:
- https://github.com/Taxel/PlexTraktSync/discussions/208
- https://github.com/Taxel/PlexTraktSync/pull/240
=> Fallback to single episode search for found form Trakt errors

plex_trakt_sync/version.py
Workaround for library internal errors: https://github.com/spapas/python-git-info/issues/7
refs:
- https://github.com/Taxel/PlexTraktSync/pull/261
=> Skip git version info on TypeError

plex_trakt_sync/config.py, plex_trakt_sync/decorators/__init__.py, plex_trakt_sync/decorators/rate_limit.py, plex_trakt_sync/decorators/time_limit.py, plex_trakt_sync/timer.py, plex_trakt_sync/trakt_api.py, tests/test_timer.py
NOTE: `time.monotonic` requires Python 3.5 to be available on all Platforms:
- https://docs.python.org/3/library/time.html#time.monotonic
=> Refactor: Add Timer class, separate rate_limit and time_limit decorators

plex_trakt_sync/commands/sync.py
For logs to be gramatically correct and be clear about what is done and what is still in progress, this PR turns "_processing xx_" into "_xx processed_".
Before PR:
```
Processing TV Shows  [####################################]  16/16
INFO: Processing TV Shows in 12.7 seconds
```
After PR:
```
Processing TV Shows  [####################################]  16/16
INFO: TV Shows processed in 12.7 seconds
```
=> Measure_time end label ≠ progress label

Pipfile, Pipfile.lock, plex_trakt_sync/cli.py, plex_trakt_sync/commands/cache.py, requirements.txt
refs:
- https://github.com/reclosedev/requests-cache/issues/224
- https://github.com/reclosedev/requests-cache/issues/223
=> Upgrade requests-cache to 0.6.x

plex_trakt_sync/commands/sync.py, plex_trakt_sync/walker.py, tests/test_walker.py
Prototype for the class that can be configured as what to find and walk.
This refactors filtering to Waker class, making sync command to do just;
```python
for movie in walker.find_movies():
print(movie)
for episode in walker.find_episodes():
print(episode)
```
=> Add Walker class

plex_trakt_sync/trakt_list_util.py
A playlist missing in Plex is not supposed to be an error because :
- at first sync, it is normal that plex playlist are not yet created
- user can remove any plex playlist if he wants to
When #124 will be fixed, the lists sync logic will probably change.
But in the meantime, this PR moves "playlist not found" log level from **error** to **debug**.
User can get confused with such errror message and I understand https://github.com/Taxel/PlexTraktSync/issues/228#issuecomment-826988411
Especially if the message states that the playlist needs to be deleted 😄 
```
ERROR: Playlist Rotten Tomatoes: Best of 2019 not found, so it could not be deleted. Actual playlists: [<Playlist:/playlists/282615:70's-Comedies>, <Playlist:/playlists/280507:80s-Comedy>, <Playlist:/playlists/282612:90's-Comedies>, …
```
=> Change "playlist not found" log level

plex_trakt_sync/commands/sync.py, plex_trakt_sync/trakt_api.py, plex_trakt_sync/trakt_list_util.py
Adds `media_type` in lists to prevent mismatch of movies & episodes items based of their trakt id.
fixes #228
=> Fix addPlexItemToLists by adding media_type

README.md
Documentation for https://github.com/Taxel/PlexTraktSync/pull/192
NOTE: The Trakt app may need scrobble permission:
- https://trakt.docs.apiary.io/#reference/scrobble
=> Add documentation about watch scrobbling

plex_trakt_sync/commands/inspect.py
Avoid fatal errors when inspecting a show. Show apparently does not have any media properties.
=> Skip print media details for type show

plex_trakt_sync/commands/cache.py
```
➔  ./plex_trakt_sync.sh cache --help
Usage: main.py cache [OPTIONS]
Manage and analyze Requests Cache.
Options:
--sort [size|date]  Sort mode  [default: size]
--limit INTEGER     Limit entries to be printed  [default: 20]
--reverse           Sort reverse
--help              Show this message and exit.
```
=> Add advanced options for cache printing

plex_trakt_sync/commands/sync.py, plex_trakt_sync/walker.py
This should help understand what is going to be "walked over".
refs:
- https://github.com/Taxel/PlexTraktSync/issues/291
=> Add printing of walk plan

plex_trakt_sync/commands/sync.py
Removes printing of:
1. <del>server version</del>
2. last added media
those are not useful, wastes time on roundtrip for the requests, wastes resources on the server to calculate the result, and slows down the script startup.
for me, those take off 1-3 seconds of startup time.
if such information is required for debugging, we can add specific command for that.
=> Remove slow server info printing

plex_trakt_sync/trakt_api.py
The check for media type in response should be removed:
- https://github.com/Taxel/PlexTraktSync/blob/75dc59ef463f678cb48998ac372582bb2c0f9935/plex_trakt_sync/trakt_api.py#L218
as the media type is always passed in query:
- https://github.com/Taxel/PlexTraktSync/blob/75dc59ef463f678cb48998ac372582bb2c0f9935/plex_trakt_sync/trakt_api.py#L215
I didn't remove it yet, added logging in case Trakt or Trakt API is misbehaving.
=> Add error logging for search returning wrong media type

plex_trakt_sync/cli.py, plex_trakt_sync/commands/webhook.py
The webhook can be used for Tautulli Webhook Notification Agent endpoint:
- https://github.com/Tautulli/Tautulli/wiki/Notification-Agents-Guide#webhook
```
➔ ./plex_trakt_sync.sh webhook --help
Usage: main.py webhook [OPTIONS]
Listen for WebHook data from HTTP
Options:
--bind TEXT     Address to listen on  [default: localhost]
--port INTEGER  TCP port to listen on  [default: 7707]
--help          Show this message and exit.
```
NOTE: This webhook doesn't do right now anything else than find a matching Plex item and print it.
=> Add webhook command for Tautulli

plex_trakt_sync/commands/cache.py
With request_cache 0.5.x the cache command prints many screens of gibberish (serialized cache objects).
This makes error shorter and indicating the user how to proceed.
=> Add check that requests_cache is upgraded

plex_trakt_sync/plex_server.py
Add @nocache to get_plex_server method, Add wrapper class as `@nocache` requires class methods.
The breakage came form this being get_plex_server being not called with request cache disabled:
```py
with requests_cache.disabled():
server = get_plex_server()
```
Somehow that affected also other calls made by `server` later on.
Fixes https://github.com/Taxel/PlexTraktSync/issues/307
=> Fix Plex requests being cached

plex_trakt_sync/commands/sync.py, plex_trakt_sync/config.py
This allows using other commands than sync without config being present:
- Plex Login: https://github.com/Taxel/PlexTraktSync/pull/230
- Trakt Login: https://github.com/Taxel/PlexTraktSync/pull/243
refs:
- https://github.com/Taxel/PlexTraktSync/issues/306
=> Move .env init check out of config to sync command

.dockerignore
It seems that the py files in the subfolders are being ignored and not being copied to the image.
the globstar syntax `!/plex_trakt_sync/**/*.py`, and even single folder wildcard syntax `!/plex_trakt_sync/*/*.py` don't seem to work for me either, so I had to specify the folder exclusions individually.
=> include commands and decorators folders as .dockerignore exclusions

plex_trakt_sync/trakt_api.py
A possible workaround for https://github.com/moogar0880/PyTrakt/issues/150
The side effect is that on import pytrakt tries to load `~/.pytrakt.json`, which usually does not exist, and when this application runs local `.pytrakt.json` is loaded again.
this relies on from internal import:
```py
trakt.core import load_config
```
the import works, but it's not present in `__all__`, meaning it's internal method.
- https://github.com/moogar0880/PyTrakt/blob/3.1.0/trakt/core.py#L415
=> Lazy init trakt config on use, not on import

Pipfile, Pipfile.lock, requirements.txt
The `websocket` package is required to run in "watch" mode:
- https://github.com/Taxel/PlexTraktSync/issues/312
Fixes https://github.com/Taxel/PlexTraktSync/issues/312
=> Add websocket-client 1.0.1 dependency

plex_trakt_sync/cli.py, plex_trakt_sync/commands/login.py, plex_trakt_sync/commands/plex_login.py, plex_trakt_sync/commands/sync.py, plex_trakt_sync/commands/trakt_login.py
This replaces need for `get_env_data` code.
- adds new `login` command. used internally, but users can invoke too
- calls `trakt-login` and `plex-login` commands if respective tokens are missing
The `get_env_data` along with the `get_env_data.py` will be removed in as separate PR.
=> Call new login commands in case tokens are missing

plex_trakt_sync/commands/login.py, plex_trakt_sync/commands/sync.py
This solves the problem that adding `click` decorator changed the behavior of the method.
When the first problem of click calling `sys.exit` was fixed with `standalone=False`, then next problem is that options are passed to the wrong command, i.e to `login` command, not to `sync` command.
=> Add ensure_login method without click decorator

plex_trakt_sync/decorators/rate_limit.py
Instead of raising a python error and crash when Trakt do not respond properly, it will explain the problem as coming from Trakt, tell user to retry later and abort the script run.
closes #333
=> Handle trakt bad response & ends script

README.md, plex_trakt_sync/plex_api.py
This bumps Python minimum version to 3.7
_Extracted from https://github.com/Taxel/PlexTraktSync/pull/330_
=> Add support for forward declare of annotations

plex_trakt_sync/trakt_api.py
_Extracted from https://github.com/Taxel/PlexTraktSync/pull/341_
The Trakt API states that tvdb is only for shows and episodes :
- https://trakt.docs.apiary.io/#reference/search/id-lookup/get-id-lookup-results
Plex should not be able to match tvdb id for movies, so it can't exist as guid..., but it can exist as guid in Plex:
- https://github.com/Taxel/PlexTraktSync/issues/318#issuecomment-855386958
Closes #318
=> Prevent tvdb movie search trakt request

plex_trakt_sync/decorators/__init__.py, plex_trakt_sync/decorators/http_cache.py, plex_trakt_sync/requests_cache.py
Opposite of `@nocache`, to indicate the method needs to be cached.
In the future add support for `ttl` parameter.
=> Add http_cache decorator

plex_trakt_sync/commands/clear_collections.py, plex_trakt_sync/commands/inspect.py, plex_trakt_sync/commands/sync.py, plex_trakt_sync/commands/trakt_login.py, plex_trakt_sync/commands/watch.py, plex_trakt_sync/commands/webhook.py, plex_trakt_sync/factory.py, tests/conftest.py, tests/test_batch.py, tests/test_new_agent.py, tests/test_plex_search.py, tests/test_tv_lookup.py, tests/test_walker.py
This simplifies code by moving object instantiation to a single place. Some places behaved differently because `get_plex_server()` wasn't used, but `PlexServer()` directly.
=> Refactor: Add factory class for controlling API instances

plex_trakt_sync/commands/sync.py, plex_trakt_sync/decorators/__init__.py, plex_trakt_sync/decorators/http_cache.py, plex_trakt_sync/decorators/nocache.py, plex_trakt_sync/factory.py, plex_trakt_sync/plex_api.py, plex_trakt_sync/plex_server.py, plex_trakt_sync/requests_cache.py, plex_trakt_sync/trakt_api.py, plex_trakt_sync/walker.py
Having a local module with the same name as the package is confusing. Confusing for IDE and then confusing to humans as IDE can't resolve symbols.
=> Refactor: Remove requests_cache local module

plex_trakt_sync/plex_api.py
Requires:
- https://github.com/Taxel/PlexTraktSync/pull/211
Refs:
- https://github.com/Taxel/PlexTraktSync/issues/117
=> Add media_type to collection metadata when adding media to collections

Pipfile, Pipfile.lock, plex_trakt_sync/decorators/deprecated.py, requirements.txt
The deprecation messages can be made visible with `PYTHONWARNINGS` variable:
- https://docs.python.org/3/library/devmode.html#devmode
To print them:
```
export PYTHONWARNINGS=default
```
To make the program abort:
```
export PYTHONWARNINGS=error
```
you can set this value in `.envrc.local`:
- https://github.com/Taxel/PlexTraktSync/pull/346
=> Add @deprecated decorator

Pipfile, Pipfile.lock, plex_trakt_sync/decorators/http_cache.py, plex_trakt_sync/decorators/nocache.py, plex_trakt_sync/factory.py, plex_trakt_sync/trakt_api.py, requirements.txt
requires pytrakt 3.2.0:
- https://github.com/moogar0880/PyTrakt/pull/151
this updates trakt calls to use CachedSession rather global patching.
eventually when global patching is removed (https://github.com/Taxel/PlexTraktSync/pull/342), this improves performance:
- https://github.com/reclosedev/requests-cache/issues/295
=> Refactor: Use CachedSession for trakt  requests

plex_trakt_sync/factory.py
Bugfix to https://github.com/Taxel/PlexTraktSync/pull/355
=> Ensure CachedSession uses same cache path as before

Pipfile, Pipfile.lock, requirements.txt
- https://github.com/pkkid/python-plexapi/releases/tag/4.5.1
- https://github.com/pkkid/python-plexapi/releases/tag/4.5.2
- https://github.com/pkkid/python-plexapi/releases/tag/4.6.0
- https://github.com/pkkid/python-plexapi/releases/tag/4.6.1
=> Update plexapi to 4.6.1

plex_trakt_sync/plex_api.py
return early in guids method, if legacy agent as accessing .guids for legacy agent
will make another round-trip to plex server and the result is always empty anyway.
=> Speedup .guids access for legacy agent

plex_trakt_sync/media.py
_Replaces https://github.com/Taxel/PlexTraktSync/pull/341_
Walk over guids until matching result from Trakt.
Guids are processed in preferred order to minimize API calls:
- https://github.com/Taxel/PlexTraktSync/issues/313#issuecomment-838447631
This can be merged ok, since the performance problem has been eliminated:
- https://github.com/Taxel/PlexTraktSync/pull/358
fixes #318
fixes #338
=> Always walk all guids to find a match

plex_trakt_sync/plex_api.py
This project requires Python 3.7 (since 0.11.0), so code to support Python < 3.6 can be safely dropped.
refs:
- https://github.com/Taxel/PlexTraktSync/pull/336
=> Remove py<3.6 support

Pipfile, Pipfile.lock, requirements.txt
Refs :
- https://github.com/reclosedev/requests-cache/compare/v0.7.0...v0.7.1
- https://github.com/urllib3/urllib3/releases/tag/1.26.6
=> Update requests-cache to 0.7.1 (urllib3 to 1.26.6)

plex_trakt_sync/plex_api.py
Fixes #380 
Checks that the xml parser does not return None
=> Add null checks in metadata parsing

Pipfile.lock
I tried to understand why updating requests-cache to 0.7.1 (#378) added [pyaml](https://pypi.org/project/pyaml/) dependency, so I regenerated `Pipfile.lock`.
somewhy the result is not identical:
- chardet 4.0.0 replaced with charset-normalizer 2.0.1
- requests updated to 2.26.0
- idna updated to 3.2
- typical markers flip-flop
Here's the full dependency graph:
```
$ pipenv graph
click==7.1.2
Deprecated==1.2.12
- wrapt [required: >=1.10,<2, installed: 1.12.1]
PlexAPI==4.6.1
- requests [required: Any, installed: 2.26.0]
- certifi [required: >=2017.4.17, installed: 2021.5.30]
- charset-normalizer [required: ~=2.0.0, installed: 2.0.1]
- idna [required: >=2.5,<4, installed: 3.2]
- urllib3 [required: >=1.21.1,<1.27, installed: 1.26.6]
python-dotenv==0.15.0
python-git-info==0.7.1 …
```
=> Regenerate Pipfile.lock

Pipfile, Pipfile.lock, plex_trakt_sync/commands/sync.py, plex_trakt_sync/logging.py, plex_trakt_sync/walker.py, requirements.txt
I managed to fix #377 by using tqdm and some minimal changes. tqdm is even [recommended by click](https://click.palletsprojects.com/en/8.0.x/utils/#showing-progress-bars) if you want a more capable progress bar. It is also much faster.
> Note
If you find that you have requirements beyond what Click’s progress bar supports, try using tqdm.
The log messages are now printed in a different line without interrupting the progress bar:
Fixes #377
=> Tqdm progressbar

plex_trakt_sync/commands/plex_login.py
```
INFO: Syncing with Plex None and Trakt twolaw
...
```
=> Fix Plex username being 'None'

plex_trakt_sync/plex_api.py
Reads Plex media picture **width** instead of picture **height** to get their correct resolutions.
discussed in:
- https://github.com/Taxel/PlexTraktSync/pull/366#issuecomment-878592575
closes #117
refs:
- https://github.com/trakt/Plex-Trakt-Scrobbler/pull/490
=> Fix resolution detection of Plex medias (uses picture width)

config.default.json, plex_trakt_sync/commands/cache.py, plex_trakt_sync/decorators/http_cache.py, plex_trakt_sync/factory.py
The intent is to keep the cache out of project dir.
Example:
```json
{
"cache": {
"path": "~/.cache/PlexTraktSync/http_cache"
},
```
=> Make cache path configurable

plex_trakt_sync/media.py
1ceb69d33b2a6f84465767357047663ce6b949a5 removed information (media type and media name) in two log messages, making more difficult for user to identify concerned media.
Exemple :
`Skipping <local://4392:<local:4392:<Movie:4392:Thomas-Vdb-Bon-Chien>>>: Provider local has no external Id`
became :
`Skipping local://4392: Provider local has no external Id`
This PR reverts it to bring back the full information in log messages.
=> Bring back guid error log verbosity

plex_trakt_sync/commands/unmatched.py
> TypeError: progressbar() got an unexpected keyword argument 'total'
https://github.com/Taxel/PlexTraktSync/pull/386 changed properties expected from progressbar. Update unmatched command to use tqdm as well.
=> Use tqdm progressbar for unmatched command

plex_trakt_sync/media.py
PR #415 is not correct because guid displayed in log is the first of PlexLibraryItem guids list.
This PR makes logger to display the guid effectively concerned by raised error.
`Skipping <local://4392:<Movie:4392:Thomas-Vdb-Bon-Chien>>: Provider local has no external Id`
becomes:
`<Movie:4392:Thomas-Vdb-Bon-Chien>: Skipping guid local://4392 because provider local has no external Id`
`Skipping <tmdb:30983/1/33:<Episode:4381:Case-Closed-s01e33>>: Not found on Trakt`
becomes:
`<Episode:4381:Case-Closed-s01e33>: Skipping tmdb:30983/1/33 not found on Trakt`
closes #417
=> Display correct guid and media type/name in guid error log

README.md
better leave a note, so people won't report this as a bug.
refs:
- https://github.com/Taxel/PlexTraktSync/issues/324
=> Add note that watch command has no user filtering

plex_trakt_sync/plex_api.py
- Fixes https://github.com/Taxel/PlexTraktSync/issues/387
- Fixes https://github.com/Taxel/PlexTraktSync/issues/384
- Replaces https://github.com/Taxel/PlexTraktSync/pull/401
Problem is that the xml feed from section.all() does not contain data for media item .guids, so data for that is called when item.guids is first accessed, lazy loaded on demand.
Ideally this should be solved in PMS or python-plexapi:
- https://github.com/pkkid/python-plexapi/issues/808
=> Disable cache for guids resolve

tests/test_collection_metadata.py
test_collection_metadata.py fails as testdata has incorrect object
Fixes resolution in testdata
=> Test against resolution width on collection metadata

.github/workflows/docker-image.yml
Create and publish a Docker image to GHCR
on push to main branch and tags
To get these containers use
- `$ docker pull ghcr.io/taxel/plextraktsync:latest` to get latest built $tagged commit
- `$ docker pull ghcr.io/taxel/plextraktsync:main` to get latest build on main branch
Also available are tagged builds and tag for a branch:
- `$ docker pull ghcr.io/taxel/plextraktsync:$tag`
- `$ docker pull ghcr.io/taxel/plextraktsync:0.x`
https://github.com/Taxel/PlexTraktSync/pull/413#issuecomment-893778111
=> only set docker "latest" tag on tagged commits

tests/test_collection_metadata.py
collection metadata test fails because of local timezone in datetime object
this sets utc timezone when creating datetime object
=> Set timezone in collection metadata test

Dockerfile, Pipfile, README.md, plex_trakt_sync.sh, plex_trakt_sync/__main__.py
Add `__main__.py` module, to be able to run as module.
Refs:
- https://github.com/Taxel/PlexTraktSync/issues/427
There's an extra benefit of running as a module:
> A minor difference between scripts and modules is that when you import a module the system will attempt to use an existing .pyc file (provided it exists and is up to date and for that version of Python) and if it has to compile from a .py file it will attempt to save a .pyc file. When you run a .py file as script it does not attempt to load a previously compiled module, nor will it attempt to save the compiled code. For this reason it may be worth keeping scripts small to minimise startup time.
- https://stackoverflow.com/a/2997044/2314626
=> Add __main__ module to run script as module

plex_trakt_sync/plex_api.py
520cf77 removed `@memoize`, so the `all()` was actually called twice.
This instead makes a simple API call with no data:
```
"GET /library/sections/1/all?includeCollections=0&X-Plex-Container-Size=0&X-Plex-Container-Start=0 HTTP/1.1" 200 335
```
For my library of 644 items (cache is filled) the timing is:
- before: 9.7s, 10.0s, 9.1s
- after: 6.6s, 6.4s, 6.4s
=> Use section.totalSize to figure out item count in section

plex_trakt_sync/commands/sync.py, plex_trakt_sync/commands/unmatched.py
to allow them to not use the progress bar, this can be used to simplify the output for non-interactive situations
=> Add `no-progress-bar` option to the sync and unmatched commands

plex_trakt_sync/plex_api.py, plex_trakt_sync/walker.py
Instead of getting all results via [plexapi.library.LibrarySection.all()], implement pager locally to buffer at most `X_PLEX_CONTAINER_SIZE` items at a time.
This should reduce memory consumption to a constant value.
Users with a large library may find the progress bar being more responsive: it starts to process items sooner.
[plexapi.library.LibrarySection.all()]: https://python-plexapi.readthedocs.io/en/latest/modules/library.html#plexapi.library.LibrarySection.all
NOTE: This uses private method section._buildSearchKey, which may break with any PlexAPI update. Instead, such yielding by page size should be implemented in PlexAPI itself.
About the implementation: it's important to have `fetch_items` with `@nocache` as a separate method (instead in method `all()` directly), as using …
=> Buffer results in section.all() by page size

plex_trakt_sync/logging.py
`tqdm.tqdm` implements necessary `.write()` method, so it can be used as a stream.
refs https://github.com/Taxel/PlexTraktSync/pull/386
cc @mcdallas
=> Drop TqdmLoggingHandler class

plex_trakt_sync/plex_api.py
When matching for `XBMCnfoTVImporter` the guid is `xbmcnfotv` not `xbmcnfo`:
- `com.plexapp.agents.xbmcnfotv://76290?lang=xn`
Fixes #452
=> Match xbmcnfotv also for xbmc-providers

plex_trakt_sync.sh
This makes cron job execution simpler, without the need to `cd`.
=> Change working dir to application dir in launch wrapper

plex_trakt_sync/config.py
WHen user has outdated `config.json`, do not raise an error when figuring out cache path. Do the envsubst after config merge of defaults and user config.
This is regression after https://github.com/Taxel/PlexTraktSync/pull/457
=> Fix cache.path access for unmerged config

plex_trakt_sync/plex_api.py
NOTE: yield and @nocache do not play well. do not mix them in same
method.
This fixes episode state caching for a new plex agent.
Fixes https://github.com/Taxel/PlexTraktSync/issues/450
Internally for a new agent, `.all()` gives out xml with `<Directory ratingKey>` pointing to season, and Plex API internally makes /allLeaves call for episodes.
This means the `/allLeaves` call used to be cached.
=> Ensure item.episodes() is invoked under @nocache

Dockerfile, plex_trakt_sync/commands/plex_login.py
`PLEX_FALLBACKURL=http://localhost:32400` in **.env** is irrelevant if script runs inside a docker container. In this case, _localhost_ refers to the container only but Plex is not in the same container.
This PR adds code to detect (during Plex credentials setup) if run inside docker, find container host ip adress and write `PLEX_FALLBACKURL=http://ip_address:32400` instead. 
172.17.0.1 is the default ip address of container's host.
This is not an important issue because the PLEX_FALLBACKURL is used only as last resort, when Plex connection fails.
~~Docker detection is made through _/.dockerenv_ file or _/proc/self/cgroup_ content.~~
~~_Another solution would be to create a dedicated environment variable (such as RUN_IN_DOCKER) at container creation so it could be read during setup._~~
=> Change Plex fallback url if run in docker

plex_trakt_sync/trakt_api.py
The idea of this PR :
The trakt `watched_movies` list used during sync is created when syncing the first movie of the first library.
It is later read to know the watched status of other movies, but it is memoized so not fetched from trakt server. Therefore, it can give a wrong not-watched status when a movie is scanned for the second time in the same sync session.
The idea is to update this list each time a movie is marked as watched in trakt.
With this list up-to-date, the script will know the correct watched status of a movie even if it has already been scanned in the same session.
https://github.com/Taxel/PlexTraktSync/blob/83ded352c7611ccb0399a1408c9c13b0b9581833/plex_trakt_sync/trakt_api.py#L90-L98
fixes #476
=> Fix duplicate watched status in trakt (due to movie in multiple Plex libraries)

plex_trakt_sync/pytrakt_extensions.py, plex_trakt_sync/trakt_api.py
Same as #477 but for tv shows.
fixes #476 
note : [pytrakt_extensions.py](https://github.com/Taxel/PlexTraktSync/blob/main/plex_trakt_sync/pytrakt_extensions.py) uses many `if value in dict.keys():` which [seems](https://stackabuse.com/python-check-if-key-exists-in-dictionary/) to be slower than `if value in dict:`
note 2 : please @glensc do not merge in a hurry.
=> Fix duplicate watched status in trakt (due to tv episode in multiple Plex libraries)

Dockerfile
So that output can be shown in `docker logs`
=> use unbuffered output for docker

README.md
Reorganised readme so it is easier to follow.
- Each step is now a dot point, with alternative options (such as Pipenv) being listed with `or` to make it clear.
- New `Commands` section gathers together Sync, Unmatched & Watch into one logical space, to which further commands can be added as needed.
- Previous `Notes` footnotes have been redistributed to their logical sections for easier reference.
=> Reorganised readme

plex_trakt_sync/commands/watch.py, plex_trakt_sync/plex_api.py
This shows that watching "play" / "unplayed" events from Plex Media Server is possible for https://github.com/Taxel/PlexTraktSync/issues/495
This prints:
```
Activity: <tmdb:xxx>: Watched: Plex: True, Trakt: False
Activity: <tmdb:xxx>: Watched: Plex: False, Trakt: False
```
=> Feature: Add example ActivityNotification to watch command

plex_trakt_sync/listener.py, tests/test_events.py
Bugfix to https://github.com/Taxel/PlexTraktSync/pull/501 to fix logic error that mistakenly accepted the first match on object property.
=> Fix: Update match logic to match all conditions

config.default.json, plex_trakt_sync/commands/watch.py, plex_trakt_sync/events.py, plex_trakt_sync/plex_api.py
To enable this feature, change `config.json`:
```json
"watch": {
"username_filter": true
},
```
NOTE: it's important that you log in with plex account name, not email. i.e `PLEX_USERNAME` must be the account name.
Fixes https://github.com/Taxel/PlexTraktSync/issues/324, Replaces https://github.com/Taxel/PlexTraktSync/pull/480
=> Add username filter to watch command

plex_trakt_sync/commands/watch.py, plex_trakt_sync/events.py
This updates https://github.com/Taxel/PlexTraktSync/pull/499 so that it doesn't receive too much unwanted updates
=> Fix:  Update on_activity to match only type=library.refresh.items

plex_trakt_sync/listener.py
Also decrease interval for loop polling. Websocket events are immediate, there's no reason to spam server so often as 1s.
=> Watch: Add different interval for restarts

Pipfile, Pipfile.lock, plex_trakt_sync/commands/plex_login.py, requirements.txt
Simplified user input using InquirerPy:
- Server selection _(selectable list)_
- Managed user Y/N _(made redundant by below)_
- Managed user selection _(selectable list, including default main username)_
=> Use InquirerPy for user input

plex_trakt_sync/trakt_list_util.py
This PR creates **LazyUserList** class being inherited from trakt **UserList** class but without requesting each item of the list to Trakt API.
Fetching Trakt lists should be much faster and not crashing if above 1000 items (GET rate limit of trakt API).
fixes #489
=> Use LazyUserList to fetch Trakt Lists faster

.github/workflows/docker-image.yml
The image name needs to be lowercased for docker build to succeed:
```
/usr/bin/docker buildx build --build-arg APP_VERSION=0.14.0-3-g8cbf1f4_main --tag ghcr.io/Taxel/PlexTraktSync:ci-test --iidfile /tmp/docker-build-push-kpnBCT/iidfile --metadata-file /tmp/docker-build-push-kpnBCT/metadata-file --load .
error: invalid tag "ghcr.io/Taxel/PlexTraktSync:ci-test": repository name must be lowercase
Error: buildx failed with: error: invalid tag "ghcr.io/Taxel/PlexTraktSync:ci-test": repository name must be lowercase
```
- https://github.com/Taxel/PlexTraktSync/runs/3743383829?check_suite_focus=true
Use hardcoded docker image for test
As GitHub actions does not provide builtin lowercase method:
- https://docs.github.com/en/actions/learn-github-actions/expressions#functions
just use fixed name, …
=> Fix: Lowercase docker image used for test

.github/workflows/docker-image.yml
Add support for arm64, `armhf`/`armv7`. Close #522
=> Add multi arch support for Docker images

plex_trakt_sync/sync.py
User choose what to sync in the config file.
There is no reason to unconditionaly cache trakt requests if they won't be used.
=> Remove trakt unconditional caching

plex_trakt_sync/pytrakt_extensions.py
Removes the 10 items limit of liked lists.
Trakt API doc: [Get likes](https://trakt.docs.apiary.io/#reference/users/likes/get-likes), [Pagination](https://trakt.docs.apiary.io/#introduction/pagination)
fixes #564
=> Raise pagination limit to 1000 liked lists

plex_trakt_sync/pytrakt_extensions.py, plex_trakt_sync/trakt_api.py
First, this PR needs to be merged :
- https://github.com/moogar0880/PyTrakt/pull/157
Then we could fix the `AttributeError: 'dict' object has no attribute 'trakt'` and properly get the show trakt id of every watched episodes.
Fixes #487
=> Fix finding show trakt id from trakt episode

.dockerignore, Dockerfile, plex_trakt_sync/__init__.py
This changes build logic, that pipenv is not included in final image.
pipenv is build time dependency used to lock dependencies.
- Before: 133MB
- After: 72.9MB
=> Build docker image without pipenv dependency

plex_trakt_sync/plex_api.py
Probably this should be handled systematically, but happened once to me for this method, so it's a quick fix. Move along.
=> Fix: handle Plex Server errors from _get_episodes method

plex_trakt_sync/commands/sync.py, plex_trakt_sync/commands/unmatched.py, plex_trakt_sync/plex_api.py, plex_trakt_sync/walker.py, tests/test_walker.py
For end-user, this validates input arguments before starting sync process by fetching matches from Plex Server.
This also handles filtering by libraries (sections), so if `--library` is passed then `--show` or `--id` will find only matches from the named libraries.
And `excluded-libraries` is now respected when `--show` or `--movie` option is used.
Fixes https://github.com/Taxel/PlexTraktSync/issues/291
Requires:
- https://github.com/Taxel/PlexTraktSync/pull/573
=> Feature:  Add WalkPlanner that validates inputs against plex server

plextraktsync/commands/sync.py, plextraktsync/walker.py
Fixes `--id` option repeat for Movies sync.
Noticed that specifying episodes with `--id` option doesn't do anything. To be fixed later.
=> Fix multiple --ids support for sync

plextraktsync/factory.py
Remove printing of this warning:
```
plextraktsync/walker.py:250: TqdmExperimentalWarning: rich is experimental/alpha
pb = self._progressbar(iterable, **kwargs)
```
=> Fix: Disable tqdm ExperimentalWarning

plextraktsync/commands/sync.py, plextraktsync/commands/unmatched.py, plextraktsync/config.py, plextraktsync/factory.py, plextraktsync/walker.py
This simplifies code needing to pass parameters around multiple methods. For example `media_factory(batch_size=batch_size)` was present just to be passed to `factory.trakt_api()`.
To get walker instance with defaults, can now just call `factory.walker()`
=> Refactor: Add RunConfig and factory for worker

plextraktsync/media.py, plextraktsync/plex_api.py, plextraktsync/trakt_api.py
Drop the methods that used only one guid. The methods are not in use.
=> Chore: Cleanup long deprecated methods

README.md, plextraktsync/cli.py, plextraktsync/commands/info.py, plextraktsync/commands/sync.py
Rename "version" command to "info" and put all info printing to that command.
Besides putting all useful info to same place,
this improves privacy when people paste sync command output to bug reports.
=> Refactor: Rename "version" command to "info"

plextraktsync/commands/sync.py
Plan validation happens in `w.print_plan`, so add exception check.
The sync method can throw as well, so keep the exception:
```
Error: Unexpected call: episode without show property
```
=> Fix: Catch error from plan validaion

plextraktsync/trakt_api.py
`search_by_id` takes guid.id as intput, and that must be numeric, or with `tt` prefix (imdb), with too long input, trakt gives out 500 error.
Refs @twolaw  note:
- https://github.com/Taxel/PlexTraktSync/issues/591#issuecomment-963553557
=> Fix: Skip search_by_id with invalid input

plextraktsync/media.py, plextraktsync/trakt_api.py
Show trakt id is needed for episodes added in `watched_shows` during sync (to keep this list up-to-date in real time).
Instead of requesting Trakt API based on show name, we can get this id from the `show_trakt_id` attribute.
Fixes #615
=> Remove unnecessary request to trakt api to get show trakt id

Dockerfile
Fixes docker build without --build-arg:
- https://github.com/Taxel/PlexTraktSync/pull/605#issuecomment-975173494
=> Allow building docker image without APP_VERSION build argument

plextraktsync/config.py, tests/test_config.py
This helps in cases when config.default.json will have new key under section that already has a value:
// config.json
```json
"logging": {
"append": false
},
```
// config.default.json
```json
"logging": {
"append": true,
"filename": "plextraktsync.log"
},
```
without this changeset, the final config would be:
```json
"logging": {
"append": false
},
```
but needs to be:
```json
"logging": {
"append": false,
"filename": "plextraktsync.log"
},
```
=> Feature: Deep merge config.defaults.json

plextraktsync/plex_api.py
Fixes https://github.com/Taxel/PlexTraktSync/issues/606
=> Decorate mark_watched with rate_limit to retry Plex Server errors

plextraktsync/walker.py
The typing was incorrect anyway:
```py
list[Movie, Show, Episode]
```
The values are actually strings, not objects.
refs:
- https://github.com/Taxel/PlexTraktSync/issues/619#issuecomment-991923551
- https://docs.python.org/3/whatsnew/3.9.html#type-hinting-generics-in-standard-collections
=> Fix: restore python 3.8 support

plextraktsync/plex_api.py
Happens when trying to inspect an epsode
```
if media_id[0:2] == 'tt' and media_id[2:].isnumeric():
TypeError: 'int' object is not subscriptable
```
=> Fix: Do not cast show_id to integer to avoid error in valid_trakt_id method

plextraktsync/plex_api.py
Fixes https://github.com/Taxel/PlexTraktSync/issues/650
Adds solution for 'hd_1080p', 'hd_720p' only as don't have any other media to test with.
=> Feature: Try to use stream.displayTitle for resolution detection

plextraktsync/plex_api.py
May increase memory usage for https://github.com/Taxel/PlexTraktSync/issues/431
=> Fix: Don't memoize properties being accessed only once

plextraktsync/media.py, plextraktsync/plex_api.py
This may call fetch by plex and it may be cached
or later code could prevent last seen date being incorrect
Probably fixes https://github.com/Taxel/PlexTraktSync/issues/631 and fixes https://github.com/Taxel/PlexTraktSync/issues/619
=> Fix: Prevent rating key access filling cache with stale data

plextraktsync/sync.py
The detection if old config should be used for syncing got broken after https://github.com/Taxel/PlexTraktSync/pull/604
=> Fix: Handle config merge better

plextraktsync/logging.py
Plex entries were duplicated once debug log is enabled.
=> Fix: Don't setup duplicate logging for Plex

plextraktsync/commands/inspect.py, plextraktsync/plex_api.py
Since rating fetching for all items is super slow:
- https://github.com/Taxel/PlexTraktSync/pull/666#issuecomment-997428206
add method to find Plex items that have rating value present.
=> Refactor: Fetch Plex userRatings in a separate call

.gitignore, README.md, plextraktsync/config.default.json, plextraktsync/logging.py
This enables append=true to keep all logs, therefore having last_update as log filename is no longer appropriate.
Also, moved all logging options under "logging" in config file.
=> Feature: Use plextraktsync.log as log filename

plextraktsync/commands/plex_login.py
Avoid crashing when Plex server is not found
Just exit with a short error. Fix for https://github.com/Taxel/PlexTraktSync/issues/677
```
➜ python -m plextraktsync plex-login
You already have Plex Access Token, do you want to log in again? [Y/n]:
Please enter your Plex username or e-mail [*redacted*]:
If you have 2 Factor Authentication enabled on Plex you can append the code to your password below (eg. passwordCODE)
Please enter your Plex password:
Login to MyPlex was successful!
Error: Unable to find server from Plex account
➜
```
=> Fix: Avoid crashing when Plex server is not found

README.md
I went ahead and added the information about the new logging options in config.json to the README.md
At the same time I restructured it somewhat, grouping the installation methods together (instead of having windows and unraid spread through). and added a TOC.
=> Add logging to README.md and Re-structure

plextraktsync/commands/unmatched.py
This will print movies that have no Plex match (`local://` guid).
=> Feature: Add --local to unmatched command

plextraktsync/commands/plex_login.py
Skip friend check. Managed users do not have a separate account (with email address)
I have tested it and it works great.
x-ref:
- https://github.com/Taxel/PlexTraktSync/discussions/680#discussioncomment-1929301
=> Fix login with managed users

plextraktsync/config.py
Fixes regression from https://github.com/Taxel/PlexTraktSync/pull/664
The side effect was that old `log_debug_messages` wasn't respected
=> Delegate __contains__ to inner dict to support contains queries

plextraktsync/commands/watch.py
The Activity monitor not to error when episode is opened.
NOTE: the activity only prints, performs no actions (yet).
=> Feature: Handle watch activity for episodes

plextraktsync/commands/watch.py, plextraktsync/config.default.json, plextraktsync/events.py, plextraktsync/listener.py, plextraktsync/media.py
This detects media delete events and deletes them from trakt collection if `config["watch"] ["remove_collection"]` is `true`.
The delete event payload looks like this:
```py
{
'type': 'timeline',
'size': 1,
'TimelineEntry': [{
'identifier': 'com.plexapp.plugins.library',
'sectionID': '2',
'itemID': '16336',
'parentItemID': '16325',
'rootItemID': '16324',
'type': 4,
'title': 'Pioneer One S01 E02',
'state': 9,
'metadataState': 'deleted',
'updatedAt': 1641766793
}]
}
```
This can be used for removing trakt collection on delete on plex:
- https://github.com/Taxel/PlexTraktSync/issues/374
Example:
```
INFO: Deleted Pioneer One S01 E05
INFO: Removed from Collection: <tvdb:170551/1/5:<Episode:16326:Pioneer-One-s01e05>>
```
NOTE: Deleting an episode results season and show become empty, those are …
=> Feature:  Add on_delete listener to watcher

plextraktsync/commands/watch.py, plextraktsync/events.py, plextraktsync/listener.py
Previously event dictionary was accepted as well, but it was only a single use, add a property for that instead.
=> Refactor: Simplify event dispatcher to accept only properties

plextraktsync/decorators/cached_property.py, plextraktsync/media.py, plextraktsync/path.py, plextraktsync/plex_api.py, plextraktsync/sync.py, plextraktsync/trakt_api.py, plextraktsync/walker.py
Some mitigation to https://github.com/Taxel/PlexTraktSync/issues/431
Instead of stacking `@property` and `@memoize` decorators, use `@cached_property`,  after which memory usage seems to be a bit better:
Tested with a library of 176 shows:
version | base memory | process end memory | difference
-- | -- | -- | --
0.18.6 | 44612 | 165000 | 120388 
cached_property | 45180 | 78384 | 33204
the command for measuring memory usage (RSS column):
```
htop -p $(ps -ef |awk '/[p]lextraktsync/{print $2}')
```
Fallback for order python versions (python<3.8) taken from:
- https://github.com/pydanny/cached-property/blob/409f24286e16ea3086af463edea6b80cdd62deed/cached_property.py#L18-L47
=> Use cached_property decorator to cache properties

plextraktsync/trakt_api.py
No longer needed as of pytrakt 3.4.0: #715
=> Chore: Omit load_config from trakt init

plextraktsync/media.py, plextraktsync/trakt_api.py
_Extracted from https://github.com/Taxel/PlexTraktSync/pull/720_
There are more types than movies and episodes.
This can avoid treating a show as an episode.
=> Fix: Add guards of unsupported media type

plextraktsync/media.py, plextraktsync/trakt_api.py, plextraktsync/walker.py, tests/test_tv_lookup.py
remove `@memoize` from:
- trakt_api::collected -> moved to media::collected
- trakt_api::lookup -> moved to media::seasons
so the cache is per episode/movie, not in the global traki_api class
see usage report:
- https://github.com/Taxel/PlexTraktSync/issues/431#issuecomment-1013444604
=> Feature: Move memoize from trakt_api to media class

plextraktsync/trakt_api.py
It's not useful for sync run and only consumes memory for cache that
nobody needs:
- https://github.com/Taxel/PlexTraktSync/issues/431#issuecomment-1013709208
originally added in ef991ea66b520bf243cfd0774afb379c5a1e6442
Fixes https://github.com/Taxel/PlexTraktSync/issues/431
=> Performance: Drop memoize of find_by_guid

plextraktsync/commands/self_update.py
older pipx gives:
```
pipx: error: unrecognized arguments: --json
```
So, for `self-update` command to work, pipx 1.0.0 is required
refs:
- https://github.com/Taxel/PlexTraktSync/issues/730
- #717
=> Fix: Discard pipx error output

.github/workflows/docker-image.yml
This could speed up Docker builds in GitHub Actions.
- https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md#github-cache
=> Chore: Enable docker image layer cache in GHA

plextraktsync/cli.py, plextraktsync/commands/cache.py, plextraktsync/commands/clear_collections.py, plextraktsync/commands/info.py, plextraktsync/commands/inspect.py, plextraktsync/commands/login.py, plextraktsync/commands/plex_login.py, plextraktsync/commands/sync.py, plextraktsync/commands/trakt_login.py, plextraktsync/commands/unmatched.py, plextraktsync/commands/watch.py
This prevents all commands being imported just to figure out their usage.
This has minor speedup for setting up the application due not importing commands that aren't executed in the current run.
=> Refactor: Lazy import commands

plextraktsync/commands/watch.py, plextraktsync/plex_api.py
If pulling server without admin access the `/sessions` request gives a forbidden error. This changes to detect such scenario and disabling username filter.
=> Fix: Disable username filter if no permission

plextraktsync/plex_api.py
Some mitigation to https://github.com/Taxel/PlexTraktSync/issues/742
Closes #742
=> Add retry to plex.rate method to overcome timeout error

plextraktsync/media.py, plextraktsync/plex_api.py
The plex item is decorated with nocache, so the call won't be cached.
=> Fix:  Use is_watched from plex item

plextraktsync/commands/inspect.py
Allow to use full urls like this:
```sh
$ plextraktsync inspect https://app.plex.tv/desktop/#!/server/abcdefg/details?key=%2Flibrary%2Fmetadata%2F13202
```
Selecting just the numeric part after `%2F` is rather tricky as double click on the number selects also `2F` i.e: `2F13202`
=> Feature:   Allow inspect to take full urls as input

plextraktsync/commands/watch.py, plextraktsync/trakt_api.py
Pass fresh progress value before calling stop/pause instead of previous value from update.
Probably fixes https://github.com/Taxel/PlexTraktSync/issues/758 and https://github.com/Taxel/PlexTraktSync/issues/766
This also improves logging, example:
```
2022-01-31 00:09:10,540 DEBUG[PlexTraktSync.WatchStateUpdater]:Scrobbled: {'id': 0, 'action': 'start', 'progress': 0.0, 'sharing': {'facebook': False, 'twitter': False, 'tumblr': False}, 'episode': {'season': 2, 'number': 4, ...
2022-01-31 00:09:16,294 DEBUG[PlexTraktSync.WatchStateUpdater]:Scrobbled: {'id': 0, 'action': 'pause', 'progress': 0.0, 'sharing': {'facebook': False, 'twitter': False, 'tumblr': False}, 'episode': {'season': 2, 'number': 4, ...
```
Requires:
- https://github.com/moogar0880/PyTrakt/pull/196
Refs:
- …
=> Fix: pass progress from plex when calling scrobble api

plextraktsync/plex_api.py
Fixes #778, a bug from https://github.com/Taxel/PlexTraktSync/pull/668
=> Fix: Do not cache ratings fetch

plextraktsync/trakt_api.py
Fix #778: A bug from https://github.com/Taxel/PlexTraktSync/pull/725
=> Fix: Skip cache of trakt ratings as well

plextraktsync/commands/plex_login.py, plextraktsync/config.py, plextraktsync/plex_server.py
In `.env` file, I suggest renaming the variable `PLEX_FALLBACKURL` to `PLEX_LOCALURL` so that **users understand and change this URL by themself** with a specific message in error logs.
______
After that, the local IP address auto-finding will have to be improved for docker users because 172.17.0.x doesn't look useful (see #775 and #816)
=> Rename Plex variable fallbackurl to localurl

plextraktsync/config.default.json, plextraktsync/config.py
Useful when the same `.env` file is used to initialize docker-compose but
want to change the `.env` file value at runtime.
This changes so that values of `.env` are always read even if the environment with the same name is already present.
```json
"config": {
"dotenv_override": true
},
```
See https://github.com/Taxel/PlexTraktSync/discussions/849
=> Feature: Add support to override .env keys from actual environment

plextraktsync/config.py
Fixes https://github.com/Taxel/PlexTraktSync/pull/850#issuecomment-1083064068
=> Fix: Set self.initialized early to avoid recursion error

plextraktsync/listener.py
Better logging for https://github.com/Taxel/PlexTraktSync/issues/866
The traceback will be logged to debug log:
```
2022-04-03 12:39:58,400 ERROR[PlexTraktSync.EventDispatcher]:'int' object does not support item assignment
2022-04-03 12:39:58,401 DEBUG[PlexTraktSync.EventDispatcher]:['  File "PlexTraktSync/plextraktsync/listener.py", line 41, in dispatch\n    f[2] = 3\n']
```
=> Feature: Catch exceptions locally in watch to capture traceback

plextraktsync/plex_api.py
Needed internally for `__rich__` method: https://github.com/Taxel/PlexTraktSync/pull/660
and https://github.com/Taxel/PlexTraktSync/pull/870
=> Feature: Add plex property to PlexLibraryItem/PlexLibrarySection

plextraktsync/config.py
Fixes https://github.com/Taxel/PlexTraktSync/issues/878
Avoid opening config with OS native encoding, always use utf-8.
=> Fix: Open config.json as utf-8

README.md
Reorganize instructions about `watch` command.
I move `watch` examples under the Watch section so the explanations of what it does are read first.
Some users run the `watch` command without fully understanding what it does.
Many docker users are concerned because they switch to `watch` to keep the container alive (a stopping container is not usual).
fixes #843 
fixes #860
=> Reorganize watch command instructions

plextraktsync/plex_api.py
Fixes https://github.com/Taxel/PlexTraktSync/issues/572
There's no major performance gain, as the parts are only accessed when the item is submitted to collection.
=> Fix: Reload item when accessing parts for media

plextraktsync/cli.py, plextraktsync/commands/sync.py, plextraktsync/config.py, plextraktsync/factory.py, plextraktsync/sync.py, plextraktsync/trakt_api.py, tests/test_batch.py
This PR changes the logic of batch sending of Plex collected items. The script now sends collected items to trakt based on **time interval** instead of **batch size**.
`--batch-delay`  (in seconds) is used instead of `--batch-size` option. Default is 5 seconds.
Logic is that collected items are sent every n seconds.
It reduces trakt number of requests for huge Plex libraries having many new items. Sync time should be reduced too.
⚠️ Only tested on a small library, please anyone test on big library and give feedback.
One annoying detail is the last `flush(force=True)` is displayed _after_ the message `INFO: Section processed in x seconds`
I don't understand why this last `flush()` was not implemented with the batch-size version because it is needed to finish the job if the last batch is …
=> Improve logic of collected items batch (send to trakt every n seconds)

plextraktsync/commands/inspect.py
Extracts id from urls like:
```
$ plextraktsync inspect https://app.plex.tv/desktop/#!/server/abcdefg/details?key=%2Flibrary%2Fmetadata%2F13202
$ plextraktsync inspect https://app.plex.tv/desktop/#!/server/abcdefg/playHistory?filters=metadataItemID%3D6041&filterTitle=&isParentType=false
```
=> Feature: Add ability to extract media id from playHistory plex url

README.md
If users don't want or can't use **cron** to schedule syncs at set intervals, there is an alternative with docker : [Ofelia](https://github.com/mcuadros/ofelia/)
This PR adds in README.md an example of Ofelia docker scheduler to run a sync every 6h.
=> Show docker scheduler example as cron alternative

Dockerfile
https://alpinelinux.org/posts/Alpine-3.14.0-released.html
This requires the docker host to be fresh enough:
> The faccessat2 syscall has been enabled in musl. This can result in issues on docker hosts with older versions of docker (<20.10.0) and libseccomp (<2.4.4), which blocks this syscall.
----
https://alpinelinux.org/posts/Alpine-3.15.0-released.html
=> Update Docker base image to alpine 3.15

plextraktsync/media.py, plextraktsync/pytrakt_extensions.py, plextraktsync/trakt_api.py
...instead of [/shows/id/progress/collection](https://trakt.docs.apiary.io/#reference/shows/collection-progress/get-show-collection-progress) request which returns only aired episodes. Trakt doc states:
> Note: Only aired episodes are used to calculate progress. Episodes in the future or without an air date are ignored.
The [sync/collection/shows](https://trakt.docs.apiary.io/#reference/sync/get-collection/get-collection) trakt request is better because it returns all collected episodes **even if not aired**.
There was a problem with episodes without airdate (typically specials episodes of season 0) being sent over and over to trakt, polluting log file.
Problem similar to PR https://github.com/Taxel/PlexTraktSync/pull/31
fixes #936
=> Get trakt shows collection through sync/collection/shows request

plextraktsync/plex_api.py
```
ERROR    'Tag' object has no attribute 'ratingKey'
DEBUG
File "PlexTraktSync/plextraktsync/listener.py", line 40, in dispatch
listener["listener"](event)
File "PlexTraktSync/plextraktsync/commands/watch.py", line 101, in on_activity
m = self.find_by_key(activity.key, reload=True)
File "PlexTraktSync/plextraktsync/commands/watch.py", line 79, in find_by_key
pm = self.plex.reload_item(pm)
File "PlexTraktSync/plextraktsync/plex_api.py", line 513, in reload_item
return self.fetch_item(pm.item.ratingKey)
```
=> Fix: Catch invalid ratingKey property fetch from watch

CONTRIBUTING.md, plextraktsync/__init__.py, plextraktsync/cli.py, plextraktsync/commands/self_update.py, pyproject.toml
See https://github.com/pypa/pipx/issues/812#issuecomment-1066684085
=> Feature: Add install from pull request instructions

plextraktsync/media.py, plextraktsync/trakt_api.py
Some TV Shows have different episodes ordering across source databases (tvdb, tmdb,...) and layout (aired, DVD, absolute).
- Trakt uses tmdb as primary source.
- Plex uses tmdb order as [default](https://support.plex.tv/articles/naming-and-organizing-your-tv-show-files/) but let users choose episodes ordering among sources (tvdb, tmdb) and layout order (aired, DVD, absolute).
Tmdb is the recommended source but sometimes another one has to be used.
What this PR adds :
Checks episodes id to correctly map episodes number between Plex (order chosen by user) and Trakt (tmdb order).
fixes #914
fixes #996
=> Check episodes id if ordering is different between Plex and Trakt

README.md, plextraktsync/commands/plex_login.py, plextraktsync/config.default.yml, plextraktsync/config.py, plextraktsync/media.py, plextraktsync/plex_api.py, plextraktsync/sync.py, plextraktsync/trakt_api.py, plextraktsync/walker.py
Adds sync between [Plex Universal Watchlist](https://support.plex.tv/articles/universal-watchlist/) (feature added april-2022) and Trakt Watchlist.
```yaml
sync:
plex_to_trakt:
watchlist: true
trakt_to_plex:
watchlist: true
watchlist_as_playlist: false
```
- If you want to sync watchlist only `one-way` (plex_to_trakt **or** trakt_to_plex), it will remove items on destination watchlist that are not on source watchlist (kind of overwrite to keep it perfectly identical).
- If you sync watchlist `two-way` (plex_to_trakt **and** trakt_to_plex), no items are removed.
Before this PR, the Trakt watchlist was synced as a standard playlist because Plex didn't have a Watchlist.
To keep this old behavior, edit config file to sync trakt_to_plex only and use `watchlist_as_playlist` :
```yaml
sync: …
```
=> Plex Watchlist sync

plextraktsync/plex_api.py
Use of new **Plexapi** property `isPlayed` and method `markPlayed()` instead of deprecated `isWatched` and `markWatched()`
Ref :
- https://github.com/pkkid/python-plexapi/pull/984
fixes #1016
=> plexapi isWatched markWatched are deprecated

plextraktsync/commands/sync.py, plextraktsync/rich_addons.py
The side-effect is that this makes output colored and thus easier to read perhaps.
```
➜ plextraktsync
INFO     PlexTraktSync [0.21.0dev0]
INFO     Sync Movie sections: [<PlexLibrarySection:movie:Movies>]
INFO     Sync Show sections: [<PlexLibrarySection:show:TV Shows>]
```
=> Refactor: Use logger to print walk plan

plextraktsync/commands/info.py, plextraktsync/config.py, plextraktsync/factory.py, plextraktsync/logging.py, plextraktsync/path.py
This makes info command be colored via rich package.
Also add log filename and cache filename to command output, as they can be reconfigured via config file. Internally it moves those path values building to Config class to avoid duplication.
=> Feature: Use logger to print messages in info command

plextraktsync/sync.py
Bypass watchlist sync if Plex watchlist is unavailable.
see #1022
=> Bypass if Plex watchlist is unavailable

plextraktsync/commands/sync.py, plextraktsync/sync.py
Do not walk across Plex libraries if it's not needed
=> Feature: Conditional library walk

plextraktsync/commands/plex_login.py, plextraktsync/config.py, plextraktsync/plex_api.py
Account token ≠ Resource access token for users with shared library
This PR adds the **plex_account_token** to `.env` file for Plex account users using a shared resource.
=> Add plex account token for shared resource

plextraktsync/walker.py
When searching Plex item by id, return the corresponding item only once even if it can be found in many sections.
fixes #1047
=> find_from_sections_by_id append item only once

plextraktsync/plex_api.py
This avoids warning when using watch
where plex account token is not yet available.
=> Fix: Setup PlexAccount only when needed

plextraktsync/plex_api.py
Mistakenly removed in eda493b6fc9a78e4645aa30c028a6b2400a3335c
Fixes https://github.com/Taxel/PlexTraktSync/issues/1090
=> Fix rating being property again

plextraktsync/commands/self_update.py
Workaround for pipx shortcoming:
- https://github.com/pypa/pipx/issues/902
=> Fix: Uninstall previous plextraktsync pr if already installed

plextraktsync/commands/self_update.py, plextraktsync/path.py, plextraktsync/util/packaging.py, plextraktsync/version.py
Prints something like:
```
$ plextraktsync@1100 info
INFO     PlexTraktSync Version: 0.22.0@pr1100#1a9c2ed6
```
Refs:
- https://github.com/Taxel/PlexTraktSync/pull/1100#issuecomment-1279705151
=> Fix: Add support to detect pipx install from a pr

CONTRIBUTING.md, plextraktsync/commands/self_update.py, plextraktsync/util/packaging.py, plextraktsync/version.py
this will update pr version of the command to latest pr changes of #1110:
```
$ plextraktsync@1110 self-update
```
=> Fix: Update self-update command to understand installed from pr

plextraktsync/cli.py
Just have `plextraktsync --version` around.
```
$ plextraktsync self-update --pr 1109
Updating PlexTraktSync to the pull request #1109 version using pipx
installed package PlexTraktSync 0.22.0.dev0 (PlexTraktSync@1109), installed using Python 3.10.8
These apps are now globally available
- plextraktsync@1109
done! ✨ 🌟 ✨
$ plextraktsync@1109 --version
PlexTraktSync 0.22.0@pr/1109#0c045225
```
=> Feature: Add --version global option

CONTRIBUTING.md, Pipfile, Pipfile.lock, requirements.txt
Testing to use trakt as git repository because current trakt maintainer is unavailable:
- https://github.com/moogar0880/PyTrakt/issues/199
Test for:
- https://github.com/Taxel/PlexTraktSync/issues/994
uses repo from:
- https://github.com/glensc/python-trakt
commands:
```
pipenv install "git+https://github.com/glensc/python-trakt@3.4.0#egg=trakt"
pipenv lock --requirements > requirements.txt
```
=> Use trakt from git repository

plextraktsync/commands/cache.py
Broken with upstream commit:
- https://github.com/requests-cache/requests-cache/commit/35b48cf3486e546a5e4090e8e410b698e8a6b7be#r87356998
=> Fix: Restore cache status reporting

plextraktsync/decorators/retry.py
Not sure what the handling should be. So added it to retry list.
```
WARNING  Bad Response - Response could not be parsed for plextraktsync.trakt_api.collected(), retrying after 1
seconds (try: 1/5)
WARNING  Bad Response - Response could not be parsed for plextraktsync.trakt_api.lookup(), retrying after 1 seconds
(try: 1/5)
WARNING  Bad Response - Response could not be parsed for plextraktsync.trakt_api.lookup(), retrying after 2 seconds
(try: 2/5)
WARNING  Bad Response - Response could not be parsed for plextraktsync.trakt_api.lookup(), retrying after 3 seconds
(try: 3/5)
WARNING  Retry using search for specific Plex Episode
```
Requires:
- https://github.com/moogar0880/PyTrakt/pull/181
- https://github.com/Taxel/PlexTraktSync/pull/1123
=> Feature: Add handling of BadResponseException

plextraktsync/pytrakt_extensions.py, plextraktsync/trakt_api.py, tests/test_tv_lookup.py
Requires:
- https://github.com/moogar0880/PyTrakt/pull/176
=> Refactor: Use TVShow.episodes property for episodes trakt id lookup

plextraktsync/commands/watch.py, plextraktsync/plex_api.py, plextraktsync/trakt_api.py
Use simplified super for python3:
- https://docs.quantifiedcode.com/python-anti-patterns/correctness/bad_first_argument_given_to_super.html
Refs:
- https://github.com/glensc/python-pytrakt/pull/4
=> Fix super() call for python3

plextraktsync/trakt_api.py, tests/test_tv_lookup.py
Test for https://github.com/Taxel/PlexTraktSync/pull/716#issuecomment-1289037337
=> Fix broken TraktLookup invalid match detection for New Agent

plextraktsync/media.py, plextraktsync/plex_api.py, plextraktsync/pytrakt_extensions.py, plextraktsync/sync.py
Trakt VIP members can [reset a show watched progress](https://support.trakt.tv/support/solutions/articles/70000628748-how-to-reset-watched-progress).
To make it work with PlexTraktSync, the script should take this `reset_at` date into consideration when reading the watched status of trakt episodes.
After being reset, a show [watched progress](https://trakt.docs.apiary.io/#reference/shows/watched-progress) should be defined as unwatched :
> If not null, the reset_at date is when the user started re-watching the show. Your app can adjust the progress by ignoring episodes with a last_watched_at prior to the reset_at.
This PR adds the `reset_at < last_watched_at` check before returning any trakt episode watched status.
It also marks as unwatched in Plex a show that's been reset in Trakt (only …
=> Use progress reset trakt VIP feature for shows

plextraktsync/commands/watch.py, plextraktsync/media.py, plextraktsync/trakt_api.py, plextraktsync/walker.py
requires :
- ~~https://github.com/moogar0880/PyTrakt/pull/208~~
- https://github.com/glensc/python-pytrakt/pull/6 (v3.4.9)
- #1143
Uses the newly added `show_id` attribute of trakt **TVEpisode** instead of TVShow id found from Plex show guid.
Usefull when a Plex show is split in many Trakt shows.
closes #1111
=> Use trakt.show_id for episodes

plextraktsync/plex_api.py
Remove timezone offset for episode seen_date before comparing to trakt reset_at show date.
https://github.com/Taxel/PlexTraktSync/pull/1140#issuecomment-1292433963
=> plex ep localtime date changed to utc date before comparison with trakt date

.github/ISSUE_TEMPLATE/bug.yml, README.md
There has been an increasing volume of people making reports of installation failure, while they have not fully followed the installation documentation.
This makes it clear that only pipx and docker image are supported. other install methods are just documented as a convience, but without support.
- https://github.com/Taxel/PlexTraktSync/issues/1157
- https://github.com/Taxel/PlexTraktSync/issues/1154
- https://github.com/Taxel/PlexTraktSync/issues/1144
=> Docs: Make clearer note about unsupported install methods

.github/ISSUE_TEMPLATE/config.yml
Docs:
- https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#configuring-the-template-chooser
=> Fix: Disallow creating issues without templates

plextraktsync/commands/bug_report.py, plextraktsync/config.py
The bug-report command now also passes users' `config.yml`:
```
plextraktsync bug-report
```
Requires:
- https://github.com/Taxel/PlexTraktSync/pull/1164
=> Feature: Pass config yaml to bugreport command

plextraktsync/util/openurl.py
```
✖  docker-compose run --rm plextraktsync bug-report
Opening bug report URL in browser, if that doesn't work open the link manually:
https://github.com/Taxel/PlexTraktSync/issues/new?template=bug.yml*redacted*
Traceback (most recent call last):
File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
exec(code, run_globals)
File "/app/plextraktsync/__main__.py", line 18, in <module>
cli()
File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
return self.main(*args, **kwargs)
File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
rv = self.invoke(ctx)
File …
```
=> Fix bug-report subcommand on linux

plextraktsync/commands/sync.py, plextraktsync/factory.py, plextraktsync/sync.py, plextraktsync/trakt_api.py
Increases readability (at least for me), lazy access for building lists. It's still a mess of responsibilities of classes, but at least properties aren't initialized inconsistent way. i.e need to run the `sync() method to gain access to some class properties.
For example this is still a mess:
```py
runner: Sync = factory.sync()
if runner.config.need_library_walk:
w.print_plan(print=logger.info)
```
=> Refactor to use SyncConfig

plextraktsync/plex_api.py, plextraktsync/sync.py, plextraktsync/trakt_list_util.py
Fixes https://github.com/Taxel/PlexTraktSync/issues/124
This allows you edit Plex lists, add them description:
- https://github.com/pkkid/python-plexapi/issues/1054
and it will be preserved as long as you keep the name intact.
Playlist contents is still cleared with each update to supply order by PTS.
it would be overly complicated to do compare and run only three available methods:
- addItems
- deleteItems
- reorderItems
besides, reorder items can take only one item a time, so lots of api calls
=> Refactor: Update Plex playlists not delete+create

plextraktsync/sync.py
PR for Feature request: Allow syncing of Liked Lists without needing Watchlist sync.
Resolves #1182
=> Allow liked lists to sync without watchlist sync

.pre-commit-config.yaml
It can't preserve comments,
so very annoying to revert the changes all the time..
refs:
- https://github.com/Taxel/PlexTraktSync/commit/271a993a0d8489eebc86f6fa5380eb5ec0c85230 (added here)
discussions:
- https://github.com/asottile/setup-cfg-fmt/issues/44
- https://github.com/asottile/setup-cfg-fmt/pull/21
- https://github.com/asottile/setup-cfg-fmt/issues/25
=> Fix: Remove setup-cfg-fmt pre-commit hook

plextraktsync/plex_api.py, plextraktsync/trakt_list_util.py
Enables handling of a watchlist which has no items in common with the Plex library.
Also fixes an issue where [creating a new playlist would give a BadRequest exception.](https://github.com/Taxel/PlexTraktSync/pull/1183#discussion_r1018872371)
=> Handle syncing empty watchlist or playlist

plextraktsync/plex_api.py
Plex uses file date to set the `addedAt` value of a media.
Some media managers (such as Radarr/Sonarr) have an option to automatically set file date to release date.
But some OS cannot handle very old dates (eg. [Windows](https://www.reddit.com/r/radarr/comments/qr3jbj/trigger_write_release_dates_to_files_many_have/) dates before 1970) so the file date cannot be written on file system by such media manager.
Therefore Plex cannot populate the `addedAt` value.
This PR allows None value for `addedAt` instead of crashing.
None value is accepted by trakt, it is understood as current datetime.
closes #1189
closes #949
=> allow None as date value

plextraktsync/sync.py, plextraktsync/trakt_api.py, plextraktsync/trakt_list_util.py
With this PR, the script handles trakt lists with their id instead of there creator name.
This allows to use user lists and official lists with the same function.
Official lists are not identical to user lists because they are not created bu users and cannot be called with `/users/(user)/lists/(list)`
Ideally, the pytrakt module would add official lists support.
=> Add trakt official lists support

plextraktsync/sync.py
Issue : if you wanted to sync both `liked lists` and `watchlist`, the watchlist would never sync (because of a `else` logic).
This PR fix this issue.
Also uses only one log line for each playlist update.
Tested successfully.
=> Fix watchlist update logic

plextraktsync/timer.py, plextraktsync/trakt_api.py
Remove a call to `submit()` if there's nothing to submit.
```
➜ grep -F 'Sleeping for' plextraktsync.log
2022-11-14 19:52:31,535 DEBUG[PlexTraktSync]:Sleeping for 1.100 seconds
2022-11-14 19:52:32,639 DEBUG[PlexTraktSync]:Sleeping for 1.100 seconds
2022-11-14 19:52:33,742 DEBUG[PlexTraktSync]:Sleeping for 1.100 seconds
2022-11-14 19:52:34,845 DEBUG[PlexTraktSync]:Sleeping for 1.100 seconds
2022-11-14 19:52:35,949 DEBUG[PlexTraktSync]:Sleeping for 1.100 seconds
2022-11-14 19:52:37,053 DEBUG[PlexTraktSync]:Sleeping for 1.100 seconds
2022-11-14 19:52:38,156 DEBUG[PlexTraktSync]:Sleeping for 1.100 seconds
2022-11-14 19:52:40,892 DEBUG[PlexTraktSync]:Sleeping for 1.100 seconds
2022-11-14 19:52:41,993 DEBUG[PlexTraktSync]:Sleeping for 1.100 seconds
2022-11-14 19:52:43,097 …
```
=> Fix 10x 1.1s second delay end of the sync

.gitignore, plextraktsync/commands/plex_login.py, plextraktsync/config/Config.py, plextraktsync/config/PlexServerConfig.py, plextraktsync/config/ServerConfig.py, plextraktsync/factory.py, plextraktsync/path.py, plextraktsync/plex_server.py, plextraktsync/servers.default.yml
Allow easy switching between multiple Plex servers.
This moves servers definition to `servers.yml` file:
```yml
servers:
default:
token: ~
urls:
- http://localhost:32400
```
in `.env`:
```sh
PLEX_SERVER=default
```
`urls` can be an unlimited amount of urls to try.
`plex-login` command can be used to add new servers, it will add/update servers.yml and update `PLEX_SERVER` in `.env`.
Future ideas:
- allow specify server via commandline by name
- walk multiple servers
- per server config overrides
=> Feature: Add multiple servers support

plextraktsync/plex_server.py
Fixes exception from https://github.com/Taxel/PlexTraktSync/issues/1198, https://github.com/Taxel/PlexTraktSync/issues/1202
=> Fix: Skip attempting to detect protocol if url is None

setup.cfg
Fixes https://github.com/Taxel/PlexTraktSync/issues/1228
=> Fix: Package servers.default.yml to pip package

plextraktsync/plex_api.py
See details:
- https://github.com/Taxel/PlexTraktSync/issues/815#issuecomment-1331189557
Fixes https://github.com/Taxel/PlexTraktSync/issues/778, Fixes https://github.com/Taxel/PlexTraktSync/issues/815
The queries made to PMS:
- https://*redacted*.plex.direct:32400/library/sections/2/all?includeGuids=1&push=1&show.userRating%3E%3E=-1&pop=1&X-Plex-Container-Start=0&X-Plex-Container-Size=100
- https://*redacted*.plex.direct:32400/library/sections/1/all?includeGuids=1&push=1&userRating%3E%3E=-1&pop=1&X-Plex-Container-Start=0&X-Plex-Container-Size=100
note the keys differ: `show.userRating` for episodes and `userRating` for movies.
=> Fix: Disable bulk rating fetch for shows

plextraktsync/media.py, plextraktsync/plex_api.py
Implement:
- https://github.com/Taxel/PlexTraktSync/pull/1239#issuecomment-1331285446
Fetches show ratings for episodes, as the `episode.userRating` filter will return shows that have ratings. So skip episodes that are not in that list. For episodes whose show is in the list, every item will be reloaded by python-plexapi:
```
2022-11-29 23:38:32,531 DEBUG[plexapi]:Reloading Episode 'Bla Bla' for attr 'userRating'
```
so shows having just one episode with userRating will be still slow.
=> Fetch show ratings for episodes

.dockerignore, plextraktsync/plex/PlexRatings.py, plextraktsync/plex_api.py, setup.cfg
Improve https://github.com/Taxel/PlexTraktSync/pull/1242, shows ratings were not working.
Add PlexRatings class dealing with ratings. There's too much logic spewed around multiple places it's difficult to follow the logic anymore.
=> Refactor Plex ratings logic into PlexRatings class

.dockerignore, Dockerfile, README.md, entrypoint.sh
Match the LinuxServer images behavior:
- https://github.com/linuxserver-labs/docker-plextraktsync
```yaml
services:
plextraktsync:
image: ghcr.io/taxel/plextraktsync
container_name: plextraktsync
restart: on-failure:2
volumes:
- ./config:/app/config
environment:
- PUID=1000
- PGID=1000
- TZ=Europe/Tallinn
```
- If `PUID`/`PGID` are specified, in container uid/gid is changed, files are changed to plextraktsync user recursively in config dir and script is continuing with plextraktsync user.
- Without specifying `PUID`/`PGID`, container continues to run as `root`. no file permissions are changed
- if `--user` is specified, no permissions are changed and process continues to run as that user.
=> Feature: Add PUID/PGID support to docker image

plextraktsync/trakt_api.py, tests/test_batch.py
This fixes that on first call to batch() 1-size batch is sent out immediately without the time delay.
This came out when fixing `tests/test_batch.py` after changes from https://github.com/Taxel/PlexTraktSync/pull/869
=> Fix TraktBatch not to send out batch immediately

plextraktsync/factory.py, plextraktsync/trakt_api.py, tests/test_batch.py
Reduce code duplication when creating TraktBatch instances.
=> Refactor: Use trakt_batch factory to create TraktBatch

README.md, plextraktsync/cli.py
```
$ plextraktsync
WARNING  plextraktsync without command is deprecated. Executing "plextraktsync sync"
```
The technical reason for dropping support is because supporting it makes difficult to implement a cleanup handler for two commands (main and subcommand). Implementing Exception handler is already quite hackish:
- https://click.palletsprojects.com/en/8.1.x/exceptions/
Fixes: https://github.com/Taxel/PlexTraktSync/issues/780
=> Deprecate usage without command name

plextraktsync/commands/config.py, plextraktsync/config.default.yml, plextraktsync/config/Config.py, plextraktsync/config/HttpCacheConfig.py, plextraktsync/factory.py, plextraktsync/trakt/TraktApi.py, plextraktsync/trakt/TraktBatch.py, plextraktsync/trakt/TraktLookup.py
Replaces https://github.com/Taxel/PlexTraktSync/pull/1220
Removes `@nocache` annotation and moves them to be setup via rules:
```yml
http_cache:
#
policy:
"*.trakt.tv/shows/*/seasons": 0
"*.trakt.tv/sync/collection/shows": 0
"*.trakt.tv/sync/watched/shows": 0
"*.trakt.tv/users/*/collection/movies": 0
"*.trakt.tv/users/*/collection/shows": 0
"*.trakt.tv/users/*/ratings/*": 0
"*.trakt.tv/users/*/watched/movies": 0
"*.trakt.tv/users/*/watchlist/movies": 0
"*.trakt.tv/users/*/watchlist/shows": 0
"*.trakt.tv/users/likes/lists": 0
"*.trakt.tv/users/me": 0
```
This allows to setup rule to cache some watchlist forever.
In the future could add default cache key (removed from this branch for now):
```yml
http_cache:
default_expire_after: 1 hour
```
=> Refactor: Setup url cache for trakt.tv by patterns

plextraktsync/config/Config.py, tests/mock_data/http_cache-1-entry.yml, tests/mock_data/http_cache-blank.yml, tests/mock_data/http_cache-empty.yml, tests/test_config.py
Fixing https://github.com/Taxel/PlexTraktSync/pull/1221
Do not fail if user has config `http_cache` but no entries:
```yml
http_cache:
```
=> Fix: Handle empty http_cache section

plextraktsync/commands/plex_login.py
Uses [`preferred_connections`](https://github.com/pkkid/python-plexapi/blob/3d3f9da5012428f5d703cf9f8e95f6aa10673ea6/plexapi/myplex.py#L1309-L1314) which describes as:
> Returns a sorted list of the available connection addresses for this resource.
> Often times there is more than one address specified for a server or client.
> Default behavior will prioritize local connections before remote or relay and HTTPS before HTTP.
> 
Writes all urls in order like:
```yml
servers:
default:
urls:
- https://192-168-0-1.5eaf640a56769cf3a72fd93ac9711e40.plex.direct:32400
- http://192.168.0.1:32400
- https://8-8-8-8.5eaf640a56769cf3a72fd93ac9711e40.plex.direct:12521
- http://8.8.8.8:12521
- http://localhost:32400
```
=> Feature: Save all urls to config from plex-login

plextraktsync/cli.py, plextraktsync/commands/sync.py
New global options:
- `plextraktsync --no-progressbar`
- `plextraktsync --batch-delay`
- `plextraktsync --server`
The `sync` command options are deprecated:
- `plextraktsync sync --no-progress-bar`
- `plextraktsync sync --batch-delay`
- `plextraktsync sync --server`
=> Refactor: Move sync options to global that are global options

plextraktsync/__main__.py, plextraktsync/trakt/TraktBatch.py, setup.cfg
Looks like we can use builtin `atexit` for shutdown handlers:
- https://docs.python.org/3/library/atexit.html#module-atexit
So the code from this PR is not really needed:
- https://github.com/Taxel/PlexTraktSync/pull/1269
=> Refactor: Use atexit for shutdown handlers

plextraktsync/config/HttpCacheConfig.py, plextraktsync/plex/PlexApi.py, plextraktsync/plex/PlexLibraryItem.py, plextraktsync/plex/PlexLibrarySection.py
Continue https://github.com/Taxel/PlexTraktSync/pull/1221, but for plex urls.
```sh
git grep --function-context -C2 @nocache
```
Docs:
- https://requests-cache.readthedocs.io/en/stable/user_guide/expiration.html#url-patterns
=> Refactor: Add plex cache policy patterns

.github/ISSUE_TEMPLATE/bug.yml
So users can fill the issue without lying about it.
Problem: Users check the box just. to get the issue going, but they really didn't do any downgrade attempts:
- https://github.com/Taxel/PlexTraktSync/issues/1314
=> Bugreport: remove required for downgrade checkbox

plextraktsync/sync.py
This is not much useful:
```
INFO     Removing 'Innocence' from Plex watchlist
```
Currently in Plex global search there are 6 movies with that exact title, so which ones were removed?
=> Add year to watchlist add/remove message

plextraktsync/commands/watch.py
Refs:
- https://github.com/Taxel/PlexTraktSync/pull/1324
- https://stackoverflow.com/a/72304083/2314626
=> Reset cursor when watch command is aborted (ctrl+c)

plextraktsync/media.py, plextraktsync/trakt/TraktApi.py
`trakt_api.remove_from_library` from wasn't using queue like the other ones defined in Queue class. Add new `trakt_api.remove_from_collection` method and deprecate `trakt_api.remove_from_library`
Refs:
- https://github.com/Taxel/PlexTraktSync/pull/1326#issuecomment-1367557046
=> Feature: Add TraktApi.remove_from_collection method

plextraktsync/commands/clear_collections.py
<del>
Updates code to use `TraktBatch`, so API requests to Trakt are sent in 5s batches. Old code sends each removal as a single request.
</del>
----
Update to use `trakt.remove_from_collection(movie)` rather deprecated `trakt.remove_from_library(movie)`.
Enable debug logging and see the `plextraktsync.log` what requests are made.
Refs:
- https://github.com/Taxel/PlexTraktSync/issues/374
=> Use TraktBatch in clear_collections

plextraktsync/cli.py, plextraktsync/commands/sync.py, plextraktsync/sync.py, plextraktsync/walker.py
Allows syncing only watchlist:
```
$ plextraktsync sync --sync=watchlist
```
does not work when `watchlist_as_playlist` is enabled.
syncing plain watchlist, does not need to walk through libraries, so can work fine in partial mode or no library walk mode at all.
=> Feature: Add --sync=watchlist option

plextraktsync/plex/PlexApi.py
We do not check user fields from watchlist entries, so allow it to be cached
This allows caching reloads:
```
WARNING  Reloading Movie 'Big Bad Bugs' for attr 'guids'
```
=> Skip user state for watchlist items

plextraktsync/config.default.yml, plextraktsync/factory.py, plextraktsync/logger/filter.py
This turns off all logs for typical "sync" command run :)
```yml
filter_loggers:
- plexapi
- requests_cache.backends
- requests_cache.backends.base
- requests_cache.backends.sqlite
- requests_cache.policy.actions
- requests_cache.session
- trakt.core
- urllib3.connectionpool
filter:
- name: PlexTraktSync
- name: PlexTraktSync.PlexServerConnection
- name: plexapi
- name: requests_cache.backends
- name: requests_cache.backends.base
- name: requests_cache.backends.sqlite
- name: requests_cache.policy.actions
- name: trakt.core
- name: urllib3.connectionpool
```
=> Feature: Allow filtering logs by name

.dockerignore, Dockerfile
Just an experiment, to install from pre-downloaded wheels. More efficient layer caching for local dev.
Spun off from branch trying to build wheel of strototime in separate target.
refs:
- https://github.com/pypa/pipenv/issues/1105
=> Docker: Download and pre-build wheels

plextraktsync/media.py, plextraktsync/sync.py
_Extracted from https://github.com/Taxel/PlexTraktSync/pull/1338_
add `{m.title}` and use it as `{m}` is too perhaps not much readable for typical messages. `{m}` could be still used for errors.
=> Feature: Add title property to media

plextraktsync/commands/cache.py, plextraktsync/commands/clear_collections.py, plextraktsync/commands/config.py, plextraktsync/commands/imdb_import.py, plextraktsync/commands/inspect.py, plextraktsync/commands/login.py, plextraktsync/commands/plex_login.py, plextraktsync/commands/self_update.py, plextraktsync/commands/sync.py, plextraktsync/commands/trakt_login.py, plextraktsync/commands/unmatched.py, plextraktsync/commands/watch.py, plextraktsync/commands/watched_shows.py, plextraktsync/console.py, plextraktsync/factory.py
Remove uses of `click.echo`, Replace uses with Rich `print`. We don't need Python 2 wrappers, and print from Rich does extra coloring, which is nice.
=> Cleanup: Unify use of print

plextraktsync/commands/watch.py, plextraktsync/config.default.yml
Add an option to turn it off. It corrupts tmux session on Debian 10, so it's rather annoying as it also makes scrolling also useless.
```yaml
watch:
media_progressbar: true
```
=> Feature: Add config for media_progressbar

plextraktsync/commands/cache.py
This allows output to be grep'ed:
- https://github.com/Taxel/PlexTraktSync/pull/1362#issuecomment-1382912340
=> Fix: Skip wrapping cache output

plextraktsync/commands/info.py, plextraktsync/plex/PlexApi.py, plextraktsync/walker.py
Similarly to https://github.com/Taxel/PlexTraktSync/pull/1354
=> UX: Print titles in print_plan

Pipfile, Pipfile.lock, requirements.txt
This should generate more stable Pipfile.lock. But might not, dependabot is full of surprises.
Refs:
- https://github.com/dependabot/dependabot-core/issues/6200
- https://github.com/pypa/pipenv/issues/5569
=> Set python_versions in Pipfile

plextraktsync/commands/clear_collections.py, plextraktsync/config.default.yml, plextraktsync/sync.py, plextraktsync/trakt/trakt_set.py
Implementation for:
- https://github.com/Taxel/PlexTraktSync/issues/374#issuecomment-1380076905
```yml
sync:
plex_to_trakt:
collection: true
clear_collected: true
```
This configuration enables deletion of movies from Trakt that are no longer present in Plex.
Must do full collection sync for this to be applied:
```
plextraktsync sync
```
Shows (or episodes) not implemented yet:
- https://github.com/Taxel/PlexTraktSync/issues/374#issuecomment-1382904372
=> Feature: Add sync.plex_to_trakt.clear_collected config (for Movies only)

plextraktsync/plex/PlexApi.py
It doesn't currently change the result, but better fetch less info.
_Extracted from https://github.com/Taxel/PlexTraktSync/pull/1360_
=> Feature: Disable includeCollections, includeExternalMedia for plex watchlist

Pipfile, Pipfile.lock, README.md, plextraktsync/util/Path.py, requirements.txt
It seems that the community is moving past `appdirs` and that a more maintained fork has appeared: `platformdirs`.
This becomes relevant when requests cache is updated to <del>0.10</del> 1.0.0:
- https://github.com/reclosedev/requests-cache/issues/563
Currently `appdirs` dependency is still in `Pipfile.lock` because of `requests-cache`.
Ref:
- https://github.com/ActiveState/appdirs/issues/79
- https://github.com/ActiveState/appdirs/issues/170
- https://platformdirs.readthedocs.io/en/latest/changelog.html
=> Replace appdirs with platformdirs dependency

plextraktsync/commands/plex_login.py
inquirer.rawlist can't do more than 9 entries:
- https://github.com/kazhala/InquirerPy/blob/714d9068896c1a1f9f4d1354f43f922cd5cfe16d/InquirerPy/prompts/rawlist.py#L268-L269
Fixes https://github.com/Taxel/PlexTraktSync/issues/1397
=> Switch back to inquirer.select

plextraktsync/watch/WatchStateUpdater.py
You may log in with email,  then filter username will go wrong.
NOTE: This may need `PLEX_OWNER_TOKEN` or `PLEX_ACCOUNT_TOKEN`, depending on setup. They may need to re-login for these to appear in `.env`
=> Fix: Ensure username_filter gets username regardless what PLEX_USERNAME has

plextraktsync/commands/inspect.py, plextraktsync/plex/PlexLibraryItem.py
If not enough access to server, the markers attribute is missing.
=> Fix AttributeError on inspect with no access to markers

plextraktsync/commands/inspect.py, plextraktsync/plex/PlexLibraryItem.py
Extracted from #1437 
By default, plex item data is fully loaded from PMS if a requested attribute has value `None`.
`editionTitle` is an attribute printed out during sync and is almost always `None` for average movies.
This PR creates `edition_title` property (e.g.: director's cut, extended, special edition,...) for `PlexLibraryItem` without reloading data from Plex server.
refs:
- https://github.com/pkkid/python-plexapi/pull/1093
- https://support.plex.tv/articles/multiple-editions/
fixes #1436
=> Set edition_title property without reloading Plex data

plextraktsync/cli.py, plextraktsync/commands/download.py
When downloading from PMS that is on Windows, media file is saved with absolute path looking like `E:\Movies\Movie.avi`.
`plex.download()` is able to remove directory part of the filename on Unix to Unix server, but not Windows to Unix, so we have to do basename for windows files.
Also adds `--target` option to save files to, it suppots tilde expansion (`~`) as `$HOME`.
```
$ plextraktsync download --help
Usage: python -m plextraktsync download [OPTIONS] [INPUT]...
Downloads movie or subtitles to a local directory
Options:
--only_subs    Download only subtitles
--target TEXT  Download directory  [default: .]
--help         Show this message and exit.
```
=> Fix: Use basename when downloading

plextraktsync/config/HttpCacheConfig.py, plextraktsync/util/Factory.py
Cache for some time, this activates 304 responses, need some cache value to be able to compare and make conditional requests.
Commands to expire existing cache (Not needed as previously these were not cached at all). Replace `*` with your trakt account.
```sh
plextraktsync cache --expire https://plex.tv/users/account
plextraktsync cache --expire https://api-v2launch.trakt.tv/sync/collection/shows
plextraktsync cache --expire https://api-v2launch.trakt.tv/sync/watched/shows
plextraktsync cache --expire https://api-v2launch.trakt.tv/users/*/collection/movies
plextraktsync cache --expire https://api-v2launch.trakt.tv/users/*/ratings/episodes
plextraktsync cache --expire https://api-v2launch.trakt.tv/users/*/ratings/movies
plextraktsync cache --expire …
```
=> Set some cache to responses that can generate 304 response

plextraktsync/media.py, plextraktsync/sync.py
This fixes issues like:
1. titles with aposthrophes continue be colored
2. having title on screen it's difficult to find actual item
now it's clickable links, if terminal supports it.
=> Use rich links when printing titles

entrypoint.sh
This simplifies container access without needing to override with `--entrypoint sh`:
```
$ docker-compose run --rm plextraktsync sh         
~ $ ls -l
total 8
drwxr-xr-x    2 plextrak plextrak       120 Apr 19 13:59 config
drwxr-xr-x   13 root     root          4096 Apr 21 07:00 plextraktsync
-rwxr-xr-x    1 root     root           113 Jan 16 06:27 plextraktsync.sh
~ $
```
=> Add "sh" command to docker compose to passthrough to shell

Dockerfile, entrypoint.sh
Inspired by https://github.com/Taxel/PlexTraktSync/pull/1464
```
$ docker-compose run --rm plextraktsync pipx
* Installing git
fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/community/x86_64/APKINDEX.tar.gz
(1/5) Installing brotli-libs (1.0.9-r6)
(2/5) Installing nghttp2-libs (1.47.0-r0)
(3/5) Installing libcurl (8.0.1-r0)
(4/5) Installing pcre2 (10.40-r0)
(5/5) Installing git (2.36.5-r0)
Executing busybox-1.35.0-r17.trigger
OK: 27 MiB in 41 packages
* Installing pipx
Defaulting to user installation because normal site-packages is not writeable
Collecting pipx
Downloading pipx-1.2.0-py3-none-any.whl (57 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.8/57.8 kB 2.3 MB/s eta 0:00:00
Collecting …
```
=> Feature: Add pipx docker compose alias to prepare pipx in container

plextraktsync/media.py
Fixes https://github.com/Taxel/PlexTraktSync/issues/1462
=> Skip link for media if no plex (only trakt)

plextraktsync/logging.py
Removes rich markups __link__ and __green__ (used for titles) in logfile (keep them in console log) because it makes logfile unreadable.
Feature added in #1447 version `0.26.1`
Logfile before this PR:
```
2023-05-12 04:20:11,431 INFO[PlexTraktSync]:Sync Show sections: ['[link=https꞉//app.plex.tv/desktop/#!/media/3f48753c4e05fda84b1316596945dd36194e4/com.plexapp.plugins.library?source=2][green]TV Shows[/][/]']
2023-05-12 04:21:01,117 INFO[PlexTraktSync]:Marking as watched in Plex: [link=https꞉//app.plex.tv/desktop/#!/server/3f48753c4e05fda84b1316596945dd36194e4/details?key=/library/metadata/5098][green]Breaking Bad/s01e04/Cancer Man (2008)[/][/]
2023-05-12 04:21:23,406 INFO[PlexTraktSync]:[link=https꞉//app.plex.tv/desktop/#!/media/3f48753c4e05fda84b1316596945dd36194e4/com.plexapp.plugins.li …
```
=> CustomFormatter to remove rich markup in logfile

plextraktsync/config.default.yml, plextraktsync/sync.py
Fix for issue: https://github.com/Taxel/PlexTraktSync/issues/1489. Pull request adds support for optional rating priority config setting. Includes modifications for rating sync logic in `sync.py` and a new setting for `rating_priority` in `config.default.yml`.
Valid values for rating_priority are trakt, plex or none. (default: none)
- none - No rating priority. Existing ratings are not overwritten.
- trakt - Trakt ratings have priority. Existing Plex ratings are overwritten.
- plex - Plex ratings have priority. Existing Trakt ratings are overwritten.
Previously, if there was an existing rating for an item in Plex AND Trakt, the Plex rating would take precedence and the Trakt rating would be overwritten. 
I have thoroughly tested these changes and have found no conflicts or errors. …
=> Feature: Add support for optional rating priority config setting (none, trakt, or plex)

plextraktsync/plex/PlexLibrarySection.py
This is to avoid `section.fetchItems` returning already visited items
Refs:
- https://github.com/Taxel/PlexTraktSync/pull/1506#issuecomment-1605918667
- https://github.com/pkkid/python-plexapi/pull/1143#issuecomment-1605918687
=> Fix: Pass maxresults to section.fetchItems

plextraktsync/config/HttpCacheConfig.py, plextraktsync/plex/PlexLibraryItem.py
Fetch episodes using library search to include guids without reloading every episode object. This should *significantly* increase the speed for syncing tv shows.
Please delete options that are not relevant.
=> Fetch episodes using library search to include guids without reloading

.github/workflows/lint.yml, .github/workflows/pypi.yml, .github/workflows/test.yml, Pipfile, Pipfile.lock, README.md, plextraktsync/commands/imdb_import.py, plextraktsync/config/SyncConfig.py, plextraktsync/decorators/cached_property.py, plextraktsync/logger/filter.py, plextraktsync/media.py, plextraktsync/mixin/SetWindowTitle.py, plextraktsync/plex/PlexApi.py, plextraktsync/plex/PlexAudioCodec.py, plextraktsync/plex/PlexGuid.py, plextraktsync/plex/PlexLibraryItem.py, plextraktsync/plex/PlexWatchList.py, plextraktsync/sync.py, plextraktsync/trakt/TraktApi.py, plextraktsync/trakt/TraktItem.py, plextraktsync/trakt/TraktLookup.py, plextraktsync/trakt/TraktWatchlist.py, plextraktsync/util/Factory.py, plextraktsync/util/Path.py, plextraktsync/util/Version.py, plextraktsync/walker.py, plextraktsync/watch/ProgressBar.py, plextraktsync/watch/WatchStateUpdater.py, requirements.txt, setup.cfg
Not to be merged before 27 Jun 2023:
- https://endoflife.date/python
Version | Released | Security Support | Release
-- | -- | -- | --
3.7 | 3 years and 7 months ago(27 Jun 2018) | Ends in 1 year and 4 months(27 Jun 2023) | 3.7.12
=> Cleanup: Drop Python 3.7 support (EOL)

Pipfile, Pipfile.lock, README.md, plextraktsync/cli.py, requirements.txt
Adds new subcommand `tui` to add nice text browser or all commands.
https://github.com/Textualize/trogon#custom-command-name-and-custom-help
requires python 3.8:
- https://github.com/Taxel/PlexTraktSync/pull/773
or we lack python 3.11 support:
- https://github.com/executablebooks/mdit-py-plugins/blob/v0.4.0/CHANGELOG.md#040---2023-06-05
=> Feature: Enable trogon tui for cli

Dockerfile
Apparently there's wheel now for x86_64:
> PyYAML-6.0.1-cp311-cp311-musllinux_1_1_x86_64.whl
- https://github.com/Taxel/PlexTraktSync/actions/runs/6037364156/job/16381489172?pr=1564#step:8:540
=> Build missing wheels only if needed

plextraktsync/config/Config.py, plextraktsync/config/PlexServerConfig.py, plextraktsync/config/SyncConfig.py, plextraktsync/sync.py, plextraktsync/util/Factory.py
Currently only "sync" command reads "sync" settings.
```yml
servers:
default:
id: xxx
token: xxx
urls:
- https://xxx.plex.direct:32400
config:
sync:
plex_to_trakt:
collection: true
trakt_to_plex:
liked_lists: false
```
=> Feature: Add config support for servers.yml

plextraktsync/logging.py
Extracted from https://github.com/Taxel/PlexTraktSync/pull/716
=> Fix: Force logging.basicConfig to logging to work in pytest

README.md, plextraktsync/commands/plex_login.py
This should fix login for Plex users using 2FA.
Closes #1584 
TODO:
=> Fix Plex login for users with 2FA enabled

plextraktsync/plex/PlexRatings.py
Using only `item.ratingKey`, `item.userRating` fields really.
=> Optimize: Disable includeGuids for ratings search

plextraktsync/plex/PlexApi.py
No need to memoize them, they are plain property accesses.
=> Performance: Use plain property for plex api .version, .updated_at

plextraktsync/logger/init.py, plextraktsync/util/Factory.py
This is to avoid confusing the import of the system and a local module.
_Extracted from https://github.com/Taxel/PlexTraktSync/pull/1654_
=> Refactor: Move logging out of root import

plextraktsync/media.py
This mitigates the problem with fetching `index=None` from plex api
See:
- https://github.com/Taxel/PlexTraktSync/issues/1631
=> Fix: Skip dumping guid.pm.item on unmatched items

plextraktsync/trakt/TraktApi.py
Quite typical to put mini-series as movie to the library, as plex recognizes both. but trakt only has them as tv series.
If the match is not found,  try a tv series and print warning if found, so users would know to fix this.
=> Feature: Retry movie search for mini series

plextraktsync/trakt/TraktApi.py
There's such item in media library
```
Guids:
Guid: <PlexGuid:tmdb://1123257>, Id: 1123257, Provider: 'tmdb'
Guid: <PlexGuid:tvdb://346000>, Id: 346000, Provider: 'tvdb'
Guid: <PlexGuid:imdb://tt27430909>, Id: tt27430909, Provider: 'imdb'
```
and it behaves really oddly.
later it appeared the tmdb id is deleted, new id is 1201008
```
Guids:
Guid: <PlexGuid:tmdb://1201008>, Id: 1201008, Provider: 'tmdb'
Guid: <PlexGuid:tvdb://346000>, Id: 346000, Provider: 'tvdb'
Guid: <PlexGuid:imdb://tt27430909>, Id: tt27430909, Provider: 'imdb'
```
but having no match in tvdb, it was confusing why tvdb wasn't consulted. no request made, nothing in logs.
so now at least prepping logs for 346000 will give some match.
while the site has the id present:
- https://thetvdb.com/movies/louis-ck-at-the-dolby …
=> Improve tvdb does not support movie provider debug message

CONTRIBUTING.md
Updates trakt baseurl because old one is deprecated.
According to [Trakt API](https://twitter.com/traktapi/status/1742976564567106019) :
> The API host name [http://api-v2launch.trakt.tv](https://t.co/9TYHCeYzjb) will be removed on February 1. 
>
>This has been deprecated since 2017. This will only affect very old apps and they need to use [http://api.trakt.tv](https://t.co/0mENbHo7Uq) to continue working beyond February 1.
=> Update trakt baseurl

.github/workflows/pypi.yml
Taking from pipx:
- https://github.com/pypa/pipx/blob/81c2fa509768715de24a3ba10d46596de980052f/.github/workflows/tests.yml#L91-L93
Should appear something like this:
- https://github.com/pypa/pipx/deployments/release
=> CI: Add release environment for pypi job

plextraktsync/commands/inspect.py, plextraktsync/plex/PlexApi.py
1. did not parse url well
2. history results exception
```
$ plextraktsync inspect "https://app.plex.tv/desktop/#!/provider/tv.plex.provider.discover/details?key=/library/metadata/5d7769ed9ab54400214f8ad9"
```
=> Fix: Make inspect work for discover urls

plextraktsync/plex/PlexApi.py, plextraktsync/util/Factory.py, plextraktsync/watch/WatchStateUpdater.py
Less confusion, and duplicate plex.plex typing
=> Refactor: Rename plex property to server in PlexApi class

trakt-api.sh
This default assignment may cause DoS due to globbing. Quote it.
See SC2223:
- https://github.com/koalaman/shellcheck/wiki/SC2223
=> Fix trakt-api.sh shellcheck SC2223 warning

README.md, plextraktsync/config.default.yml, plextraktsync/config/PlexServerConfig.py, plextraktsync/plex/PlexApi.py
Requires:
allows configuring per server libraries:
1. "libraries" -> use only these libraries. global "excluded-libraries" will be ignored if this is set
2. "exclude-libraries" -> per server libraries to exclude
example 1: process only libraries "Movies" and "TV Shows"
```yml
Example1:
token: ~
urls:
- http://localhost:32400
config:
libraries:
- "Movies"
- "TV Shows"
```
example 2: exclude "Family Movies" library for specific server only
```yml
Example1:
token: ~
urls:
- http://localhost:32400
config:
excluded-libraries:
- "Family Movies"
```
you can see the final list of libraries with `info` command:
```
$ plextraktsync  --server=Example1 info  
INFO     Enabled 2 libraries in Plex Server: ['Movies', 'TV Shows']           
```
=> Feature: Add library config to server config

plextraktsync/plan/Walker.py, plextraktsync/rich/RichProgressBar.py, plextraktsync/util/Factory.py
Get rid of tqdm rich wrapper.
Needed for:
- https://github.com/Taxel/PlexTraktSync/pull/563
and tqdm upstream unresponsive:
- https://github.com/tqdm/tqdm/pull/1395
note: `tqdm` still in use:
1. `from tqdm.rich import FractionColumn, RateColumn`
2. plex downloader
=> Refactor: Use RichProgressBar class

plextraktsync/media.py
The redirect by id may get to incorrect place:
- https://trakt.tv/movies/96
Redirects wrongly:
- https://trakt.tv/movies/96-2018
Should be:
- https://trakt.tv/movies/princess-mononoke-1997
=> Fix: Use trakt slug for trakt_url

plex-api.sh
Similarly to https://github.com/Taxel/PlexTraktSync/pull/1638 add `plex-api.sh` to help debugging plex urls
Expects `PLEX_TOKEN` env variable, or reads itself value from `.env` and `servers.yml`
=> Feature: Add plex-api.sh helper script

plextraktsync/plan/Walker.py, plextraktsync/rich/RichProgressBar.py
```
TypeError: RichProgressBar.__init__() missing 1 required positional argument: 'total'
```
=> Fix: Calculate RichProgressBar length automatically

plextraktsync/watch/ProgressBar.py
This is to solve terminal quirks that on some terminal unicode play/pause characters render with different width:
- https://github.com/Textualize/rich/issues/3254
Fixes issue with Kitty, renders fine with iTerm2 as well
=> Fix: Fix watch play/pause icon display for Kitty terminal

plextraktsync/trakt/TraktRatingCollection.py
This reverts commit 13237f8784d754b5162224ca3b9f18cfa09979fe.
Revert, because it breaks Python 3.8
Fixes #1723
=> Revert "Add implicit typing for TraktRatingCollection"

plextraktsync/media.py, plextraktsync/plan/Walker.py, plextraktsync/plex/PlexLibraryItem.py, plextraktsync/plex/PlexLibrarySection.py, plextraktsync/plex/PlexShowSectionPager.py, plextraktsync/trakt/TraktApi.py
Implement shows sync using episodes search:
- https://github.com/Taxel/PlexTraktSync/issues/976#issuecomment-1648004190
<del>Requires support from PlexApi side: - https://github.com/pkkid/python-plexapi/pull/1243</del>
=> Refactor: Implement shows sync using episodes

plextraktsync/plex/PlexShowSectionPager.py
Does not seem to be having any effect. but since default is True override with False.
=> Skip collections from PlexShowSectionPager

plextraktsync/plex/PlexLibraryItem.py
Fixes https://github.com/Taxel/PlexTraktSync/issues/1740
Refs:
- https://docs.python.org/3/faq/programming.html#faq-cache-method-calls
- https://stackoverflow.com/questions/7027199/hashing-arrays-in-python
=> Fix: Add hash definition to PlexLibraryItem

plextraktsync/commands/inspect.py
Filename may contain text in brackets: `[text]`, that would be hidden by rich.
=> Fix: Escape filename in inspect

plextraktsync/plan/Walker.py, plextraktsync/plex/PlexLibrarySection.py, plextraktsync/plex/PlexSectionPager.py, plextraktsync/rich/RichProgressBar.py
`PlexSectionPager` can now page all library types
Requires:
- https://github.com/Taxel/PlexTraktSync/pull/1736
This should have been cleaned up after:
- https://github.com/Taxel/PlexTraktSync/pull/1578
=> Refactor: Rename PlexShowSectionPager to PlexSectionPager

plextraktsync/media/MediaFactory.py, plextraktsync/plex/PlexGuid.py, plextraktsync/plex/PlexLibraryItem.py
The refactor checks provider only once for providers that exist, possible micro performance boost. For unmatched more checks are performed. Previously all checks were performed regardless if the result will fail. It also improves readability of the resolve_guid method and moves logic of deciding which provider is what to PlexGuid class for enculapsing logic there.
Requires:
=> Refactor: Optimize resolve_guid to check only once positive providers

plextraktsync/commands/inspect.py, plextraktsync/watch/WatchStateUpdater.py
Some media may be without video (audio files).
TODO: Rename symbols internally. Note Plex already renamed to `isPlayed`:
- https://github.com/Taxel/PlexTraktSync/pull/1017
=> Rename Watched to Played

plextraktsync/queue/Queue.py, plextraktsync/queue/TraktScrobbleWorker.py, plextraktsync/trakt/ScrobblerProxy.py, plextraktsync/util/Factory.py
Moves trakt scrobble api calls to worker. This offloads synchronous requests to background task, making main watch command more responsive. 
It will also aggregate results to update same media object, to submit only latest update for same id: 
```
trakt_id=1, percent=1.11
trakt_id=1, percent=1.23
trakt_id=1, percent=1.40
trakt_id=2, percent=19
```
will become:
```
trakt_id=1, percent=1.40
trakt_id=2, percent=19
```
additionally worker methods respect `@time_limit()`, so methods are not called more often than 1.1 seconds:
- https://github.com/Taxel/PlexTraktSync/blob/ef581d1c05c9f851692b448ada74c1f21e2abe21/plextraktsync/config/__init__.py#L9
=> Refactor: Add TraktScrobbleWorker worker

plextraktsync/commands/trakt_login.py
Improve https://github.com/Taxel/PlexTraktSync/pull/1773, `click.prompt` used `Abort` rather `EOFError`, so it's prompts would not be caught.
Test
```
$ docker-compose run --no-TTY --interactive=false plextraktsync trakt-login
Sign in to Trakt
If you do not have a Trakt client ID and secret:
1 - Open http://trakt.tv/oauth/applications on any computer
2 - Login to your Trakt account
3 - Press the NEW APPLICATION button
4 - Set the NAME field = plex
5 - Set the REDIRECT URL field = urn:ietf:wg:oauth:2.0:oob
6 - Press the SAVE APP button
Please enter your client id: 
Error: Program requested terminal, No terminal is connected: EOF when reading a line
```
```
$ docker-compose run --no-TTY --interactive=false plextraktsync plex-login 
You already have Plex Access Token, do you want to log in …
```
=> Fix: Use Prompt.ask rather click.prompt

plextraktsync/trakt/TraktApi.py
=> Use improved OAuthRefreshException for trakt token refresh errors

plextraktsync/config/HttpCacheConfig.py
No longer need to support old domain:
- https://github.com/Taxel/PlexTraktSync/pull/1686
Requires:
=> Use api.trakt.tv only in HttpCacheConfig

plextraktsync/media/Media.py
Improve logging for https://github.com/Taxel/PlexTraktSync/issues/1785
=> Fix: Raise error when plex_rating needs show but it is missing

plextraktsync/trakt/TraktUserList.py
The self._items would evaluate False if it is an empty array:
- https://github.com/Taxel/PlexTraktSync/issues/1788
=> Fix TraktUserList load check

plextraktsync/media/Media.py, plextraktsync/sync.py
Some shows from TVDB do not exist in TMDB / Trakt database because TVDB sometimes splits a show in multiple shows.
Therefore, those shows cannot be rated separately and cannot be synced to Trakt.
Example :
TMDB has show A with 2 seasons.
TVDB has same show split in show A with 1 season and show B with 1 season.
Ids of show A correspond between TMDB and TVDB, so it can be synced.
Id of show B correspond to nothing in TMDB/Trakt, so it cannot be synced. We have to bypass it.
fixes #1785
=> Bypass show when it doesn't exist in trakt db (ex. in tvdb only)

README.md
- Adds instructions on how to setup configuration per server and per library.
- Adds examples of how to setup configuration per server and per library.
- Adds instructions and examples of how to schedule with ofilia if multiple servers are used.
Fixes https://github.com/Taxel/PlexTraktSync/issues/1808
=> Config added: Per server/library configuration example and instructions.

plextraktsync/media/MediaFactory.py
This helps to figoure out id of failing item before the crash.
=> Feature: Add guid resolve log

plextraktsync/commands/imdb_import.py, plextraktsync/media/Media.py, plextraktsync/plex/PlexLibraryItem.py, plextraktsync/plex/PlexRatings.py, plextraktsync/sync/Sync.py, plextraktsync/trakt/TraktApi.py, plextraktsync/trakt/TraktRatingCollection.py, plextraktsync/util/Rating.py, tests/test_rating.py
Requires:
- https://github.com/glensc/python-pytrakt/pull/41 (pytrakt dependency)
NOTE: Plex does not support setting `rated_at` timestamp, but it provides `lastRatedAt` attribute.
Fixes https://github.com/Taxel/PlexTraktSync/issues/1805
=> Refactor: Add Ratings class to support rated_at

.dockerignore
Sync.py missing in docker container because of `.dockerignore` not updated after 1b58921f34d27920f56c6edb536ab25fd7c7bd58
fixes #1828
=> Add sync/*.py exception in docker ignore

plextraktsync/cli.py, plextraktsync/commands/sync.py, plextraktsync/decorators/measure_time.py, plextraktsync/decorators/rate_limit.py, plextraktsync/decorators/retry.py, plextraktsync/media/MediaFactory.py, plextraktsync/plan/Walker.py, plextraktsync/plex/PlexApi.py, plextraktsync/plex/PlexPlaylist.py, plextraktsync/plex/PlexServerConnection.py, plextraktsync/queue/BackgroundTask.py, plextraktsync/queue/TraktBatchWorker.py, plextraktsync/queue/TraktMarkWatchedWorker.py, plextraktsync/queue/TraktScrobbleWorker.py, plextraktsync/sync/Sync.py, plextraktsync/trakt/ScrobblerProxy.py, plextraktsync/trakt/TraktApi.py, plextraktsync/trakt/TraktLookup.py, plextraktsync/trakt/TraktUserList.py, plextraktsync/trakt/TraktUserListCollection.py, plextraktsync/util/Factory.py, plextraktsync/util/Timer.py, plextraktsync/watch/EventDispatcher.py, plextraktsync/watch/WatchStateUpdater.py, plextraktsync/watch/WebSocketListener.py, tests/test_logger.py
NOTYET: In the future drop also:
```py
logger = factory.logger
```
Also, setup log filters on demand on first access to `logging.getLogger(__name__)`.
=> Refactor: Use named loggers everywhere

plextraktsync/plex/PlexApi.py, plextraktsync/plex/PlexWatchList.py
Fixes https://github.com/Taxel/PlexTraktSync/issues/1836, https://github.com/Taxel/PlexTraktSync/issues/1838
=> Fix: Improve message with no plex account

plextraktsync/plex/PlexGuidProvider.py, plextraktsync/plex/PlexGuidProviderMbid.py, plextraktsync/plex/PlexLibraryItem.py
=> Add PlexGuidProviderMbid provider

plextraktsync/util/Factory.py
_Extracted from https://github.com/Taxel/PlexTraktSync/pull/1312_
=> Extract urls_expire_after factory

plextraktsync/config/HttpCacheConfig.py
Walked all entries in my cache to see if some of them had missing match.
```py
#!/usr/bin/env python
import fnmatch
from glob import glob
from requests_cache import CachedSession, DO_NOT_CACHE
from requests_cache.policy.expiration import _url_match
from plextraktsync.config.HttpCacheConfig import LONG_EXPIRY
from plextraktsync.factory import factory
def get_cache():
session: CachedSession = factory.session
return session.cache.responses
def match_policy(policy, url):
for pattern, v in policy.items():
matching = _url_match(url, pattern)
if matching:
if v == LONG_EXPIRY:
v = "LONG_EXPIRY"
if v == DO_NOT_CACHE:
v = "DO_NOT_CACHE"
return (pattern, v)
return None
def test():
session: CachedSession = factory.session
http_cache = factory.config.http_cache
policy = http_cache.default_policy
for r …
```
=> Update HttpCache rules

plextraktsync/config/Config.py
Keep the written `.env` clean(er).
=> Skip writing legacy env keys to .env

plextraktsync/plex/PlexLibraryItem.py
astimezone() on Windows cannot handle pre-epoch dates (before 1970-01-01) and raises `OSError: [Errno 22] Invalid argument`
- https://github.com/python/cpython/issues/80940
fixes #1873
=> Catch timezone error for pre-epoch added_at on Windows

.pre-commit-config.yaml, .prettierignore
https://github.com/requests-cache/requests-cache/blob/65ff40d6d29422b11c0694132f0ec50f575e5de0/.pre-commit-config.yaml
format commit already in HEAD: https://github.com/Taxel/PlexTraktSync/commit/dcb54fc91fc4d19c237b114252ac98593d45a358
=> Linter: Update pre-commit hooks versions, add prettier

plextraktsync/queue/TraktScrobbleWorker.py
I got same episode recorded as played around every hour because watch was retrying the error.
```
Mar 30 16:09:27 niblus plextraktsync[1680006]: ERROR    Got exception while working on
Mar 30 16:09:27 niblus plextraktsync[1680006]:          <plextraktsync.queue.TraktScrobbleWorker.TraktScrobbleWorker object at
Mar 30 16:09:27 niblus plextraktsync[1680006]:          0x7fff1eebab50>: Conflict - resource already created
Mar 30 16:09:32 niblus plextraktsync[1680006]: ERROR    Got exception while working on
Mar 30 16:09:32 niblus plextraktsync[1680006]:          <plextraktsync.queue.TraktScrobbleWorker.TraktScrobbleWorker object at
Mar 30 16:09:32 niblus plextraktsync[1680006]:          0x7fff1eebab50>: Conflict - resource already created
Mar 30 16:09:37 niblus plextraktsync[1680006]: ERROR …
```
=> Fix: Do not retry conflict errors in scrobble

README.md, plextraktsync/cli.py, plextraktsync/commands/config.py
```
$ plextraktsync config --help
Usage: plextraktsync config [OPTIONS]
Print user config for debugging and bug reports.
Options:
--urls-expire-after  Print urls_expire_after configuration
--edit               Open config file in editor
--locate             Locate config file in file browser
--help               Show this message and exit.
```
=> Feature: Add --edit support to config command

plextraktsync/plex/PlexLibraryItem.py
This method doesn't cause reloads for `None` values, i.e unmatched local items.
=> Performance: Add year property to PlexLibraryItem

plextraktsync/config.default.yml, plextraktsync/config/SyncConfig.py, plextraktsync/media/Media.py, plextraktsync/plex/PlexLibraryItem.py, plextraktsync/sync/WatchProgressPlugin.py, plextraktsync/sync/plugin/SyncPluginManager.py, plextraktsync/trakt/TraktApi.py, plextraktsync/trakt/WatchProgress.py
Add syncing watch progress:
- https://trakt.tv/users/me/progress
- https://trakt.docs.apiary.io/#reference/sync/playback/get-playback-progress
Feature request:
- https://github.com/Taxel/PlexTraktSync/discussions/1885
Features:
NOTE: Use tppm to manage entries at trakt.tv side, i.e. removing 0% items (not sure where same functionality is on trakt.tv site):
- https://sharkykh.github.io/tppm/
Requires:
- https://github.com/Taxel/PlexTraktSync/pull/1891
=> Feature: Add watch progress syncing option

plextraktsync/config/HttpCacheConfig.py, plextraktsync/media/Media.py, plextraktsync/plex/PlexLibraryItem.py, plextraktsync/plex/PlexRatings.py
This will improve performance for episodes sync of shows where at least one episode was rated.
Along with https://github.com/Taxel/PlexTraktSync/pull/1899, this eliminates plex reloads in my libraries sync.
=> Performance: Remove reloads for episode ratings sync

plextraktsync/sync/ClearCollectedPlugin.py, plextraktsync/sync/Sync.py, plextraktsync/sync/plugin/SyncPluginInterface.py, plextraktsync/sync/plugin/SyncPluginManager.py
Disable plugin if it would be not needed, i.e in partial mode disable clear collected plugin.
=> Refactor: Allow plugin to unregister itself

plextraktsync/sync/AddCollectionPlugin.py, plextraktsync/sync/ClearCollectedPlugin.py, plextraktsync/sync/LikedListsPlugin.py, plextraktsync/sync/SyncRatingsPlugin.py, plextraktsync/sync/SyncWatchedPlugin.py, plextraktsync/sync/TraktListsPlugin.py, plextraktsync/sync/WatchListPlugin.py, plextraktsync/sync/WatchProgressPlugin.py, plextraktsync/sync/plugin/SyncPluginInterface.py
Make imports shorter, and also explicit that the same types are used in plugin definitions.
=> Refactor: Import types from SyncPluginInterface

plextraktsync/sync/plugin/SyncPluginManager.py
Loading WatchListPlugin takes time because it's `@cached_propery` methods are all resolved.
=> Feature: Measure plugin load times

plextraktsync/decorators/measure_time.py, plextraktsync/sync/plugin/SyncPluginManager.py
This allows passing logger and level, so that logger name would match caller.
=> Feature: Add support for logger to measure_time

plextraktsync/plan/Walker.py
Extracted from https://github.com/Taxel/PlexTraktSync/pull/563, can't lazy load the show property in from async methods, so need to preload them.
=> Performance: Preload matches for shows

plextraktsync/commands/sync.py
Apparently `inquirer.select().execute()` starts new async loop
and doesn't seems to be a way to pass it a loop.
So we just delay creating async loop in sync command.
Fixes https://github.com/Taxel/PlexTraktSync/issues/1938
=> Fix: Throw sync command out of async

plextraktsync/plan/Walker.py, plextraktsync/sync/AddCollectionPlugin.py, plextraktsync/sync/Sync.py, plextraktsync/sync/SyncRatingsPlugin.py, plextraktsync/sync/SyncWatchedPlugin.py, plextraktsync/sync/WatchProgressPlugin.py
Get started with asyncio:
- https://docs.python.org/3/library/asyncio.html
Add `@coro` decorator to get started:
- https://github.com/pallets/click/issues/85#issuecomment-503464628
Major blocker is missing async for rich:
- https://github.com/Textualize/rich/issues/2480
May be fixed with:
- https://github.com/Taxel/PlexTraktSync/pull/1698
General async reading list:
- https://github.com/python-trio/trio/wiki/Reading-list
=> Refactor: Add asyncio support

.github/workflows/test.yml, tests/test_collection_metadata.py, tests/test_config.py, tests/test_plugin.py, tests/test_trakt_progress.py, tests/test_tv_lookup.py
Run tests in CI, so that required dependency is tested to be installed:
- https://github.com/Taxel/PlexTraktSync/pull/1939
Refs:
- https://stackoverflow.com/questions/38442897/how-do-i-disable-a-test-using-pytest
=> Run pytest in CI

plextraktsync/plex/PlexApi.py, plextraktsync/plex/PlexIdFactory.py, plextraktsync/trakt/TraktApi.py, plextraktsync/trakt/TraktItem.py
Example:
```
plextraktsync inspect https://trakt.tv/movies/barbie-2023
```
supports only movies
=> Add trakt url support for inspect: Movies

Pipfile, Pipfile.lock, plextraktsync/decorators/coro.py, plextraktsync/decorators/flatten.py, plextraktsync/decorators/nocache.py, plextraktsync/decorators/rate_limit.py, plextraktsync/decorators/retry.py, plextraktsync/decorators/time_limit.py
Makes decorator code more readable, because nested functions no longer needed.
NOTE: [decorator](https://pypi.org/project/decorator/) is already in dependencies.
Also, not a clue why pipenv again changed all decorators: 4e6ff6f636cea8f53849b6e1e43d46b88978dbe4
=> Refactor: Use decorator package to make decorators

Pipfile, Pipfile.lock, requirements.pipenv.txt
Seems @dependabot still sucks and not able to track properly without entries in `Pipfile`:
- https://github.com/dependabot/dependabot-core/issues/6200#issuecomment-1325144662
So that dependabot doesn't go crazy and create incomplete pull requests:
- https://github.com/Taxel/PlexTraktSync/pull/1975
- https://github.com/Taxel/PlexTraktSync/pull/1980
- https://github.com/Taxel/PlexTraktSync/pull/1982
=> Pipenv: Track typing-extensions package for dependabot

plextraktsync/config.default.yml, plextraktsync/config/SyncConfig.py, plextraktsync/sync/Sync.py, plextraktsync/sync/TraktListsPlugin.py, plextraktsync/trakt/TraktUserList.py, plextraktsync/trakt/TraktUserListCollection.py
Also adds new config:
```yml
liked_lists:
keep_watched: false
```
You can also override `keep_watched` per list:
```yml
liked_list:
"Saw Collection":
keep_watched: true
```
Refs:
- https://github.com/Taxel/PlexTraktSync/issues/1494#issuecomment-1952495773
=> Feature: Add keep watched to liked lists

plextraktsync/config/SyncConfig.py
=> Fix: Respect playback_status and clear_collected from server config override

plextraktsync/plex/PlexApi.py
The previous code didn't work at all: it always took all matches are positive matches.
Credits for the `sum()` trick:
- https://realpython.com/python-flatten-list/
=> Fix matching of matches by name and value

plextraktsync/plex/PlexLibraryItem.py
Example:
- https://app.plex.tv/desktop/#!/provider/tv.plex.provider.discover/details?key=/library/metadata/60cefe5ed208b5002dd25f5f
It would fail because `is_discover` is giving false result.
=> Fix inspect of discover url

plextraktsync/plan/WalkConfig.py
Otherwise creating multiple instances of WalkConfig used static class properties.
=> Fix: Convert WalkConfig to dataclass

README.md
`docker-compose` --> `docker compose`
The official syntax of the command has changed. Many distributions and installers will automatically create an alias, but this should no be relied upon since it will not always be there. Documentation should be updated to reflect the standard syntax as defined by Docker. 
```
$ docker-compose
The program 'docker-compose' is currently not installed. It is provided by
several packages. You can install it by typing one of the following:
$ docker compose
Usage:  docker compose [OPTIONS] COMMAND
```
=> Update README.md: change docker-compose to docker compose because command syntax has changed

plextraktsync/cli.py, plextraktsync/commands/compare_libraries.py, plextraktsync/util/Factory.py
The idea is to find duplicates across different libraries, different servers allowed.
Currently supports only Movie libraries.
```
$ plextraktsync compare-libraries  --library1=me/Movies --library2=friend/Movies
```
NOTE: Someone (else) should write docs for README. Docs is not my thing.
=> Feature: Add compare-libraries command

pyproject.toml, setup.cfg
This is for tools like [rye][1] to work.
[1]: https://rye.astral.sh/
Refs:
- https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#writing-pyproject-toml
=> Refactor: Move project metadata to pyproject.yaml

pyproject.toml, setup.cfg
Looks like changes were incomplete from https://github.com/Taxel/PlexTraktSync/pull/2045
```
$ pipx install plextraktsync==0.31.11
Note: Dependent package 'python-dotenv' contains 1 apps
- dotenv
Note: Dependent package 'charset-normalizer' contains 1 apps
- normalizer
Note: Dependent package 'websocket-client' contains 1 apps
- wsdump
Note: Dependent package 'markdown-it-py' contains 1 apps
- markdown-it
Note: Dependent package 'pygments' contains 1 apps
- pygmentize
Note: Dependent package 'tqdm' contains 1 apps
- tqdm
No apps associated with package plextraktsync. Try again with '--include-deps' to include apps of dependent packages, which are listed above. If you are attempting to install a library, pipx should not be used. Consider using pip or a similar tool instead.
```
=> Build: Move entry points and packages to pyproject

plextraktsync/commands/plex_login.py
This ensures same instance is used across application.
Fixes: https://github.com/Taxel/PlexTraktSync/issues/2050
To test
```sh
docker build https://github.com/Taxel/PlexTraktSync.git#refs/pull/2052/head -t plextraktsync/2052
docker run -it --rm -v `pwd`/issue-2050-v2:/app/config plextraktsync/2052 sync                                                          ─╯
```
=> Fix: Use ServerConfigFactory singleton

README.md
Added container running state validation before executing the script as I noticed that the container was stopping after running the sync each time, and would not auto-start even with unraid's autostart switch toggled on. This change fixed the problem for me.
PS: This is my first time contributing to an open source project, I have read the contirbuting guidelines, please let me know if there is something wrong and how I could fix it! :) 🚀
=> Fixed documentation for unRaid sync script with container running state validation

README.md
Fix spelling mistake in command in line 230
=> README: Fix spelling mistake in plextraktsync command

plextraktsync/trakt/TraktUserList.py
When parsing and syncing lists from trakt to plex, only movies and episodes are processed. This adds support to process a whole season in a list.
Example list: https://trakt.tv/users/nmasnadithya/lists/mcu?sort=rank,asc
=> Parse & sync Trakt TV Seasons to plex

README.md
added a little help to hint at creating the necessary files elsewhere when docker image cannot be run from command-line (like on Synology NAS).
=> added info to documentation on creating ciritcal files without access to commandline

plextraktsync/cli.py, plextraktsync/commands/plex_login.py
Recreate https://github.com/Taxel/PlexTraktSync/pull/1635
Can login to MyPlex without need for user/password.
=> Feature: Re-use token for plex-login with --use-token flag

plextraktsync/plex/PlexLibrarySection.py, plextraktsync/plex/PlexSectionPager.py
Extracted from https://github.com/Taxel/PlexTraktSync/pull/1870
=> Fix: Add retry to some methods

plextraktsync/util/Rating.py
otherwise trakt would treat this as rating=1 (weak sauce):
- https://github.com/Taxel/PlexTraktSync/issues/2122#issuecomment-2567114618
Fixes https://github.com/Taxel/PlexTraktSync/issues/2122
=> Fix: Treat rating=0 as no rating

README.md
- Removes "schedule" profile in multi server setup since it doesnt work.
- Updates image versions so that it is cohesive through the whole documentation (latest on all).
- Updates config volume path so that it is the same in multi server config as it is in the single server config.
After discussions and testing for #2139.
=> Config updated: Working per server/library scheduling with ofelia

plextraktsync/config/HttpCacheConfig.py, plextraktsync/factory/Factory.py, plextraktsync/plex/PlexServerConnection.py
Such overrides actually work now:
```yml
policy:
"api.trakt.tv/users/me": 12d
"api.trakt.tv/search/imdb/tt*?type=movie": "7d"
"api.trakt.tv/search/imdb/tt*?type=show": "7d"
"api.trakt.tv/search/tmdb/*?type=movie": "7d"
"api.trakt.tv/search/tmdb/*?type=show": "7d"
"api.trakt.tv/search/tvdb/*?type=show": "7d"
"api.trakt.tv/shows/*/seasons?extended=episodes": "2d"
```
<del>Might even work like offline mode now.</del>
=> Update http cache rules to be more effective

plextraktsync/plex/PlexServerConnection.py
This would not print long trace of well known error
=> Catch BadRequest service_unavailable from plex separately

tests/test_tv_lookup.py
This reverts commit 06b743288148e81ba98fffb750a3ef799712efd1.
Fixed by https://github.com/Taxel/PlexTraktSync/pull/2166
=> Revert "Disable more broken tests in CI"

.pre-commit-config.yaml, pyproject.toml
Carry https://github.com/python-humanize/humanize/pull/236
=> Update pre-commit hooks (validate-pyproject v0.23)

pyproject.toml
This reverts commit 3db996fae1e7ea16885e15b86c9025af6d385330.
Setuptools is not yet ready:
- https://github.com/Taxel/PlexTraktSync/pull/2191#issuecomment-2690099403
=> Fix: Revert "Replace deprecated classifier with licence expression (PEP 639)"

plextraktsync/config.default.yml, plextraktsync/decorators/account_limit.py, plextraktsync/queue/TraktBatchWorker.py
Handles http error `420 Account Limit Exceeded` to ensure sync without crashing and stops sending further requests to the affected endpoints.
This error can occur when a free Trakt account attempts to add items to _collection_ or _watchlist_ that have already reached their limit.
The account limit was introduced to the Trakt API in February 2025.
Refs :
- https://forums.trakt.tv/t/freemium-experience-more-features-for-all-with-usage-limits/41641
Closes #2162
=> Fix: Handle Trakt error 420 Account Limit Exceeded

plextraktsync/sync/WatchProgressPlugin.py
This PR fixes issue #2196 where media marked as watched in Trakt was being set to 99.99% progress in Plex instead of being marked as fully watched. This caused media items to remain in the "Continue Watching" section with 0 seconds remaining.
- Modified `WatchProgressPlugin.sync_progress()` to check if the progress from Trakt is ≥ 99%
- For media with ≥ 99% progress, use `markWatched()` instead of `updateProgress()`
- Only use `updateProgress()` for media that is genuinely partially watched (< 99%)
- Updated the log messages to indicate when an item is being marked as fully watched
I've tested this by:
- Syncing content that was marked as watched in Trakt
- Confirming that items previously stuck at 99.99% are now properly marked as watched
- Verifying that items are removed from the …
=> Fix media remaining in "Continue Watching" due to 99.99% progress

.github/workflows/automerge.yml
> This is a scheduled Ubuntu 20.04 retirement.
> Ubuntu 20.04 LTS runner will be removed on 2025-04-15.
For more details, see
- https://github.com/actions/runner-images/issues/11101
See:
- https://github.com/Taxel/PlexTraktSync/actions/runs/14574394377/job/40877534817?pr=2234
Unbreaks:
- https://github.com/Taxel/PlexTraktSync/pull/2234
=> Switch ubuntu-20.04 with ubuntu-latest for fastify/github-action-merge-dependabot

.gitignore, plextraktsync/trakt/TraktApi.py, plextraktsync/trakt/TraktUserList.py, plextraktsync/trakt/TraktUserListCollection.py, plextraktsync/trakt/types.py
Adds #1879 
I'm not sure if the implementation inside [`load_items()` of `TraktUserList.py`](https://github.com/Taxel/PlexTraktSync/blob/e08ae81d463429059ca6f66a1b25d483b84c89e2/plextraktsync/trakt/TraktUserList.py#L100) is correct. Because the return type of `PublicList.load()` is different from `User().get_list()`, I had to write a new function `build_dict_from_raw_items()` to build a dictionary similar to `build_dict()` that takes in a `PublicList`. But it works!
Feel free to make any changes as you see fit.
I tested it by creating a private personal list and liking it. I then ran the program with `python -m plextraktsync --no-cache sync`. 
I also followed the [contributing guide](https://github.com/Taxel/PlexTraktSync/blob/main/CONTRIBUTING.md) and ran all tests.
For some reason, the …
=> Feature: Add support for private liked lists

plextraktsync/plex/PlexApi.py
With Plex Media Server _1.46.1_, the user sessions were detected as not available with a `401 Unauthorized` when PTS was logged with a non-admin Plex user.
With Plex Media Server _1.47.1_, the error returned is now a `403 Forbidden` raised  as `BadRequest` by [PlexApi](https://github.com/pushingkarmaorg/python-plexapi/blob/d5fcfd0bf41f123192be54cfb62f4db4a8eb1745/plexapi/server.py#L768-L773).
Fixes #2243
=> Handle BadRequest exception in PlexApi has_sessions method

README.md
I added an example to the readme that runs `PlexTraktSync watch`, and also schedules ofelia to run `PlexTraktSync sync` every 12 hours. This is the method I'm using with Unraid templates, and it works great.
=> Added example for watch command with scheduled sync

plextraktsync/plex/PlexApi.py
Add the providers parameter to the searchDiscover method call. Fixes the issue with syncing watchlist from Trakt to Plex.
Closes #2066
=> Added providers parameter for plex discover api
